### ISSUE TITLE
The file "/boot/mainsail-wpa_supplicant.txt" has become unusable

### ISSUE THREAD

**Issue by matsm85** [mainsail-crew/mainsail#1027]
### Mainsail Version:

v2.2.1

### Browser:

Chrome

### Device:

Laptop

### Operating System:

Windows

### What happened?

The file "/boot/mainsail-wpa_supplicant.txt" has become unusable
When moving the printer, it has no way to connect to a new network.
Nor modifying "/boot/mainsailos-wpa-supplicant.txt"
nor from the klipperscreen network connection option.

The /etc/wpa_supplicant/wpa_supplicant.conf file
is fulfilling the old function of the /boot/mainsailos-wpa-supplicant.txt file
the problem is that for end users there is no access to this directory from the sd card.

I haven't been able to use my printers for days, since I move them to different places where there are different networks.

When not finding a network, the printer tries to communicate via ethernet and does not allow you to select a Wi-Fi network from Klipperscreen as it did before.

### What did you expect to happen instead?

The file "/boot/mainsail-wpa_supplicant.txt" should allow you to connect to a new network.

### How to reproduce this bug?

try to change wifi network in file "/boot/mainsail-wpa_supplicant.txt"

**Comment by meteyou** [comment]
this repo is only for mainsail. mainsail is just a webgui and have nothing todo with the OS.
