### ISSUE TITLE
Macros - default parameters are not populating when read from object i.e. printer['configfile'] or variable

### ISSUE THREAD

**Issue by zebons** [mainsail-crew/mainsail#1040]
### Mainsail Version:

v2.2.1

### Browser:

Chrome

### Device:

Laptop

### Operating System:

Windows

### What happened?

I encounter the same issue in mainsail than that referenced in Fluidd (#650) and now closed :

The menu to populate the default parameter for a macro is not able to use values from objects. It's showing the name of the object instead i.e. "printer.configfile.settings.printer.max_velocity" (same issue with variables loaded priorly in the macro itself)

### What did you expect to happen instead?

The value should populate from the object i.e. printer.configfile.settings.printer.max_velocity should show the max velocity i.e. 300

### How to reproduce this bug?

[gcode_macro TEST_SPEEDABX]
gcode:
    {% set max_velocity = printer.configfile.settings.printer.max_velocity %}
    {% set speed = params.SPEED|default(max_velocity)|int %}

    
![image](https://user-images.githubusercontent.com/51046171/185885267-9811aa37-5468-4d3a-a589-620397faf1ae.png)

**Comment by meteyou** [comment]
yes, because only the config text will be parsed for this feature. its not possible to "execute" the marco to get "computed" values.

**Comment by zebons** [comment]
But it doesn't work better if I put that :
{% set speed = params.SPEED|default(printer.configfile.settings.printer.max_velocity)|int %}
I get that :
![image](https://user-images.githubusercontent.com/51046171/185916355-8ec1aaec-fc4c-4d37-8ab0-df94af69292f.png)

**Comment by zebons** [comment]
Ok But i get the same error if I put here a config test !
If I put that :
{% set speed = params.SPEED|default(printer.configfile.settings.printer.max_velocity)|int %}

I get that :

[image]<https://user-images.githubusercontent.com/51046171/185916355-8ec1aaec-fc4c-4d37-8ab0-df94af69292f.png>

De : Stefan ***@***.***>
Envoyé le :lundi 22 août 2022 12:56
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [mainsail-crew/mainsail] Macros - default parameters are not populating when read from object i.e. printer['configfile'] or variable (Issue #1040)


yes, because only the config text will be parsed for this feature. its not possible to "execute" the marco to get "computed" values.

**Comment by zebons** [comment]
OK so I’ll be ask for a FR. It’ll be nice to see what we get if we don’t put a value (instead of seing a part of the variable very unusefull)
Thanks



De : Stefan ***@***.***>
Envoyé le :lundi 22 août 2022 14:28
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [mainsail-crew/mainsail] Macros - default parameters are not populating when read from object i.e. printer['configfile'] or variable (Issue #1040)


yes, because it is only a "text parsing". just the string between the () of default will be used. nothing more...
