### ISSUE TITLE
New Uploaded Files From PC Does Not Showing In Mobile

### ISSUE THREAD

**Issue by ruredi87** [mainsail-crew/mainsail#1041]
### Mainsail Version:

2.2.1

### Browser:

Chrome

### Device:

Mobile device (Phone, Tablet or similar)

### Operating System:

Windows

### What happened?

These are the steps that I am following when I print someting

1- Slice file in pc
2-Upload from pc to RPİ via mainsail
3-Go to near printer and start print with mobilephone when observing printer.

When I upload any file from pc to rpi I am expecting to see fresh uploaded file in my android mobile. But I can not see it, even I change my mainsail page to files tab. I have to restart my android's browser to see new uploaded file. 

Mainsail should refresh files folder when I change tab to files.

### What did you expect to happen instead?

-----

### How to reproduce this bug?

To see bug these steps should followed

-Mainsail should be working on mobile (mine was android)
-New file should be uploaded via computer

After these steps We should be able to print new file with using android bu instead of that we cannot see new uploaded file. The only way to see it restart browser on android than gcode file should be there.

**Comment by meteyou** [comment]
this happens, when de browser is in "sleep mode" during the upload. so your smartphone does not recognize the "new file notification" from moonraker. just hit the "refresh" button in gcode files to update the file list.
