### ISSUE TITLE
Pie chart under History has overlapping labels

### ISSUE THREAD

**Issue by newphreak** [mainsail-crew/mainsail#1046]
### Mainsail Version:

v2.2.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

![image](https://user-images.githubusercontent.com/640287/186731089-b8d34449-959a-4cfd-9c9d-233763b3d831.png)
The pie chart has overlapping labels, makes it impossible to read

### What did you expect to happen instead?

Text to be spaced out to be readable

### How to reproduce this bug?

Get the percentages close enough to overlap

**Comment by meteyou** [comment]
thx for the report. i think i can only combine entries smaller than 2-3-4%. have to test the value.

so i would display all smaller entries as "others".
