### ISSUE TITLE
Adding job to print queue in 'gcode files' view adds strange entry in dashboard queue

### ISSUE THREAD

**Issue by abrenoch** [mainsail-crew/mainsail#1057]
### Mainsail Version:

v2.2.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When adding a gcode file to the queue in the 'gcode files' area, the queue on the dashboard gets this "one more job" entry added instead (appears to have correct metadata):

Files page:
![image](https://user-images.githubusercontent.com/2146139/188150700-fe366567-bf72-401c-a006-d97ca74bd55b.png)

Dashboard page:
![image](https://user-images.githubusercontent.com/2146139/188150820-6478c98c-76f1-40fb-af27-3710a65f7fac.png)

### What did you expect to happen instead?

The job on the dashboard page queue displays the correct filename & thumbnail

### How to reproduce this bug?

Start a queue of files, add a gcode file to the queue from the 'gcode files', return to the dashboard and view the queue

### Additional information:

I did have 5 jobs in my queue before I saw this behavior

**Comment by meteyou** [comment]
this is normal. only 5 files will be displayed. all other files will be stacked "one more job" or "123 more jobs". just add some more files to see it...
