### ISSUE TITLE
[FR] Hide "SAVE CONFIG" button

### ISSUE THREAD

**Issue by HyperToxic33** [mainsail-crew/mainsail#1066]
### Requested feature:

My printer is on all the time 24/7 - Bed Mesh is part of my PRINT_START.   SAVE CONFIG is always shown and I never know what it would save, because many thing trigger the display of SAVE CONFIG.  

Bed Mesh among other things causes SAVE CONFIG button to be shown and enabled.   There is currently no way to know what values will be changed when SAVE CONFIG is pressed.   I do not ever want to use this feature because of the ambiguity of what may be changed.

This best solution is to provide a toggle button in the config that hides the SAVE CONFIG button all the time.  That way I don't need to worry about accidently pressing the button and modifying my config file.

**Comment by meteyou** [comment]
> I do not ever want to use this feature because of the ambiguity of what may be changed.

this is not correct. this PR in klipper (<https://github.com/Klipper3d/klipper/pull/5270>) provide all new/changed things. so it is on my todolist to add this feature.

but also with this implemention. i would add some kind of "filter". so you can only hide the button for bed_mesh changes. i have the same issue on my switchwire. i create a new mesh at the beginning of every print.

**Comment by LazaroFilm** [comment]
One thing I'm not sure is understood. When you press SAVE_CPNFIG, it saves all the changes that were made to the bottom section of your printer.cfg file. It doesn't only save the last change made, but any and all scheduled change. But it only changes values in that bottom section, not throughout your Config. 
Also, it creates a backup of your Config file in its previous state.
