### ISSUE TITLE
BED_SCREWS_ADJUST helper dialog

### ISSUE THREAD

**Issue by meteyou** [mainsail-crew/mainsail#1070]
### Requested feature:

Implement a helper dialog for BED_SCREWS_ADJUST

**Comment by jwhb** [comment]
This is much appreciated.

Should the UI component be added to the heightmap tab or to it's own tab called "leveling"?

**Comment by meteyou** [comment]
this will be implemented like "manual_probe". when the function is started in klipper, a popup will be opened automatically. no matter where you are in mainsail.
