### ISSUE TITLE
Download multiple config files from machine page. 

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1074]
### Requested feature:

The ability to download multiple config files from machine page. 

### Solves the following problem:

Needing to click each file when backing up all config files.

**Comment by meteyou** [comment]
thx for this FR. sounds reasonable to me. i added it to the backlog.

**Comment by PhilBaz** [comment]
Awesome...thanks.

**Comment by Zodiak1993** [comment]
It would also be very handy, if you hit backup under settings in mainsail, that there is also a backup of the config path. Maybe selectable ?

I don't know if it is possible to create a .zip or .rar for this files.

**Comment by meteyou** [comment]
@Zodiak1993 i think for this i should talk to arksine that moonraker can offer a zip.
