### ISSUE TITLE
A layer number system for the 3d g-code viewer page.

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1075]
### Requested feature:

 A layer number system for the g-code viewer page similar to the viewers in Cura, Prusa, etc.  This would allow you to go directly to a particular layer in the g-code.

### Solves the following problem:

Currently the g-code viewer does not have a layer number system, so you are left to just search through the entire toolpath set with a single slider.  Each time you move the slider it takes a few seconds for the viewer to play. These two issues together make the viewer mostly unusable currently.

Often you want to see features of a particular layer. Bridging etc. With he current viewer its like 'good luck finding it'. I just end up going back to the slicer.

**Comment by meteyou** [comment]
as long as klipper does not have a layer system, it cannot be included. furthermore, the gcode viewer is an external lib that is only included in mainsail.

**Comment by PhilBaz** [comment]
Got it....thanks!

**Comment by meteyou** [comment]
@PhilBaz FYI: we are working on a klipper solution for real layer count: https://github.com/Klipper3d/klipper/pull/5726

**Comment by PhilBaz** [comment]
@meteyou 

Okay, I was going to submit a FR on klipper discourse but ill hold off then. I added an FR for reinclude there just now.

Thanks!
