### ISSUE TITLE
Add more colors to console messages using RESPOND command

### ISSUE THREAD

**Issue by Henlor** [mainsail-crew/mainsail#1076]
### Requested feature:

Add more colors to console messages using RESPOND command

### Solves the following problem:

- Better distinguish quickly the different types of messages into console 
- Get more control over colors displayed in the console

**Comment by Henlor** [comment]
This issue was resolved with this macro. 

https://github.com/Henlor/klipper_config_CR-6_SE/blob/65320b545e6f849a8874849be2db70b8647ffe18/macros/respond.cfg

**Comment by livinhack** [comment]
Resolved? I get this error: Existing command 'RESPOND' not found in gcode_macro rename

Mainsail 2.3.1

**Comment by th33xitus** [comment]
This has nothing to do with Mainsail

**Comment by livinhack** [comment]
His macro should work with mainsail so it's meant as additional info that I'm using it.

But what am I missing?

**Comment by Henlor** [comment]
> I think so too.
> 
> His macro should work with mainsail so it's meant as additional info that I'm using it.
> 
> But what am I missing?

You need to register the [respond] command first if you want to extend it with this macro
https://www.klipper3d.org/Config_Reference.html?h=respond#respond
