### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Rom4ik-glitch** [mainsail-crew/mainsail#1080]
### Mainsail Version:

v2.3.0

### Browser:

Other (Please tell us below)

### Device:

Laptop

### Operating System:

Windows

### What happened?

Not so long ago my UI goes mad - low contrast manu and white menu bar. After refreshing the page on second everything looks ok, but then this bug appears again.
![image](https://user-images.githubusercontent.com/63121302/190237022-b8f0c04c-57d0-4218-a907-e8a387a81a9e.png)

### What did you expect to happen instead?

Normal menu, as was earlier

### How to reproduce this bug?

Open browser.

### Additional information:

From phone everything works well.

**Comment by meteyou** [comment]
looks like a browser / add blocker issue
