### ISSUE TITLE
my.mainsail.xyz forget printers since two days.

### ISSUE THREAD

**Issue by paeppi88** [mainsail-crew/mainsail#1081]
### Mainsail Version:

2.3.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Since two days I open my.mainsail.xyz and no printer is shown. Only the Infoscreen in the picture below.
![image](https://user-images.githubusercontent.com/40436536/190235588-47a2e4f1-41b8-499b-9179-24cc86665706.png)

Then I add my printers by IP and everything looks normal.
![image](https://user-images.githubusercontent.com/40436536/190236086-3fe77a79-2219-4583-822a-22571f34fadd.png)

I can select one printer, but I can´t switch back to the second one.

If I reload my.mainsail.xyz my browser lost all printers.
I do not delete cockies or browser cache or something else.

I tryed it at my desktop PC with my standard browser chrome, with edge and a for testing downloaded version of firefox.
Also I tryed it with my Laptop using chrome and my android mobilephone. Every device shows the same failure.

### What did you expect to happen instead?

save printers

### How to reproduce this bug?

don´t know? Just press F5 to reload the Page?

**Comment by Henlor** [comment]
I have the exact same issue as you @paeppi88 

I'm on MacOS v.11.0.1 , Chrome v.105.0.5195.102 and all Mainsail packages are up-to-date.

**Comment by itajackass** [comment]
Having same issue: if i browse from my notebook (where all inatallation of klipper etc.. on my flsun speeder pad was done) all is ok..... But if I try to browse my.mainsail.xyz from another pc or tablet (same network of course) i lost all printers...

**Comment by meteyou** [comment]
> Having same issue: if i browse from my notebook (where all inatallation of klipper etc.. on my flsun speeder pad was done) all is ok..... But if I try to browse my.mainsail.xyz from another pc or tablet (same network of course) i lost all printers...

this is normal, because my.mainsail.xyz stores your printers in the browser store. so a other pc is another browser store.

**Comment by itajackass** [comment]
The problem appear also if I use direct ip....192.168.1.111 (ip of speeder pad / rasp pi)

**Comment by meteyou** [comment]
> The problem appear also if I use direct ip....192.168.1.111 (ip of speeder pad / rasp pi)

yes, because your browser have different stores for different addresses/URLs. next should be that the direct address should direct connect to moonraker or did you changed the config.json to enable the remote mode?

**Comment by itajackass** [comment]
I not edited config.json... i'm new on klipper and I followed a tutorial for flsun speeder pad and a Super Racer.... So...if I want to open mainsail web interface from smartphone (via wifi under same network) and see instantly all my printers.... Is there a way? Or for each device i need to re-add every time my printers?
