### ISSUE TITLE
[Improve] Extend css language support to scss files.

### ISSUE THREAD

**Issue by Henlor** [mainsail-crew/mainsail#1082]
### Requested feature:

Extend css language support in Codemirror for .scss and .sass extension files as well. 

### Solves the following problem:

At the moment, they are no syntax coloring for those file extensions.

**Comment by meteyou** [comment]
SCSS and SASS needs a preprocessor to work in the browser. so i don't think its very useful in mainsail itself.

**Comment by Henlor** [comment]
> SCSS and SASS needs a preprocessor to work in the browser. so i don't think its very useful in mainsail itself.

Yes it true, but you can install Sass on the Raspberry Pi to watch for file changes :D
