### ISSUE TITLE
[FR]Sliders for adjusting PA and smooth_time

### ISSUE THREAD

**Issue by Hywelmartin** [mainsail-crew/mainsail#110]
**Is your feature request related to a problem? Please describe.**
a simple way to alter PA and Smooth_time...]

**Describe the solution you'd like**
Like
![bild](https://user-images.githubusercontent.com/33714214/97198405-0a08da00-17af-11eb-91c8-61ff4a9aa22e.png)

**Describe alternatives you've considered**
buttons like Babystepping and current value displayed 

**Additional context**

**Comment by amp-man** [comment]
Also FW Retraction maybe?

**Comment by meteyou** [comment]
Yes... I think this is also important.
