### ISSUE TITLE
Completed print (without issue) is reported as "Cancelled" in the file status?

### ISSUE THREAD

**Issue by testanley3** [mainsail-crew/mainsail#1110]
### Mainsail Version:

2.3.1 (latest)

### Browser:

Other (Please tell us below)

### Device:

Other (Please tell us below)

### Operating System:

Linux

### What happened?

Every print when it is competed shows a status of "cancelled".  I just got the whole Klipper/Mainsail/KlipperScreen installation done on my Ender 6. Running on a Raspberry Pi 4.  Works GREAT! It's just that the status is reported incorrectly. Have I left something out? Thank you!

### What did you expect to happen instead?

I expected both the Webpage Dashboard to show "Print Completed Successfully" or somthing when such is the case.

### How to reproduce this bug?

Just running the print. I'm too new at this to know what I might be doing wrong.

### Additional information:

Thank you for any and all help

**Comment by meteyou** [comment]
The print history is handled by moonraker. Mainsail just display it. I think you use a macro for print end with a bug in it. That will bi your issue.
