### ISSUE TITLE
Duplicate file for G-code page - Maintains Thumbnail 

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1125]
### Requested feature:

Simple ability to duplicate G-code files in a way that maintains an associated thumbnail image. 

### Solves the following problem:

Sometimes I need to make a duplicate file and modify some g-code manually. This can be for testing, benchmarking, or simply to solve a short term problem. 

Currently I have to download and reupload a file. But when I do this, the thumbnail is lost. 

I use use moonraker connection for Cura, 'UFP with thumbnail'. It creates a thumbnail on export.

**Comment by meteyou** [comment]
Just use real gcode thumbnails with the cuts Postprozessor...

**Comment by PhilBaz** [comment]
@meteyou 

Ill check it out.... a duplicate function would still be nice though.

**Comment by PhilBaz** [comment]
@meteyou Sorry not finding it. Is that a Cura thing or a klipper thing?

**Comment by meteyou** [comment]
A cura thing

**Comment by PhilBaz** [comment]
@meteyou  Yes, got it! Thanks!

I think there would still be value in a duplicate g-code function? If not on the front page file list perhaps on the g-code page.
