### ISSUE TITLE
shutdown button reboot system

### ISSUE THREAD

**Issue by Guilouz** [mainsail-crew/mainsail#1138]
### Mainsail Version:

2.3.1

### Browser:

Chrome

### Device:

Other (Please tell us below)

### Operating System:

Linux

### What happened?

When use shutdown button, system reboot and not shutdown.

### What did you expect to happen instead?

Shutdown button shutdown system

### How to reproduce this bug?

Just click on shutdown setting

### Additional information:

OS : Ubuntu 20.04 LTS

Already tried sudo_fix.sh from Moonraker without success.

Also allow user 'pi' to reboot and shutdown without password without success.

systemd-logind service is already enabled is my distrib.

shutdown -H now command correctly shutdown my system but it seem machine.shutdown doesn't load this command

**Comment by meteyou** [comment]
`machine.shutdown` is a moonraker function. mainsail just call it and nothing more...
