### ISSUE TITLE
Potential of supporting "Arducam 64 MP" Camera

### ISSUE THREAD

**Issue by TheGameXIV** [mainsail-crew/mainsail#1143]
### Requested feature:

I know a while back, there was an issue with arudcam's 64 MP camera working with Mainsail/crowsnest. I believe due to the proprietary Kernel Module used for the libcamera stack. I was curious if this was still unsupported, or if workaround had been implemented?

### Solves the following problem:

Allows other users to use Arudcam's Autofocus camera's with Mainsail

**Comment by meteyou** [comment]
pls use the crowsnest repo for crowsnest questions...
