### ISSUE TITLE
Require confirm on Host Shutdown/Reboot

### ISSUE THREAD

**Issue by intelinc** [mainsail-crew/mainsail#1150]
### Requested feature:

Add a "Require confirm on Host Shutdown/Reboot" toggle to the UI-Settings menu that provides a confirmation dialogue before powering-down/rebooting the host.

### Solves the following problem:

Prevents inadvertent host shutdown from the dashboard of an inactive printer while an active print is in-progress on another printer connected to the same host.

### Additional information:

As someone who runs multiple printers per host RPI, it would be helpful to have a toggle in the UI-Settings that enabled the host shutdown/reboot confirmation outside of a print. I just accidentally rebooted a shared pi from one printer as another printer connected to that host was in the middle of a print. Totes my fault, but a duplicate of the "Require confirm on Device Power changes" toggle (which has saved my a$$ on more than one ocassion) that enforced an always-on confirmation of Host reboot/shutdown would be a nice late-night printing failsafe for users running multiple printers off a single host.

**Comment by meteyou** [comment]
There is no possibility to check about multiple instances and multiple instances are not recommended. So there will be no focus to such a feature.
