### ISSUE TITLE
Allow Support for Moonraker API Authentication

### ISSUE THREAD

**Issue by awickham10** [mainsail-crew/mainsail#1151]
### Requested feature:

Exposing Moonraker to the Internet can be dangerous, but Moonraker supports the usage of API keys, which reduces that risk. If Mainsail could support authenticating to Moonraker with their API keys, we could (somewhat) safely expose Moonraker endpoints to the Internet, allowing for easier remote access configurations.

### Solves the following problem:

Reduces risk of exposing Moonraker to the Internet. Reduces complexity of remote access.

**Comment by yang6991906** [comment]
Support your suggestion

**Comment by meteyou** [comment]
And this function is NOT to make your installation save in the internet. No part of Klipper was build to be safe in the internet!

**Comment by awickham10** [comment]
Thanks for the quick response. Is there a reason you think Moonraker's API authentication isn't sufficient enough? Definitely not an API security guru here but it seems like it's using pretty standard authentication mechanisms? It feels like a combination of CORS and this would make it somewhat safe aside from brute force attempts.

**Comment by meteyou** [comment]
Because the developer said it...
