### ISSUE TITLE
disable circle toolhead controls while printing

### ISSUE THREAD

**Issue by vajonam** [mainsail-crew/mainsail#1165]
### Requested feature:

at the moment toolhead controls like z_title_adjust and homing are able to be executed when printing is in progress. This should be disabled while printing. 

### Solves the following problem:

depending on the print, this will affect the z_tilt or other homing parameters if homed mid print.

**Comment by vajonam** [comment]
Looks like none of the buttons are disabled when using circle tool head controls.  More a bug than FR. this used to work before the 2.4.0 panel refactor.

**Comment by vajonam** [comment]
https://github.com/vajonam/mainsail/commit/e3a32ab724cee388c1a65bf015dee8d29bbc0c27

If anyone wants can submit a PR. seems my PRs just sit around, this is fixed on my branch that I build from so works for me.

**Comment by th33xitus** [comment]
was fixed with #1171
