### ISSUE TITLE
Webcam issue in my.mainsail.xyz

### ISSUE THREAD

**Issue by paeppi88** [mainsail-crew/mainsail#1173]
### Mainsail Version:

2.4.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

The Webcam is not shown when watching Printer over my.mainsail.xyz.
If I open the printer GUI by IP. Everything works correctly. The Settings are exactly the same.

This happend to all my printers. A few weeks ago everything works correctly. Perhaps there was an update in Mainsail 2.4.0

![webcam_issue](https://user-images.githubusercontent.com/40436536/204132860-5769a053-8977-49de-94ac-5b8226791466.PNG)

### What did you expect to happen instead?

Webcam should be shown in my.mainsail.xyz

### How to reproduce this bug?

tried it from different devices (Phone, Tablet) and different Browsers (Chrome, Firefox, Edge)

**Comment by meteyou** [comment]
Just use absolute paths or wait for the Bugfix release. You can read it in the support ticket.
.https://github.com/mainsail-crew/mainsail/pull/1162
