### ISSUE TITLE
Adaptive ETA based on layer status

### ISSUE THREAD

**Issue by odonnell944** [mainsail-crew/mainsail#1180]
### Requested feature:

Instead of averaging the 'Estimate' and 'Slicer' time remaining for the entire print, taper the ETA to align with one or the other depending on layer height. For many of us, the faster (or slower) accelerations allowed by Klipper significantly change the actual printing time. 

- Beginning of print: ETA is weighted to the slicer prediction (Mainsail estimate is wildly off during first few layers due to reduced speed).
- Intermediate time of print: Mainsail looks at actual progress, based on completing layer X of Y, and weights the ETA to whichever one is making more sense at the time. Instead of 50/50.
- Close to end of print: The Mainsail estimate should be heavily weighted to the ETA.

Example: slicer says 5 hours, but we know it will be done in 4 hours. In the last 5 minutes of the print, the ETA will be off by nearly 30 minutes. But it is obvious from the layer progress that the Mainsail estimate is the best ETA to use.

### Solves the following problem:

Inaccurate ETA when slicer is not aware of increased or decreased accelerations.

**Comment by meteyou** [comment]
thanks for your FR, but nothing of that is possible with klipper right now.
