### ISSUE TITLE
search function in gcode tab seems to not be working correctly 

### ISSUE THREAD

**Issue by DKS-18** [mainsail-crew/mainsail#1181]
### Mainsail Version:

2.4.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

when using the search bar in the g-code files tab the search results are from only the currently displayed directory

### What did you expect to happen instead?

when using search boxes in windows / other programs typically it will display results from included sub-directories. I feel this should be the standard behaviour for searches in the g-code tab

### How to reproduce this bug?

search for a file placed within a sub-directory / folder. It won't be shown in the search results

**Comment by meteyou** [comment]
This is no bug because the search function should work exactly like this.
