### ISSUE TITLE
Webcam on RPi USB 3.0 Port

### ISSUE THREAD

**Issue by TheBToby** [mainsail-crew/mainsail#1182]
### Mainsail Version:

2.4.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

My USB 3.0 webcam connected to a USB 3.0 port on the RPi4 is not being recognized. When I plug the webcam into a USB 2.0 port of the RPi4, the camera is being detected with no issue but with a very low frame rate of approx. 10-15 fps.

The camera does not show up in /dev/v4l/by-id/

The camera is working on a USB 3.0 port on my laptop with no issue.

### What did you expect to happen instead?

Connected webcam on USB 3.0 port of RPi4 being detected and supporting high frame rates

### How to reproduce this bug?

Connect USB 3.0 webcam to RPi4 USB3.0 port and check ID in /dev/v4l/by-id/

**Comment by meteyou** [comment]
Mainsail is just a webgui and has nothing todo with your host. pls, report this bug to raspberry or your webcam vendor.
