### ISSUE TITLE
PR #1162 breaks webcam display for url port other than 80

### ISSUE THREAD

**Issue by Arti4ever** [mainsail-crew/mainsail#1197]
### Mainsail Version:

2.4.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Since Mainsail 2.4.1, webcam display is no longer working if server utilise a port other than 80. 
It works with Mainsail 2.4.0. 

This is the PR #1162 that breaks this feature. 

I use a reverse proxy to acces to mainsail and I set the port to 10130.
The PR #1162 remove the part of code that set this port for the webcam stream. 
`url.port = this.hostPort.toString()`

is it possible to revert this commit ?

### What did you expect to happen instead?

I expect that it works same as in Mainsail 2.4.0.

### How to reproduce this bug?

access to Mainsail with a port other than 80, and try to display the webcam.

**Comment by meteyou** [comment]
This function breaks many other usecases. Just use an absolute URL for your usecase.
