### ISSUE TITLE
FR: Highlight current extruder in Panel

### ISSUE THREAD

**Issue by Googliola** [mainsail-crew/mainsail#1201]
### Requested feature:

In a multi-tool setup, it would be helpful to see what tool is activated.

![image](https://user-images.githubusercontent.com/505490/208494338-ecb91d59-7596-4f45-b032-bbe412c24717.png)

Either color the text or (more favourably) the button color.

**Comment by meteyou** [comment]
atm there is no option to read this from Klipper

**Comment by meteyou** [comment]
This is already implemented with the PR #1244 . I just forgot to link this issue...
