### ISSUE TITLE
Add temps to toolbar

### ISSUE THREAD

**Issue by apphead** [mainsail-crew/mainsail#1204]
### Requested feature:

There is some valuable screen estate wasted in the top tool bar which could be used to display current temps and on mouse-over target temps as well.
If possible, clicking on a temp would show the presets to select from.

### Solves the following problem:

Temperatures panel takes up a lot of space (I know the chart can be hidden) and it is the only way to see the temps and modify them, even though most of the times you just want to know what is going on.

**Comment by meteyou** [comment]
This would not work on smaller screens or with more temp sensors. I think this is also not the best solution to be generic.
