### ISSUE TITLE
Clear log file(s)

### ISSUE THREAD

**Issue by apphead** [mainsail-crew/mainsail#1205]
### Requested feature:

Add button to Mainsail > Machine > Log files panel toolbar that clears the content of a logfile.

Ideally, one can chose which logfile to delete  (klippy.log or moonraker.log etc) from a dropdown.

Optionally, a backup of the current logfile klippy-[datetime].log is created for later inspection if required.

### Solves the following problem:

As the logfile grows over time, it would be nice to start from scratch and create a clean klippy.log that contains only entries related to a certain scenario (such as testing, debugging etc.)

**Comment by meteyou** [comment]
This is not possible, because mainsail have only read rights to the log path. Pls make a FR to Moonraker.
