### ISSUE TITLE
Add KlipperScreeen to Log Files sections.

### ISSUE THREAD

**Issue by BlackNet** [mainsail-crew/mainsail#1210]
### Requested feature:

Add KlipperScreen logs to the "Log Files" section.

Klipper, Moonraker, and Crowsnest are listed; it would be super good to add KlipperScreen to the list since both can be installed side by side.

**Comment by meteyou** [comment]
Use the dropdown in the config files panel to see the complete printer_data/logs directory. We don't want to have every logfile with buttons. This will be too much.
