### ISSUE TITLE
The port is missing for camera access

### ISSUE THREAD

**Issue by blandown** [mainsail-crew/mainsail#1211]
### Mainsail Version:

v2.4.1

### Browser:

Other (Please tell us below)

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Browser: Brave
Moonraker:  v0.7.1-780

Hello, I'm migrating to mainsail.

I have a DNS in which I redirect port 3030 to 80 on my rpi, which opens the mainsail.

However, the camera is not working.

I checked and noticed that it is trying to access the camera without port 3030.

https://imgur.com/a/a0BFuNf

The correct is to try to access: ***.net:3030/webcam/?action=snapshot ...

when I try to access  ***.net:3030/webcam/?action=snapshot, it works here.

### What did you expect to happen instead?

Open the camera with specified port.

When access mainsail with :  ***.net:3030

Have an error connecting to the camera because it trying to access the wrong link

Now: ***.net/webcam/?action=snapshot ...
Expect: ***.net:3030/webcam/?action=snapshot ...

### How to reproduce this bug?

Access outside the local LAN using a specific port

**Comment by meteyou** [comment]
Just use absolute URLs. port forwarding or something similar is not supported.
