### ISSUE TITLE
FR: Time to next manual filament change

### ISSUE THREAD

**Issue by crazyminecuber** [mainsail-crew/mainsail#1214]
### Requested feature:

When printing models you want to change the filament to a different color after some layers, for example this model [https://www.printables.com/model/35520-metric-nut-screw-measuring-tool](https://www.printables.com/model/35520-metric-nut-screw-measuring-tool)

This means that you, after some amount of time, have to manually change the filament. I would be really useful to have an estimate of how long time is left until I have to do the filament change. So I suggest adding a timer to estimate the time to the next manual filament change. Maybe also add a notification so that I can get a notification on my phone/web browser when it is time to change filament.

### Additional information:

Is Prusa slicer/superslicer, color changes after a certain layer are handles by adding a M600 command in the gcode so you could predict the time until you hit that command. Maybe Cura handles that slightly differntly though I am not really sure.

**Comment by meteyou** [comment]
Mainsail is just a GUI and only runs on the client in the browser. So if you don't have Mainsail open in your browser, it won't run. So notifications are not possible. But you can use Moonraker notify for this use case and just add it to your M600 macro.

Furthermore, Mainsail has no access to the gcode to read it, and a position of a gcode (M600) in a file is not useful to make a prediction of how long it will take. For that, you would have to simulate the whole gcode to estimate a time.

Such a function would have to be integrated into the slicer, as this has all the data and can then be passed to Klipper via gcode or similar. This data could then be read out and displayed by mainsail from Klipper.
