### ISSUE TITLE
Option to exclude files in folders from the main page file list

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1216]
### Requested feature:

Option to exclude files in folders from the main page file list

### Solves the following problem:

Don't want them there.

### Additional information:

Sorry to make so many FR. I use mainsail everyday, multiple times. So I just get lots of little ideas. 

I very much appreciate all your effort and love mainsail, for sure.

**Comment by meteyou** [comment]
Sry. i don't see a real use case for this and the dashboard file list should only display the latest/newest files. i think it makes more sense to combine it with the "pinned files". so just display always the pinned files first.
