### ISSUE TITLE
Klipper Version Warning

### ISSUE THREAD

**Issue by lloydpick** [mainsail-crew/mainsail#1220]
### Requested feature:

It's very easy to update the hosts Klipper though mainsail, which is fantastic. However, as I think most people would agree that while it's not necessarily harder to update the MCUs, it is certainly more involved. Which I imagine can lead people to not keeping their Klipper versions in sync.

Although I'm not 100% sure on what sorts of issues or problems could occur if the versions are not matching?

### Solves the following problem:

Perhaps it would be worth showing some sort of warning that the versions don't match?

**Comment by meteyou** [comment]
If the version doesn't fit or both parts have different functions/names, you will get a Klipper error when starting Klipper. But this is not part of Mainsail. It only displays the Klipper error. If you don't see this error, your MCU version is fully compatible with your host version (also when it is not the same).

So a warning not matching Klipper versions between MCU and Host would be wrong.
