### ISSUE TITLE
Exclude object does not show the map (on a delta printer)

### ISSUE THREAD

**Issue by mattcalavera** [mainsail-crew/mainsail#1221]
### Mainsail Version:

2.4.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

When start a printing of a corrected processed file for 'exclude object' funtion, all work as expected except for the map of objects, which is empty and I can only see the list of object on the right and an empty rectangle on the left.
If i pass the mouse over the empty rectangle (in the top left corner) it shows the name of 1 of the objects.
I HAVE A DELTA PRINTER (maybe it's a coordinate issue on maps programmed for cartesian which have all postive coordinates?)
<img width="626" alt="Screenshot 2023-01-09 alle 22 58 47" src="https://user-images.githubusercontent.com/3481862/211416756-69759623-2c10-4f94-b2cc-4cf7705502ed.png">
<img width="961" alt="Screenshot 2023-01-09 alle 22 58 56" src="https://user-images.githubusercontent.com/3481862/211416765-8da6f33a-0fb9-40d2-9bc1-b88e69020cbb.png">
<img width="986" alt="Screenshot 2023-01-09 alle 22 58 51" src="https://user-images.githubusercontent.com/3481862/211416767-40de6813-40b1-4f3a-831c-ad8863dc0d6b.png">

### What did you expect to happen instead?

I expect to see the objects on the map

### How to reproduce this bug?

When start a printing of a corrected processed file for 'exclude object' funtion, all work as expected except for the map of objects, which is empty and I can only see the list of object on the right and an empty rectangle on the left.
If i pass the mouse over the empty rectangle (in the top left corner) it shows the name of 1 of the objects.
I HAVE A DELTA PRINTER (maybe it's a coordinate issue on maps programmed for cartesian which have all postive coordinates?)

**Comment by meteyou** [comment]
Already fixed and will be part of the next release. 

https://github.com/mainsail-crew/mainsail/pull/1217
