### ISSUE TITLE
Layout Reset confirmation

### ISSUE THREAD

**Issue by leitenky** [mainsail-crew/mainsail#1222]
### Requested feature:

If you click the reset layout button ( in settings / Dashboard)  add a confirmation dialog pop up, confirming desire to proceed before resetting.

### Solves the following problem:

Accidently hitting the reset layout button in Settings / dashboard, and resetting dashboard layout unintentionally

**Comment by meteyou** [comment]
i don't think it's too much of a loss to reset a layout. i also don't want to add a confirm to every button, because i find it very very annoying.
