### ISSUE TITLE
Support parsing webcam config out of moonraker conf

### ISSUE THREAD

**Issue by greenbigfrog** [mainsail-crew/mainsail#1226]
It would be nice, if mainsail supported just grabbing the webcams from the moonraker config. Setting them up via the website isn't that hard, but just grabbing it from the config file would be easier.
https://moonraker.readthedocs.io/en/latest/configuration/#webcam
(I tried my best making sure this isn't a duplicate, but perhaps it is.)

**Comment by meteyou** [comment]
This is already implemented with this PR: #1445 . I just forgot to link this issue.
