### ISSUE TITLE
How to add UI control for z1, z2, and z3 stepper motors

### ISSUE THREAD

**Issue by neon5d** [mainsail-crew/mainsail#1234]
### Requested feature:

Hello, 
I wonder how I can add UI control for the z1, z2, and z3 stepper motors.
Can you explain the procedure or the documentation?
Thank you

**Comment by meteyou** [comment]
All z-steppers will combine into one axis. Therefore you can only move them all together via the GUI.

But there is also a force_move command in Klipper. This command moves steppers and not axes. You can address single steppers with this command (same as the buzz_stepper command).

But we don't use GitHub for support. Only for bugs or feature requests. So please use our discord for such questions.

**Comment by neon5d** [comment]
Thank you for the information.
I will check the Discord-Server to get some more information.
Thank you.
