### ISSUE TITLE
Default to dashboard screen when switching printer through the Printers tab

### ISSUE THREAD

**Issue by HitLuca** [mainsail-crew/mainsail#1236]
### Requested feature:

I have two printers, and I can switch between them through the menu near the printer name on the top bar, or by going to the `Printers` tab. If I switch printer using the second method (`Switch to printer` button) Mainsail correctly switches printer but stays on the `Printers` tab. To me it's better to redirect the user to the `Dashboard` page when switching printer, since no new information is shown when staying on the `Printers` tab

**Comment by meteyou** [comment]
This affects all pages. Sometimes, it is better to stay on the current page.

For example, when comparing two settings. So I don't think there is a generic good unique solution for this. So I prefer the current behaviour.
