### ISSUE TITLE
Sonar service is stopped once reboot finishes

### ISSUE THREAD

**Issue by Gosga365** [mainsail-crew/mainsail#1238]
### Mainsail Version:

2.4.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I have been having wifi connection dropping problems and saw that Sonar is built into Mainsail now as a keepalive service. When I boot the pi running mainsail, I can see the message saying that sonar is started during the initial boot. However, at the very end of the boot another message says stopping sonar and stopped sonar. I would like to have the sonar service running on my pi since I am having the issues it was designed to fix, but I do not know how to make it stay running after the boot finishes.

### What did you expect to happen instead?

I expected sonar to be started during the system boot and stay running while the printer is on.

### How to reproduce this bug?

Install mainsailos on a fresh raspberry pi. boot the pi and monitor the displayed lines during boot. Stopping sonar should be one of the last five lines before the pi prompts you to login.

**Comment by meteyou** [comment]
pls post this issue in the sonar repo. this issue tracker is only for mainsail bugs/FRs.
