### ISSUE TITLE
Layer number being reported incorrectly.

### ISSUE THREAD

**Issue by iplayfast** [mainsail-crew/mainsail#1242]
### Mainsail Version:

2.4.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

While a print is happening, the Dashboard show (for example) Layer 260 of 360.
The problem is that there are 534 layers in the model. The model prints fine, just the layer count is wrong.

I've gotten around this problem by  adding the following to the Layer Change Section of my slicer.

M117 laying {layer_num+1}/{total_layer_count}

What this does is show the real layer number in the front display.
However it would be much better for it to be showing on the dashboard.

### What did you expect to happen instead?

Correct values

### How to reproduce this bug?

Apparently happens with every print.

**Comment by meteyou** [comment]
Pls use the search or join our discord. This issue posted many times, why we started a Klipper pr to fix it, but you have to use slicer special settings.
