### ISSUE TITLE
after loading history - there are already 2 selected jobs

### ISSUE THREAD

**Issue by fused3dprints** [mainsail-crew/mainsail#1265]
### Mainsail Version:

v2.4.1

### Browser:

Edge

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I just noticed that i automatically have 2 selected jobs whenever i load history tab but the details are now shown.
I can export the jobs (via CSV) and can confirm these are old jobs i printed but have deleted them long time ago.

![image](https://user-images.githubusercontent.com/112317534/218464010-637ccfab-4fe2-4236-ba1e-25460501db23.png)
[print_history.csv](https://github.com/mainsail-crew/mainsail/files/10722385/print_history.csv)

### What did you expect to happen instead?

my other printer does not have any "pre-selected" jobs when selecting the history tab

### How to reproduce this bug?

i just need to open the history tab

### Additional information:

moonraker.log shows 2 Invalid job uids when i press the "delete" button

utils.ServerError: Invalid job uid: 0000E5
utils.ServerError: Invalid job uid: 000103

[moonraker.log](https://github.com/mainsail-crew/mainsail/files/10722371/moonraker.log)

**Comment by meteyou** [comment]
pls post your output of http://<ip or hostname>/?namespace=mainsail

**Comment by Luoti** [comment]
I had this problem too. Solved it by deleting the `selectedJobs` from the database with curl:

```bash
curl -X DELETE "http://[IP_OF_THE_PRINTER]/server/database/item?namespace=mainsail&key=view.history.selectedJobs"
```
