### ISSUE TITLE
Recommend Android app that works with Mainsail IP camera functionality

### ISSUE THREAD

**Issue by shaunmulligan** [mainsail-crew/mainsail#1266]
### Requested feature:

There are a bunch of android apps that turn old phones into IP cameras. Does anyone know of any that work with mainsail?

### Solves the following problem:

Allows people to use old android phone as an IP camera for their 3D printer

**Comment by meteyou** [comment]
Any app with an MJEPG output should work.

**Comment by shaunmulligan** [comment]
@meteyou thanks! I haven't yet found one that has mjpeg output, so might have to make one :P
