### ISSUE TITLE
Webcam fails when nginx runs on custom port

### ISSUE THREAD

**Issue by iovsiann** [mainsail-crew/mainsail#1276]
### Mainsail Version:

v2.4.1

### Browser:

Edge

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I have several printers behind a router's firewall. To access printers when away from LAN, I've tunneled firewall ports. For example, https://example.com:8081 connects me to printer #1 by tunneling port 8081 to printer #1 MainSail port 80. That works, except MainSail webcam stops working. The reason for the webcam not working is MainSail omitting the port in the webcam widget.
''''
GET https://example.com/webcam/?action=stream net::ERR_CONNECTION_REFUSED
''''
The correct webcam URL as seen away from LAN is https://example.com:8081/webcam/?action=stream However, MainSail makes the browser try reaching the webcam at https://example.com/webcam/?action=stream That fails, of course.
So, to fix this issue all you need is to append the port number to the webcam request.

### What did you expect to happen instead?

Webcam stream widget works when MainSail runs on its standard HTTP port 80. Webcam stream widget fails when MainSail runs on a non-standard port (as seen from WAN), e.g. 8081.

### How to reproduce this bug?

Forward your router's port to access MainSail running at LAN 192.168.1.100 (port 80) to be exposed on WAN as example.com:8081. Launch MainSail - successfully - and observe that the webcam widget is NOT streaming. In the screenshot below I'm using HTTPS with identical results.
![Untitled](https://user-images.githubusercontent.com/9521508/219941175-a736ca24-4fe9-4a57-8a26-d530e4178fa3.png)

**Comment by meteyou** [comment]
you have to use a absolute path for this use case. next to it... don't use port forwarding to use mainsail from external. use a VPN!!!!

we already tried this (to use the current port for webcams). this breaks all multi instance installations. this is a common use case right now and thats the reason we dropped this "feature".
