### ISSUE TITLE
Questions about the Power Button

### ISSUE THREAD

**Issue by Samuel-0-0** [mainsail-crew/mainsail#1280]
### Mainsail Version:

2.5.0-beta1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

After reopening the power device for controlling the printer, the device state remains closed.It is necessary to click the button status again after the printer control page is displayed on Mainsail to make it work properly.I have two Homeassistant power devices, one respectively for controlling printer supply and hotbed AC power.

![m2](https://user-images.githubusercontent.com/23371663/219992804-c85c7a46-76ce-4ee6-a961-2c75a155cbcc.png)

I also tried v2.5.0-beta1. When I turned off the power of the printer, there was no power button displayed in the dashboard.I have selected the power device to control the power of the printer in the settings.

![m1](https://user-images.githubusercontent.com/23371663/219992781-7fc92d3b-2127-40dd-9676-2a9216678232.png)

I don't know if this is a problem with my settings or a bug.

Translated by ChatGPT.

### What did you expect to happen instead?

Fix this problem or provide usage suggestions.

### How to reproduce this bug?

Add two HomeAssistant power devices, one of which controls the printer power.

### Additional information:

My moonraker config

[power printer]
type: homeassistant
address: 192.168.88.111
port: 8123
device: switch.printer_power
token: aaaaaaaaaaaaaaaaaaaaaaaaa
domain: switch
on_when_job_queued: True
locked_while_printing: True
restart_klipper_when_powered: True
restart_delay: 1.

**Comment by meteyou** [comment]
you have to add:
```
bound_services: klipper
```
to your power device. without this setting, your power device is not correct configured and klipper is running in the background and searching the board
