### ISSUE TITLE
Turnable Thumbnail

### ISSUE THREAD

**Issue by Ringo80X** [mainsail-crew/mainsail#1281]
### Requested feature:

I think it would be helpful if we could rotate the thumbnail of the currently printed part by cursor.

**Comment by meteyou** [comment]
I can't think of a use case for it... What would be the advantage of having the image upside down?

**Comment by DVSVIDEO** [comment]
I think what the user meant here is that the small stamp image is a 3D image and he wants to rotate it in space.
He doesn't know that the slicer only "takes" a tiny picture of the model and puts this tiny picture into the .stl file.
I suggest you switch to the 3D g-code viewer tab and press the local file button there and then you can rotate the model for printing.

**Comment by meteyou** [comment]
Ahh ok! Now I understand this FR.

No this is not possible, because it's just an image, which will be created from the Slicer. (as @DVSVIDEO already described)

**Comment by Matszwe02** [comment]
In the other hand, there could be something like automatic thumbnail generation, like gcode viewer, but only for making that 3d thumbnail. It will be still a nice idea, visible cross section, etc.

**Comment by meteyou** [comment]
the gcode viewer needs the most performance of the complete mainsail interface. so this is really overkill for this function.
