### ISSUE TITLE
Mainsail can't read my C922 pro stream webcam, nor C615

### ISSUE THREAD

**Issue by DuckersMcQuack** [mainsail-crew/mainsail#1295]
### Mainsail Version:

2.3.1

### Browser:

Chrome

### Device:

Other (Please tell us below)

### Operating System:

Linux

### What happened?

I can't add the webcam, no image appears with any of the video processers on C922 pro nor C615

### What did you expect to happen instead?

A video feed

### How to reproduce this bug?

Use the mentioned cameras

**Comment by meteyou** [comment]
pls check your streamer software. Mainsail only display streams. nothing more. If it cannot display it, there is no stream.

**Comment by DuckersMcQuack** [comment]
> pls check your streamer software. Mainsail only display streams. nothing more. If it cannot display it, there is no stream.

It's not streamed, It simply won't display any image from either of the cam's in the webUI.

**Comment by meteyou** [comment]
as i wrote above. pls check your streamer!

**Comment by DuckersMcQuack** [comment]
> as i wrote above. pls check your streamer!

Oh sorry, i have a weird thing were i only read every second word. How do i check the streamer? Any config files i have to edit? If so, which ones? As just selecting different streamers and rebooting does nothing sadly.

**Comment by DuckersMcQuack** [comment]
I got it working, had to install crowsnest.
