### ISSUE TITLE
Theme Switch

### ISSUE THREAD

**Issue by Steven2k6** [mainsail-crew/mainsail#1297]
### Requested feature:

A switch to change the Theme from dark to Light and backwards.

I made a Vuetify3 Project as example.

![code](https://user-images.githubusercontent.com/99575824/223164827-4f409594-491f-4d9f-9717-4f846fa80797.png)

Maybe you can also add a setting to set the colors for the Dark and Light Theme.
I uploaded a zip with the Vue-File.
[Switch-Test.zip](https://github.com/mainsail-crew/mainsail/files/10900195/Switch-Test.zip)

**Comment by meteyou** [comment]
Feel free to made a PR, but there are some parts, which also needs some other css settings, because only switching to light mode doesn't fit.

**Comment by Steven2k6** [comment]
I don't know if its possible, because I'm relativ new to programming, but isn't it possible to create a public variable for the colors which you can edit in an editor or setting menu?

**Comment by meteyou** [comment]
All interface settings are the same function like this. It's only more work, than just a switch. You have to restyle all charts and other functions for the light mode.

**Comment by Rigattoni** [comment]
Are there plans and may be an ETA for the light mode?
The dark mode is nice, but sometimes you really need some better contrast as it is given with the dark mode, at least if you are working outside and have a sunny day. Then it is quite hard to see the stuff. 
Mostly the editor is not readable anymore. Yes, I can download the file to edit it in notepad ++... Easier to handle would be to have a white background and contrasting colors in the editor itself.

**Comment by meteyou** [comment]
@Rigattoni this is just a hobby project. so we don't have any ETA...

light mode is planned, but there are much more important things i have to implement, before i can implement a light mode. I hoped, that a contributor will fix this missing issue before...

**Comment by meteyou** [comment]
I added all missing tags and milestones. Maybe it is better visible now for contributors.
