### ISSUE TITLE
print % Complete isn't accurate

### ISSUE THREAD

**Issue by asm308** [mainsail-crew/mainsail#1299]
### Mainsail Version:

v1.0.0-8-g2615e14 

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

The % complete often starts off at several % complete before the print has even started.  I guess this is because its working of file size and that includes the image of the object which is skipped over.  Also it often shows 100% complete when its still got a few minutes to go.

Only minor points but it would be nice if it was accurate

### What did you expect to happen instead?

expected the %complete to be representative of how much of the print has occured

### How to reproduce this bug?

print any gcode file with an embedded picture

**Comment by meteyou** [comment]
pls check your setting and if you see metadata for this job. normally the "intro" and "outro" of the gcode should be calculated if you use "relative file calculation".
