### ISSUE TITLE
Allow adjustable tab size in file editor

### ISSUE THREAD

**Issue by IpsissimusMarr** [mainsail-crew/mainsail#1304]
### Requested feature:

Tab size is fixed to 2 spaces, making code difficult to read. Most editors allow changing tab size. This is a QOL improvement.

### Solves the following problem:

Currently tab size is 2 spaces, which makes code readability difficult for some files.

### Additional information:

Tab size adjustment can be added under Interface Settings -> Editor
![image](https://user-images.githubusercontent.com/1762290/224521585-8d464482-bce6-473a-8ae8-ce2575ae9e0a.png)

**Comment by forgodtosave** [comment]
Hi, I'm very interested in this project and I would love to contribute to it. Since this issue sound perfect to get familiar with the project I would like to try to solve it in the next 1-2 weeks.
