### ISSUE TITLE
Reset Print Statisctics

### ISSUE THREAD

**Issue by Steven2k6** [mainsail-crew/mainsail#1305]
### Requested feature:
Because I didn't find the option for it, I write this feature request.

Recently I got new filament, because my old ran out. Than I went to the Statistics tab to reset the statistics it, because I roughly want to know, how much of my new filament I already used. So maybe you could add an option to reset the statistics.

![Statistics](https://user-images.githubusercontent.com/99575824/224990748-6604da77-0133-4b59-9527-607cf55e2bae.png)

### Solves the following problem:

Adding a reset button for the statistics.

**Comment by meteyou** [comment]
Its already implemented. Goto interface settings > reset > history stats.

**Comment by Steven2k6** [comment]
> Its already implemented. Goto interface settings > reset > history stats.

Where do I find the interface settings?

**Comment by alexdaums** [comment]
Hello,

I can't find the function : settings > reset > history stats.
Is there any other way to do it?

Thank you.
