### ISSUE TITLE
Option for autocollapse macro group

### ISSUE THREAD

**Issue by TodWulff** [mainsail-crew/mainsail#1307]
### Requested feature:

As discussed on Discord, it is requested that a feature be added to have the Macro Panels possess a configuration option of auto expanding/collapsing on mouseover/mouseout events.

### Solves the following problem:

Provides users with more real-estate for UI elements that warrant being displayed all the time, while lesser used macro panels can be set to automatically open/collapse only when the user intends to use them and mouses over same.  I suspect that this feature would be employed by many Mainsail users.  Thank you for your time and consideration.  Take care.  ~MHz

**Comment by meteyou** [comment]
i'm closing this FR because i don't see a good possibility to implement this feature without causing other issues.
