### ISSUE TITLE
Different between estimate time from slicer and mainsail

### ISSUE THREAD

**Issue by JackyHe398** [mainsail-crew/mainsail#1315]
### Requested feature:

![image](https://user-images.githubusercontent.com/62739796/226386819-2732db82-2892-4741-b061-5fdebe7a6b1f.png)
From the photo, when (the actual time is >  the estimate time from the slicer), it shows "--" only. 

I think that maybe better if it can show how much time it has overrun. Users can have a clear concept about the time of the future print. Slicer is not always accurate. 

### Solves the following problem:

This is nothing related to bugs

**Comment by meteyou** [comment]
then i would prefer to check the history, because you don't know how long this print will need in the current state

**Comment by JackyHe398** [comment]
Interesting. 

I would like to ask is there any reason not to show that overrun time? Maybe from other perspective, it may not always be a good idea?

**Comment by meteyou** [comment]
just my 2 cents. i personally don't see any advantage in displaying them. but if it's wanted by many, i see no reason not to add this feature.

**Comment by mikebcbc** [comment]
@meteyou this issue can be closed - it's merged in

**Comment by meteyou** [comment]
Thx for the ping
