### ISSUE TITLE
Printer name in browser tab during printing

### ISSUE THREAD

**Issue by ckvsoft** [mainsail-crew/mainsail#1322]
### Requested feature:

It would be nice if the name of the printer remained in the tab when printing or was appended to the progress display in the tab.
With several printers this is annoying.

**Comment by mikebcbc** [comment]
I made a PR that got merged that adds this. Once it's released i think this issue can be closed

**Comment by meteyou** [comment]
normally i close the FR when i merge (automatically by github because the issue is linked in the PR)

**Comment by mikebcbc** [comment]
Cool!
