### ISSUE TITLE
Exclude Object button gone

### ISSUE THREAD

**Issue by srbjessen** [mainsail-crew/mainsail#1323]
### Mainsail Version:

2.5.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Exclude object button seems to have been replaced with "Pause on layer" button
![image](https://user-images.githubusercontent.com/92088582/227748442-4e11a131-e7fe-4c5a-8a2c-7820279eeb11.png)
![image](https://user-images.githubusercontent.com/92088582/227748453-b26dc0db-7da2-4d42-94ca-50c9cdb10cb4.png)

### What did you expect to happen instead?

When print starts, "Exclude Object" button used to appears next to "Pause" and "Cancel Print"

### How to reproduce this bug?

Happens on every print

**Comment by meteyou** [comment]
It's not a bug, it's just a wrong config.

**Comment by srbjessen** [comment]
Exclude object works, it's in the status panel above (currently missing) M117 messages.
![image](https://user-images.githubusercontent.com/92088582/227750520-ad52ceec-f40d-4f12-8176-820fac8039b7.png)
I just can't see the overview of the buildplate and select an object to cancel, only cancel currently active part.
But i will doublecheck config and ask discord if further issues.

**Comment by meteyou** [comment]
Is this print only with one object?

**Comment by srbjessen** [comment]
Current print is only one object yes, but it happens with multiple objects too. Will try to reboot/reset everything and double check my configs, might have done something screwy that I've forgotten about.  :-)

**Comment by meteyou** [comment]
I hide the button at the top when there is only 1 object, so you can click the layer pause button directly without the drop-down menu.

**Comment by srbjessen** [comment]
Is that new in 2.5? That might be what's messing with me. It used to be there, with both 1 and multiples.
It's working now at least. Thanks and sorry :-)

**Comment by meteyou** [comment]
yes. it comes with the "pause on layer" feature. if you have both options available, you will see a submenu with both buttons. i don't to have a submenu when there is only 1 object, because object canceling with 1 object is not very useful. So i hide this option to have only the "pause on layer" function in the toolbar.

**Comment by srbjessen** [comment]
Awesome, then it's once again just me :-)
Keep up the good work. 👍
