### ISSUE TITLE
Localization support - link not working

### ISSUE THREAD

**Issue by JendaDH** [mainsail-crew/mainsail#1325]
### Mainsail Version:

Mainsail OS 1.0.1

### Browser:

Safari

### Device:

Laptop

### Operating System:

macOS

### What happened?

Trying to add language support and this source points to "testing" the translation -> https://docs.mainsail.xyz/overview/developement/localization

However the link is broken. I would like to test the .json myself first to see translated texts make sense in whole context before creating pull request.

### What did you expect to happen instead?

Link to work -> https://docs.mainsail.xyz/development/environment

### How to reproduce this bug?

follow the URL

**Comment by meteyou** [comment]
thx for your report. I fixed the link in the docs.
