### ISSUE TITLE
[FR] Add customizable plots (fan speed, volumetric flow, etc)

### ISSUE THREAD

**Issue by 2nOrderEDO** [mainsail-crew/mainsail#1332]
### Requested feature:

It will be quite cool to be able to add custom plots to the main menu, plotting some already available parameters: fan speed, volumetric flow, even why not, positions, speed, etc.

I think it would be a super useful tool for troubleshooting and improving printers.

**Comment by meteyou** [comment]
Thx for your request. There is only one issue (currently). Mainsail has no access to the history of these data. So if you open Mainsail, all these values will begin to record. Refresh or close/open will reset these charts. There is only the possibility of getting a range of these data from the temp elements from Moonraker.

So there must first be an option in Moonraker to store these values and provide them via API.
