### ISSUE TITLE
Extruder load/unload filament kebab menu looking for case sensitive macro names

### ISSUE THREAD

**Issue by agreen** [mainsail-crew/mainsail#1333]
### Mainsail Version:

2.5.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I'm using the klipper macros provided by https://github.com/jschuh/klipper-macros - Within those macros, they have a load_filament and unload_filament macro, however they are in lowercase.  Reviewing the code for Mainsail, it's specifically looking for LOAD_FILAMENT and UNLOAD_FILAMENT and due to this, fails to display the kebab menu or the macros

### What did you expect to happen instead?

The load_filament and unload_fiament options and kebab menu under extruder to be present

### How to reproduce this bug?

Create an uppercase LOAD_FILAMENT and UNLOAD_FILAMENT macro.
Observe you can see the kebab menu and options under extruder.
 Rename the macros to lowercase load_filament and unload_filament.
Observe you can no longer see the kebab menu or options.

### Additional information:

I have also opened up a bug at https://github.com/jschuh/klipper-macros/issues/64 for the same issue. This can temporarily be resolved by renaming the macro to uppercase, however since Klipper is case insensitive for the macro names, it really should be Mainsail that resolves the issue.

Worth note, this would also possibly affect the temperature_wait clause within the load/unload filament logic, and optionally, anywhere else within the UI where a klipper macro is being looked for, as you can't guarantee the case of the gcode macro.

I have tested a modification of the code from 
`return this.macros.find((macro: PrinterStateMacro) => macro.name === 'LOAD_FILAMENT')`
to 
`return this.macros.find((macro: PrinterStateMacro) => macro.name.toUpperCase() === 'LOAD_FILAMENT')`
to resolve the issue with minimal code update.

Note: this would also need to be done in the unload filament macro (and again, anywhere else where you are looking for macros

**Comment by meteyou** [comment]
Thx for your report and debugging! I created a PR for it. Feel free to create next time direct a PR.
