### ISSUE TITLE
Github Integration in Config Files Dialog

### ISSUE THREAD

**Issue by cjohnson-phys** [mainsail-crew/mainsail#1334]
### Requested feature:

I think it could be useful to have commit, push, and pull buttons visible in the config files dialog that would run the respective git commands if it was found that the config directory was a git repository.

Of course it would need to check that not only is it a git repository but also has a remote origin attached.

It could potentially get a little clunky because appropriate configuration of GitHub credentials would be left to the user. An input box asking for a commit message would likely be necessary. I could also see some potential problems in the case of merge conflicts, but the user should be able to resolve them in the editor and re-commit.

But I could see this as an extremely useful feature.

### Solves the following problem:

QoL improvement that would keep the user from having to open an ssh session to push/pull changes to GitHub.

### Additional information:

Likely related: https://github.com/Arksine/moonraker/issues/531

**Comment by meteyou** [comment]
Mainsail itself is only a webgui with no direct access to the filesystem. So this have to be first integrated in Moonraker. Mainsail can only use the functions of Moonraker. So Pls create this FR, when this is integrated in Moonraker.
