### ISSUE TITLE
連続印刷に関するリクエスト

### ISSUE THREAD

**Issue by Km0107** [mainsail-crew/mainsail#1345]
### Requested feature:

It is a continuous printing feature that is available as a plug-in in octoprint.

### Solves the following problem:

Continuous printing of single G-code files reduces losses due to printing failures of G-code files with multiple parts bundled together.

### Additional information:

I am a beginner and not yet familiar with mainsail.
If you already have such a feature or if it is possible to implement it by means of a macro, I would be glad to know how to do so.

**Comment by meteyou** [comment]
Just use the job queue or solve it with gcode. If you need help to config it, Pls use our discord.
