### ISSUE TITLE
Schedule print starts

### ISSUE THREAD

**Issue by Lecso11** [mainsail-crew/mainsail#1346]
### Requested feature:

I imagine just RMB clicking on the file in the gcode browser, and there could be an option to schedule the print to start at the given time.

### Solves the following problem:

There are prints that need my attention, because of an auto-pause (color swap, inserted nuts etc.) and I don't want the printer to sit paused, heating the bed for hours. But for better productivity, I would schedule it to pause around the time I'm available to handle the printer (back from work, woken up etc).

**Comment by meteyou** [comment]
Mainsail is just a webgui. If you close your browser, it is not running. So this feature have to be a part of Klipper or Moonraker.
