### ISSUE TITLE
Object cancel dialogue doesn't recognize objects. 

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1362]
### Mainsail Version:

current 

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Object identified in pre-processor doesn't appear in object cancel dialogue. The objects name is 'Eraser'. 

![234613637-991c8b14-8f7f-4fcc-a0d1-3e8899fa0a72](https://user-images.githubusercontent.com/21558241/235489047-eb50c94f-1aac-453e-895f-fbda6165013a.jpg)

### What did you expect to happen instead?

'Eraser' is a printed object and should be shown in the object cancel dialogue. Visually on the display and in the list.

### How to reproduce this bug?

Slice a file in Cura and use a mesh to 'modify settings for overlap'. As shown here: https://support.makerbot.com/s/article/1667417981430

**Comment by PhilBaz** [comment]
@meteyou  Hi Stefan, yes looks like you are right. After doing some testing it looks like it working fine.

 Ill dig into the file where it was not working and see if I can understand why. Its a complex slice in Cura with many per-object settings and overlapping settings. I thought it was mainsail as when i edited
 EXCLUDE_OBJECT_DEFINE NAME=Eraser, to be EXCLUDE_OBJECT_DEFINE NAME=Eraser_3mf, It worked suddenly. 

Sorry about that.

**Comment by meteyou** [comment]
pls close this issue, when all works fine in your case...
