### ISSUE TITLE
Allow to start any print from queue not only first one

### ISSUE THREAD

**Issue by ristein** [mainsail-crew/mainsail#1379]
### Mainsail Version:

2.5.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Having multiple files in queue but I can't use it as a todo-list because I can only start the job added first from queue screen.

### What did you expect to happen instead?

Should be possible to start any file from queue not having to go look for it in files tab

### How to reproduce this bug?

add two file to queue
try to start second one

**Comment by meteyou** [comment]
Why should this be a bug?

**Comment by ristein** [comment]
Why should this be intentional?

**Comment by th33xitus** [comment]
> Why should this be intentional?

It's currently the intended behavior. Should this be rather a feature request instead?

**Comment by ristein** [comment]
that would be great

**Comment by meteyou** [comment]
fixed with the PR #1692
