### ISSUE TITLE
Allow pin/favorite gcode files.

### ISSUE THREAD

**Issue by GAZ082** [mainsail-crew/mainsail#1399]
### Requested feature:

May times I print the same 20x20 sheet when I adjust my bed or want to see everything is fine, but its cumbersome to look for it in the file list. Would be nice to have an option to pin it and by doing so goes to the top of the list, like in Whatsapp conversations.

Mockup:
![image](https://github.com/mainsail-crew/mainsail/assets/100194/7c6c3018-6f43-4ee5-9ed0-c679f41da389)

**Comment by meteyou** [comment]
you only have to create a directory and put the gcode file in it. directories are always on the top.

**Comment by GAZ082** [comment]
> you only have to create a directory and put the gcode file in it. directories are always on the top.

Nice workaround. But yet pinning would be nice.

**Comment by meteyou** [comment]
To be honest, I see no advantage in pinning, compared to a directory.

**Comment by GAZ082** [comment]
You will still want to have files on the top in that folder once the number of files increases.

**Comment by meteyou** [comment]
Pinned files are also increasing and block space from other new files...

**Comment by GAZ082** [comment]
> Pinned files are also increasing and block space from other new files...

If you overuse, yes. But you are free not to use.

I added a mockup to my first post.

**Comment by meteyou** [comment]
Sry, but I don't see any advantage with pinned files compared to the folder. Rather only disadvantages, such as lost space in the width and blocked entries in the list.

**Comment by th33xitus** [comment]
Honestly i would also just move the files i print regularly into a favorites folder, you can prefix it with `000_` for example and make sure it always stays at the very top (if you sort by name). It has the advantage that all your favorite files are in one place without blocking any space at all in the upper directory of the filebrowser. I see the ROI of that pinning feature quite low tbh.

**Comment by GAZ082** [comment]
> Sry, but I don't see any advantage with pinned files compared to the folder. Rather only disadvantages, such as lost space in the width and blocked entries in the list.

If width is a concern, just add it as a right click option.

**Comment by GAZ082** [comment]
> Honestly i would also just move the files i print regularly into a favorites folder, you can prefix it with `000_` for example and make sure it always stays at the very top (if you sort by name). It has the advantage that all your favorite files are in one place without blocking any space at all in the upper directory of the filebrowser. I see the ROI of that pinning feature quite low tbh.

000_ is a hacky way, Mainsail is sleek.

**Comment by forgodtosave** [comment]
Doesn't issue #1257 already exist for this?
I actually think this feature is a very nice idea.

I could try this. Should the pin be permanent or only available via the right-click menu?

**Comment by meteyou** [comment]
@forgodtosave i would prefer it via right click and add the icon to the print status icon. so we don't waste space for smaller displays

**Comment by meteyou** [comment]
but since the other FR is "older", i would close this issue, because it is a dublicate.
