### ISSUE TITLE
Print History and different gcode with same filename

### ISSUE THREAD

**Issue by Riksu9000** [mainsail-crew/mainsail#1402]
### Mainsail Version:

v2.5.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

In the print history, mainsail seems to match a print with a gcode file using the filename. The issue is if the gcode file is replaced, it still finds a matching file, even though it is not the same print.

The top file is displayed for reference. The rest are clearly different prints, but they show the same thumbnail and the option to reprint.

![Screenshot 2023-05-29 at 20-01-47 Trident](https://github.com/mainsail-crew/mainsail/assets/37774658/906399c9-fd4c-48ec-b985-fd6bb8f8d142)

### What did you expect to happen instead?

Mainsail should not match the history entry with a gcode file if the file has changed or has different properties.

### How to reproduce this bug?

Print two different gcode files that have the same filename.

**Comment by meteyou** [comment]
@Riksu9000 Pls post the output of: http://\<ip or hostname\>/server/history/list, that i can doublecheck your result from Moonraker. I think the "file exists" check comes from Moonraker and is no Mainsail function. but i have to double-check it.

**Comment by Riksu9000** [comment]
It seems that the list only contained the last 50 entries, which didn't include the earlier example, so I recreated the situation and here are the results.

![Screenshot 2023-05-29 at 22-08-22 Complete - test gcode](https://github.com/mainsail-crew/mainsail/assets/37774658/25c4a7ac-1e89-47bd-a773-6594d32f2212)

[trimmed.zip](https://github.com/mainsail-crew/mainsail/files/11593736/trimmed.zip)

**Comment by meteyou** [comment]
yeah thats right. 50 entries ist die default length. mainsail have to grab 50 entries till it is finished with all entries... thx i will debug it and get back to you.

**Comment by meteyou** [comment]
its interessting, because Moonraker think these files exists, but mainsail show it as "deleted". so i cannot find an issue here.
or do i interpretate the screenshot wrong?

**Comment by Riksu9000** [comment]
The last screenshot is showing the files as existing, because the text is white and it displays the thumbnail. The first entry of the first screenshot shows how it should look like if the file is missing.

In the last screenshot, only the top print should show the file as existing. The rest should not display the thumbnail and be gray, because they're a different print as shown by the estimated time and the information in the json file.

**Comment by meteyou** [comment]
ok. then it is an issue in Moonraker. Moonraker response in the json result, that alle files exists. mainsail just display the state from Moonraker in this case.

so pls open an issue in the Moonraker tracker.
