### ISSUE TITLE
Add function to print last file from physical button

### ISSUE THREAD

**Issue by Goodfeat** [mainsail-crew/mainsail#1405]
### Requested feature:

It would be nice to make a macro that could start re-printing the last file

For example:
### simple example
[gcode_macro last_file] 
    {action_respond_info('action:start')}

In this case, a reprint of a file that has already been previously sent for printing will be launched.

 ### complex example
[gcode_macro START_PRINT]
gcode:
	SAVE_VARIABLE VARIABLE=lastfile VALUE={mainsail.print_namefile}

[gcode_macro LAST_FILEPRINT]
gcode:
       START_PRINT NAME=printer.save_variables.variables.lastfile
Here is about the same, only a specific file name for printing is indicated, the name of which can be saved in a separate file

### Solves the following problem:

This solution allows you to quickly launch a file for printing without leaving the printer.

**Comment by meteyou** [comment]
Mainsail is just a gui and is only running in your browser. But I thin this should work already with Klipper gcode buttons. Pls use the support forum, if you need help to set it up.
