### ISSUE TITLE
Large thumbnail dosent work with gcode thumbnail ?

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1408]
### Mainsail Version:

2.5.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I don't get large thumbnail previews on gcode files with imbedded gcode thumbnails. But I do get them if the gcode file has a side-car image. Like when i choose 'UFP with Thumbnail' in connect moonraker

Just me?

![hgjhghj](https://github.com/mainsail-crew/mainsail/assets/21558241/5adab83f-4a12-41cf-8d54-1bbf2bf5512e)

### What did you expect to happen instead?

Same large thumbnail display on mouse over in gcode tab, or on the main page when printing.

### How to reproduce this bug?

Use gcode thumbnail type.

**Comment by meteyou** [comment]
please read the docs: https://docs.mainsail.xyz/overview/slicer/cura

**Comment by PhilBaz** [comment]
@meteyou Ahhh, the second thumbnail script....Sorry!!!
