### ISSUE TITLE
[FR] Error message keyframes on temperature graph

### ISSUE THREAD

**Issue by RaspberryPiDude314** [mainsail-crew/mainsail#1410]
### Requested feature:

I'd love a small timestamp icon on the temperature graph in the dashboard. It would be a small icon that stands out, probably at the top of the graph. Hovering would display the error message. The icons would be timestamped to when the error message was sent, and move with the graph.

### Solves the following problem:

It would make it much easier to debug heating problems and see where and when things go wrong.

### Additional information:

It would obviously have to be user toggleable through the settings menu or the config.

**Comment by meteyou** [comment]
We use a js lib for the graph. This can only display charts. No other stuffs. So it's not possible to add something like this.
