### ISSUE TITLE
Fan adjust like flow adjust and speed. 

### ISSUE THREAD

**Issue by JohnDCC** [mainsail-crew/mainsail#1436]
### Requested feature:

An adjustment slider like the speed or flow ones that scales up part cooling fan (to a max of 100).

### Solves the following problem:

When fan settings aren't quite right, allows you to save a print mid print by adjusting up or down the cooling.

**Comment by meteyou** [comment]
This is implemented since on of the first releases of Mainsail:

![image](https://github.com/mainsail-crew/mainsail/assets/8167632/0f6aefe5-e68e-40ae-b012-d5d559bb6270)

The first slider with the name `Fan` is your `[fan]`.

**Comment by JohnDCC** [comment]
Yes this adjusts the current fan level but gets overwritten as soon as the gcode changes it to something else. What I am proposing is a multiplier that gets applied over the gcode.

**Comment by meteyou** [comment]
Klipper has no option for that. So this needs first to integrated in Klipper.
