### ISSUE TITLE
Trash-bin feature like in Windows and Linux

### ISSUE THREAD

**Issue by Johan501** [mainsail-crew/mainsail#1439]
### Requested feature:

A trash bin feature, so if you delete a .cfg file it's not for definitely till you empty the trash bin.
I did missed it, for now especially when I accidentally deleted the printer.cfg file instead of clicking on downloading.

### Solves the following problem:

A trash bin

**Comment by th33xitus** [comment]
I think we simply forgot to add the confirm dialog to single files on deletion via context menu in the past. There is a PR in review right now which implements that dialog. I think that should be sufficient to deal with accidental file deletes, right?
