### ISSUE TITLE
Can't upload file with "Upload and print" button

### ISSUE THREAD

**Issue by Otann** [mainsail-crew/mainsail#1440]
### Mainsail Version:

2.6.0

### Browser:

Safari

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

I recently notices that the "upload and print" doesn't do anything, the open dialog does not open, like it usually does. The drag'n'drop works though as before, but I have to go to files and click print there.

Is it something with Mainsail or with my Safari? What should I check?

### What did you expect to happen instead?

I expected the "Open file" dialog to appear

### How to reproduce this bug?

I've got a freshly build Voron 0.2 with an klipper image for CB1, updated the Mainsail to the latest.

**Comment by meteyou** [comment]
i double-checked it with Chrome and Safari without any issues. so it looks like an issue on your client pc.
