### ISSUE TITLE
Spoolman filament manager integration

### ISSUE THREAD

**Issue by Donkie** [mainsail-crew/mainsail#1446]
### Requested feature:

Moonraker will [soon](https://github.com/Arksine/moonraker/pull/651) support integration to my latest invention, [Spoolman](https://github.com/Donkie/Spoolman).

Front ends will be able to interact with the full [Spoolman API](https://donkie.github.io/Spoolman/) through a proxy available in Moonraker. So eventually, creating a full CRUD interface is entirely possible if so desired.

However, as a starting point, the most essential thing is being able to set/get the "active spool", which is the spool that Moonraker will track filament usage of to the Spoolman server. This can be done though the [web API](https://github.com/Arksine/moonraker/blob/364eef7481976e4a81a29b0a04745f77dd198eae/docs/web_api.md#spoolman-apis).

As a second step, displaying more information about the active spool would be cool, such as remaining filament, etc. Also perhaps having warnings pop up if the remaining filament isn't enough for a print before starting it?

**Comment by meteyou** [comment]
Oh nice! This is a highly requested feature in the klipper world. Thank you for your work. I will ping you, if I have questions for the implementation or I have something to test.

**Comment by patofoto** [comment]
Amazing!!!. Already running Spoolman on a Docker on my NAS. Soooooo looking forward to this integration. I am just a hobbyist good enough with computers to get in trouble by getting way too deep beyond my knowledge. I understand the concept of how everything is working but need to learn how to make API calls and display the results.

**Comment by patofoto** [comment]
@Donkie Apologies if this is too basic a question. I am currently running Spoolman on my NAS. I assume I can install Docker directly on my control board and run Spoolman there?.  It is a BTT Manta E3EZ with a BTT CB1 and their latest image.

**Comment by Donkie** [comment]
Never used that myself, but if it can run regular ARM/x86 programs then yes it should be possible.

Please use the mainsail discord in the future for any questions. Spoolman has it's own channel there, #spoolman

**Comment by meganssmith** [comment]
any update on this?  Would love to help test

**Comment by numindast** [comment]
> @Donkie Apologies if this is too basic a question. I am currently running Spoolman on my NAS. I assume I can install Docker directly on my control board and run Spoolman there?. It is a BTT Manta E3EZ with a BTT CB1 and their latest image.

This targets running on the host where Mainsail / Moonraker / Klipper are running. So this would be on a Raspberry Pi or other host computer you use.

**Comment by nelsongraca** [comment]
Any predicted date on this?
