### ISSUE TITLE
Create backup folder for config files

### ISSUE THREAD

**Issue by solo2424** [mainsail-crew/mainsail#1456]
### Requested feature:

Can we have backup printer configs be saved in a directory inside of the config directory? When tinkering with settings. I tend to get many files that looks something like this "printer-20230626_101646.cfg". It would be nice if these could be tucked away inside of a directory, so we can have quicker access to the files we need to edit. 

### Solves the following problem:

The problem is less of a problem but more of a potential convenience. It would keep the config folder cleaner and easier to work out of. 

### Additional information:

The directory name could be something like "backup_configs".

**Comment by meteyou** [comment]
Mainsail is only a gui and display the state of your printer. These files are created by Klipper. So this change have to be in Klipper itself. You can just hide it in mainsail (cogs button in the config file panel).
