### ISSUE TITLE
Slow website UI load times

### ISSUE THREAD

**Issue by jLynx** [mainsail-crew/mainsail#1468]
### Mainsail Version:

v2.5.1 _(Edit: Just updated to v2.6.0 and still have the same issue)_

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When I load the webpage it takes around 8-20 seconds to load. (Validated on multiple high-end devices). 

### What did you expect to happen instead?

The page to load a lot faster than it currently does

### How to reproduce this bug?

If you have a lot of history file, you will see this slow down. I just with a lot of use time (438hours) 

### Additional information:

hso the issue seems to be that it loads the entire history on page I it. My suggestion is to have it load the top X from history (maybe 10?) and the rest of the history can be loaded on the history page load 

![image](https://github.com/mainsail-crew/mainsail/assets/4393979/6b25dd00-0373-454a-8870-c65f18ebca4a)

![image](https://github.com/mainsail-crew/mainsail/assets/4393979/67cc0bf0-dd11-4b92-a10d-c05d29e4d0fc)

https://github.com/Rat-OS/RatOS-configuration/assets/4393979/61c7380c-8376-4ade-ab3c-a7b693c39aa6

https://github.com/Rat-OS/RatOS-configuration/assets/4393979/4aa5a27d-b621-418f-bfd6-3ccf810838ad

You can find my DB here: 
[data.zip](https://github.com/mainsail-crew/mainsail/files/12073713/data.zip)

**Comment by zellneralex** [comment]
See also https://discord.com/channels/758059413700345988/1130299768661344288

**Comment by jLynx** [comment]
After resetting my DB it still took ages to load.
After restoring the DB and then removing all my ``/home/pi/printer_data/gcodes`` files the page now loads contently in 3 seconds which is much better.

So that tells me that is still forcefully loading all the data in the ``gcodes`` folder on load

**Comment by jLynx** [comment]
My OS is 64 Bit 
![image](https://github.com/mainsail-crew/mainsail/assets/4393979/9ed04429-52e1-4565-891e-e7bcd0e63b8d)
