### ISSUE TITLE
gcode uploaded from prusa slicer not showing up in mainsail web dashboard

### ISSUE THREAD

**Issue by LeHungryBoi** [mainsail-crew/mainsail#1478]
### Mainsail Version:

v2.6.0 

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

gcode uploaded from prusa slicer, sometims doesn't end with .gcode or have space bar in the file name, and those gcode while uploaded won't show up in mainsail dashboard.

### What did you expect to happen instead?

the file being recognized by mainsail

### How to reproduce this bug?

upload gcode from prusa sclicer and write file name with space bar and/or without .gcode extension.

**Comment by meteyou** [comment]
You cannot upload files to mainsail. Mainsail is only a Webinterface.
