### ISSUE TITLE
Filament cannot be extruded, and the extrusion button is gray and cannot be pressed.

### ISSUE THREAD

**Issue by skyaee** [mainsail-crew/mainsail#1490]
### Mainsail Version:

v2.6.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

https://github.com/mainsail-crew/mainsail/assets/40803751/cec9e3ff-d922-46e5-818c-c41c141eab23

Filament cannot be extruded, and the extrusion button is gray and cannot be pressed.

### What did you expect to happen instead?

Filament cannot be extruded, and the extrusion button is gray and cannot be pressed.

### How to reproduce this bug?

Filament cannot be extruded, and the extrusion button is gray and cannot be pressed.

**Comment by BlackShadeOSS** [comment]
It happened to me a lot of times, you just need to refresh browser to fix it. It happens when you do firmware restart when the printer is hot.

**Comment by skyaee** [comment]
> 这种情况我遇到过很多次了，只要刷新一下浏览器就可以解决。当打印机很热时重新启动固件时会发生这种情况。

**Comment by meteyou** [comment]
@skyaee thank you for the tip with the reset after a high extruder heater. pls write here only in english... i will reopen this bug report and try to fix it.

**Comment by meteyou** [comment]
Ok. I found a bug in the API init process. After a firmware_restart/restart it always initialize the extruder>can_extrude value as false and don't update it after that, only you pass the min_extrude_temp. So i added a "hack" to reinit this value after a short delay.

A real fix of this, have to be implemented in Moonraker/Klipper, bit it would work fine with my fix in Mainsail.
