### ISSUE TITLE
Setting temperature of a temperature_fan results in "Temperature too high" error

### ISSUE THREAD

**Issue by Gunner087** [mainsail-crew/mainsail#1500]
### Mainsail Version:

2.6.1

### Browser:

Safari

### Device:

Laptop

### Operating System:

macOS

### What happened?

I have a temperature_fan named "Chamber" configured in klipper for controlling the chamber temperature of my printer. When attempting to set the temperature of "Chamber" using the "target" field on the mainsail interface, an error is shown that says "Temperature too high for Chamber! (max: 0)" even though the maximum temperature is set to 70 in the printer.cfg file. It seems that this is only an issue with the mainsail interface since if I used the console to send "SET_TEMPERATURE_FAN_TARGET temperature_fan=Chamber target=60" the fan is set to 60C as expected.

### What did you expect to happen instead?

The temperature of the temperature_fan should be set to the value typed into the "target" field.

### How to reproduce this bug?

Setup a temperature_fan with the settings below and change the temperature using the "target" field of the mainsail interface.

[temperature_fan Chamber]
pin: PB4
max_power: 1.0
shutdown_speed: 0.0
cycle_time: 0.00004
hardware_pwm: false
kick_start_time: 0.0
off_below: 0.0
sensor_pin: PF5
sensor_type: Generic 3950
control: pid
pid_kp: 500.0
pid_ki: 0.1
pid_kd: 0.0
min_temp: 0.0
max_temp: 70.0
pid_deriv_time: 2.0
target_temp: 0.0
max_speed: 1.0
min_speed: 0.15

### Additional information:

klipper version: v0.11.0-250-ge9534d6f

screen recording:
https://github.com/mainsail-crew/mainsail/assets/65746045/5370adb9-3102-47a0-a595-7b1c4620a67c

**Comment by meteyou** [comment]
This bug is already fixed: https://github.com/mainsail-crew/mainsail/pull/1491
