### ISSUE TITLE
temperature_fan show NaN RPM with no tachometer pin defined

### ISSUE THREAD

**Issue by fredrikasberg** [mainsail-crew/mainsail#1501]
### Mainsail Version:

2.6.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

Updated from 2.6.0 to 2.6.1.

Temperature Fan configured without tachometer pin is showing up in temperature card with 'NaN RPM' as well as state 0%.

`[temperature_fan chamber]
pin: FAN3
max_power: 1
shutdown_speed: 0.0
sensor_type: ATC Semitec 104GT-2
sensor_pin: TH0
min_temp: 0
max_temp: 70
target_temp: 55.0
control: watermark
gcode_id: C`

### What did you expect to happen instead?

No mention of RPM in temperature card and state showing the text 'Standby' instead of 0%.

### How to reproduce this bug?

Upgrade from 2.6.0 to 2.6.1

### Additional information:

2.6.0
![image](https://github.com/mainsail-crew/mainsail/assets/21010797/0f5e8022-23ba-4907-9b80-4b5ba26ce041)

2.6.1
![image](https://github.com/mainsail-crew/mainsail/assets/21010797/9b6eef3a-750b-4bd0-a8e6-6912b276f187)

**Comment by meteyou** [comment]
this is already fixed: https://github.com/mainsail-crew/mainsail/pull/1489
