### ISSUE TITLE
Choose image background color based on color of the thumbnail content

### ISSUE THREAD

**Issue by EmJay276** [mainsail-crew/mainsail#1507]
### Requested feature:

If I print something in black, and use the dark theme, it is really hard to see the object in the thumbnail.
Is it possible to choose the background color of this black based on the color of the picture?

If you point out to me where it could be (possibly) done in the code, I can have a look at it.

![grafik](https://github.com/mainsail-crew/mainsail/assets/8619525/476a0239-fbbe-44a7-875b-3a420b7bff0a)

**Comment by meteyou** [comment]
sry, but i would recommend to use a other color in your slicer or use a different background color in your slicer. mainsail just display the thumbnail as it is...

**Comment by EmJay276** [comment]
It is a PNG with a transparent background, that's why I think mainsail could easily handle this by adjusting the background color of the widget based on the image color.

**Comment by ja2ui0** [comment]
EmJay276 is correct, the slicer outputs a transparent PNG for the thumbnail and therefore the background will be whatever Mainsail chooses for it to be. It should select lighter or darker colors within a range depending on the lightness or darkness of the thumbnail, or at least allow the user to override the default color (or brightness at least, perhaps with a slider).

**Comment by EmJay276** [comment]
I figured out what needs to be changed

`<div class="v-image__image v-image__image--cover" style="background-image: url(&quot;http://voronika/server/files/gcodes/.thumbs/VC_sturdy_handles-400x400.png?timestamp=1693058858.16708&quot;); background-position: center center;"></div>`

needs an additional `background-color: #FFF;` (or whatever color)

Before
![grafik](https://github.com/mainsail-crew/mainsail/assets/8619525/783ebbd8-aff5-4f39-bc56-eca71ad6fab1)

After
![grafik](https://github.com/mainsail-crew/mainsail/assets/8619525/b544c6f2-189a-42ca-9904-298b2ca8c956)

**Comment by dw-0** [comment]
Don't use a full black for the color. I just tested it with dark colors and with an rgb value of (40,40,40) its imho still fine.
![image](https://github.com/mainsail-crew/mainsail/assets/31533186/014e81d1-1426-4492-8206-b1e60829b5dc)
hard to see, but with your black color you don't even get those natural shadows. so thats even an issue of the slicer itself, its just a flat black area you get there. imho it looks horrible even with a white or light background.

**Comment by ja2ui0** [comment]
I don't use full black for the color anyway, I use a dark grey in the slicer so it's more visible in the slicer itself. It's great that Cura allows me to change filament colors to improve the viewing experience. Like OP, I'd still recommend an option in the mainsail interface to make the thumbnail background more contrasted.

**Comment by meteyou** [comment]
@ja2ui0 i already implemented it -> https://github.com/mainsail-crew/mainsail/pull/1535
