### ISSUE TITLE
Automatically connect to first online printer

### ISSUE THREAD

**Issue by roobre** [mainsail-crew/mainsail#1508]
### Requested feature:

When configured to use the json-defined instance list, and even if there is only one instance on the list, mainsail still asks every page load to which printer I want to connect:

![image](https://github.com/mainsail-crew/mainsail/assets/969721/afd05b93-807a-42dc-b7d2-f7da7c3282da)

I think it would be great if we had a config option which, if enabled, told mainsail to automatically connect to a printer if available.

### Solves the following problem:

It would reduce the number of clicks I have to make in order to view, or intervene the printing process. This is particularly annoying in mobile, where it is common for browsers to kill inactive tabs.

**Comment by meteyou** [comment]
just don use the json DB. just add your ip and port above from it and use moonrakerDB. then it will connect to this printer.

**Comment by roobre** [comment]
Hey @meteyou , thanks for your suggestion! I'm trying to understand a bit better how this would work on my setup. Where is this moonrakerDB stored? Would that entry be saved if I access Mainsail from different devices, or would I need to configure the printer on each browser I access Mainsail from?

**Comment by meteyou** [comment]
@roobre only printers, which you added in the mainsail settings, will be stored in the Moonraker DB. The Moonraker DB is the Moonraker instance which you connect. And you change the config.json, which is the same file for every device.
