### ISSUE TITLE
Move by clicking on a position on a map

### ISSUE THREAD

**Issue by Riksu9000** [mainsail-crew/mainsail#1516]
### Requested feature:

Hi. I would like to share my idea for quickly moving the toolhead to often used locations. There could be a map that represents the printer coordinates, and clicking on a position will move the toolhead there directly. It should snap to the center, so you don't need  pinpoint accuracy. There could be more snapping areas in the sides and corners. If a map can't be done, nine buttons for sides, corners and the center would suffice for most cases. This could also be done with Z.

### Solves the following problem:

Moving the toolhead using the current methods is precise, but slow when precision doesn't matter. Usually I need to move the toolhead to the center, side or corner. This could be solved by adding macros, but having an interface specifically for this would be nice.

**Comment by meteyou** [comment]
I am closing this FR, because no other user liked or commented this FR until now.
