### ISSUE TITLE
Print Time Elapsed, let slicer clock go negative instead of blank

### ISSUE THREAD

**Issue by YesterdaysCoffee** [mainsail-crew/mainsail#1523]
### Requested feature:

On the printing tab, where Mainsail displays times: Estimate,  Slicer, Total and ETA.

Current Behavior: After "Slicer" counts down to zero and the print is still printing- the Slicer is blanked out.

Please change to let Slicer begin counting up with a '-' (negative sign) displayed.

### Solves the following problem:

Nope, no real problem.  Having the times the slicer underestimates will help adjust the slicer.

**Comment by meteyou** [comment]
i don't really see an advantage in this feature. i would advise you to simply compare the slicer time in the history with the real printing time, as this number also shows the final state. while the print is still running, the current display doesn't really have any added benefit if it is negative.
