### ISSUE TITLE
Temp Presets not Listed in Heater

### ISSUE THREAD

**Issue by TjardF** [mainsail-crew/mainsail#1525]
### Mainsail Version:

v2.5.1

### Browser:

Safari

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

I installed a generic Heater in Klipper and added the needed Values to my Temp-Presets.
If I call the Whole Preset everything works fine but if I just wanna Heat the generic Heater the Temps do not show up, like on the other Heaters.
Am I missing something or is this maybe a bug?
Is there already a fix in current version?
Thanks a lot

![image](https://github.com/mainsail-crew/mainsail/assets/37928929/b4309c24-334b-43cb-9758-a749a288b82c)
![image](https://github.com/mainsail-crew/mainsail/assets/37928929/c84d2e95-5869-4028-8c6d-249fccac8b46)
![image](https://github.com/mainsail-crew/mainsail/assets/37928929/9fd374e4-0027-4b73-85a1-a4fa6d76f7be)

### What did you expect to happen instead?

Show everything like expected

### How to reproduce this bug?

Add generic heater and add temps to some presets

**Comment by meteyou** [comment]
@TjardF please update Mainsail and test it again. This is already fixed. I just found some other bugs, which I have to fix.

- sort of the temps in the dropdown
- update function in the settings menu doesn't work as aspected

So pls let this issue open. I will close it when I fix the other issues.
