### ISSUE TITLE
WebRTC picture-in-picture support for mobile

### ISSUE THREAD

**Issue by AndyHazz** [mainsail-crew/mainsail#1528]
### Requested feature:

In a desktop browser you can right click the webrtc camera feed in mainsail and have the video displayed picture-in-picture, which is great!

On mobile, you can't right click to get that feature.

Viewing the raw video feed on mobile at /webcam/webrtc, the player there has a tiny menu that lets you open the video picture-in-picture and it works well (for me at least, on android), but it'd be great if there was a way to get that directly from the mainsail UI.

### Solves the following problem:

Unable to open video stream picture-in-picture on mobile from mainsail UI.

**Comment by meteyou** [comment]
i disabled the buttons on purpose, because there are problems with the current integration of the webcam with this mode when you change the page. this i would have to rebuild further to decapsulate the webcam, that the PIP webcam is still displayed.
