### ISSUE TITLE
Option to keep Z Thermal Adust units in mm, and not go to microns.

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#1540]
### Requested feature:

Please add an option to keep Z Thermal Adjust units in mm, and not go to microns. 

It would be nice to have a consistent scale for Z Thermal Adjust units. I think most people are accustomed to thinking in mm. And somehow it's annoying to have to remember what decimal place a micron is, and remind yourself what it means. 

Ohhh, please add this option.

### Solves the following problem:

I'm not that smart?

### Additional information:

Thank you!

**Comment by meteyou** [comment]
if more people come forward here who see it as a issue, then we will change it. currently there is no need / not enough interest to change it.

**Comment by meteyou** [comment]
I will close this FR, because there are no more inputs / new users for this...

**Comment by PhilBaz** [comment]
Ahh, shit... I should have been campaigning on discord. F!
