### ISSUE TITLE
Hide Power devices from Power menu with underscore in the name

### ISSUE THREAD

**Issue by nppc** [mainsail-crew/mainsail#1543]
### Requested feature:

If I add underscore (_) in front of the [power device](https://moonraker.readthedocs.io/en/latest/configuration/#power) name, then it will not appear in the drop-down menu under the power button at right top corner.

[Similar](https://docs.mainsail.xyz/overview/features/hide-macros-outputs-or-fans) is made for Macros already.

### Solves the following problem:

I have multiple devices connected to host on different pins. There is some prerequisites, when I can turn devices on or off, so they should not appear under Power menu. With physical button (also connected to the host pin) I change the state of host pins defined as power devices. This is done with on_press event of the button with machine.device_power.post_device power API.

### Additional information:

Maybe it could be done with virtual mcu on host, but it looks like overkill to run a virtual mcu to do this small job.

**Comment by meteyou** [comment]
Thx for your FR. I just forgot to add it to the power devices.
