### ISSUE TITLE
Unusable Confirmation popup on Emergenct Stop

### ISSUE THREAD

**Issue by pfgh1** [mainsail-crew/mainsail#1549]
### Mainsail Version:

2.7.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When clicking on emergency stop a popup window launches asking for confirmation. However the action (emergency stop/firmware shutdown,) immediately occurs with the popup serving no function.

### What did you expect to happen instead?

Either no prompt like in previous versions or have the prompt actually stall the operation until yes/no is clicked.

Really the best would probably be to add a configuration option to enable/disable the confirmation. Some people might find value in protection from accidentally clicking emergency stop whereas others might want emergency stop to be just that... immediate.

Thanks for the great work!

### How to reproduce this bug?

Click Emergency Stop during a print job.

**Comment by meteyou** [comment]
this is already fixed -> https://github.com/mainsail-crew/mainsail/pull/1526

**Comment by pfgh1** [comment]
Thanks but I am on 2.7.1 and still get the popup?

**Comment by meteyou** [comment]
Yes, because I fixed the issue after V2.7.1

**Comment by pfgh1** [comment]
d0h sorry. Thanks again for the awesome work on this project.
