### ISSUE TITLE
Add quotes to macro parameters

### ISSUE THREAD

**Issue by Godsgrav3** [mainsail-crew/mainsail#1550]
### Requested feature:

At the moment when you fill in parameters in the macro popup window it will not add quotes if it's text with spaces. This will lead to malformed commands. the workaround is adding manual quotes.

### Solves the following problem:

Malformed commands if the parameters has spaces in it.

**Comment by meteyou** [comment]
Thx for your request. I would call it more a "bug" than a feature. I changed this ticket to "bug".
