### ISSUE TITLE
Tool Colors

### ISSUE THREAD

**Issue by mochoandre** [mainsail-crew/mainsail#1552]
### Requested feature:

Some way in config so that diferent tools can have different colors to match filament color in MMU printers. Even better if it with be possible with a small overlay in the corner with material type like PLA, ABS...

### Solves the following problem:

Not easy to decorate where diferent color are at tools and you have to fisicaly check it or if you are remote it's impossible

**Comment by meteyou** [comment]
this is already implemented: https://github.com/mainsail-crew/mainsail/pull/1244

i don't think there is space for the filament type. if you have any idea and can provide a screendesign, pls upload it here.
