### ISSUE TITLE
Can't connect to Pi Cam Module V3 (Docker)

### ISSUE THREAD

**Issue by boehser-enkel** [mainsail-crew/mainsail#1555]
### Mainsail Version:

2.7.1

### Browser:

Other (Please tell us below)

### Device:

Other (Please tell us below)

### Operating System:

Linux

### What happened?

Running Klipper & Mainsail in Docker (prind)
I am not able to connect to a Pi Cam Module V3.
I tried to stream via libcamera directly and also some docker streamer images.
I am able to stream via vlc (rtsp) and browser directly
More about it here: https://github.com/mkuf/prind/issues/80#issuecomment-1717923386

### What did you expect to happen instead?

Camera stream

### How to reproduce this bug?

Install Klipper in Docker
Connect RPI Cam V3
Try to connect

**Comment by meteyou** [comment]
@boehser-enkel and I saw in your screenshots, that you use fluidd and not mainsail... so I think the right place would be to ask the fluidd-team...
