### ISSUE TITLE
Webcam Support - mediamtx - WHEP?

### ISSUE THREAD

**Issue by hostrup** [mainsail-crew/mainsail#1559]
### Requested feature:

Hi! 
I am trying to configure mainsail to use my unifi g3 intant cam. 
I was unable to use the rtsp or rtsps stream directly from unifi protect. 
so instead i choose to install mediamtx - as i saw mainsail supported that. 

Now mediamtx is wokring - and i have access to my unifi cams from my mediamtx server. 

i am however not able to use it inside mainsail. I keep getting errors - becuase it's trying to start a WS session. 
as far as i understand - from this link: 

https://github.com/bluenviron/mediamtx/discussions/1845

mediamtx - is not supporting websockets anymore - instead they suggest to use WHEP. 

I found this PR: 
https://github.com/mainsail-crew/mainsail/pull/1558

Can anyone tell me if this will actually solve the problem with never version of mediamtx - and provide the ability to use webrtc via WHEP inside mainsail?

**Comment by meteyou** [comment]
Yes. the PR #1558 is the WHEP implementation for this webcam clientl

**Comment by hostrup** [comment]
awesome! 
I will be ready to test it - onced it's released! 
Thanks alot :D 

br Ronni
