### ISSUE TITLE
After updating to v2.7.1 can no longer open height map workspace, and cannot edit the printer.cfg.

### ISSUE THREAD

**Issue by tomohulk** [mainsail-crew/mainsail#1581]
### Mainsail Version:

2.7.1

### Browser:

Safari

### Device:

Laptop

### Operating System:

macOS

### What happened?

after updating mainsail today, the printer.cfg no longer loads to edit, and clicking on the Heightmap page also does nothing.

### What did you expect to happen instead?

I would expect to edit the printer.cfg, and I would expect the height map page to load so I can calibrate and load meshes

### How to reproduce this bug?

go to the machine workspace, and attempt to edit the printer.cfg, a blank screen loads and you can't do anything.  if I `cat` the file over ssh, the content is there.

clicking on the Heightmap workspace does nothing, no page loads or anything.

**Comment by meteyou** [comment]
Pls clear your cache.
