### ISSUE TITLE
Add support for moonrakers at paths

### ISSUE THREAD

**Issue by Laikulo** [mainsail-crew/mainsail#1599]
### Requested feature:

Add support for moonraker instances served at paths other than /, either with moonraker's new `route_prefix` option, or with reverse proxy settings.

### Solves the following problem:

Allows connecting to multiple moonrakers served over the same port, allowing for a host running multiple printers to do so in a more elegant way.

**Comment by meteyou** [comment]
How should this work? You have to connect to Moonraker, to read the instances?

**Comment by meteyou** [comment]
This FR was fixed with the PR #1836
