### ISSUE TITLE
When moonraker is built with `--base`, it still tries to get config.json from /

### ISSUE THREAD

**Issue by Laikulo** [mainsail-crew/mainsail#1600]
### Mainsail Version:

g932a2c35

### Browser:

Firefox

### Device:

Laptop

### Operating System:

Windows

### What happened?

After building mainsail with --base=/mainsail/, and serving that at /mainsail/ on an httpd: When browsing to /mainsail/, mainsail tries to retrieve config.json from /

### What did you expect to happen instead?

Mainsail to retrieve config.json from /mainsail/

### How to reproduce this bug?

1. `npm ci`
2. `npm exec vite build --base=/mainsail/`
3. `cp base/* -r /srv/www/mainsail/`
4. `firefox localhost/mainsail/`

**Comment by meteyou** [comment]
Mainsail don't support the base attribute. But there is a PR which will add something like this.

**Comment by Laikulo** [comment]
Here's an example of a workaround with Caddy, that allows mainsail to work as normal:
```
@mainsail_config_bodge {
  path /config.json
  header Referer */mainsail/*
}
redir @mainsail_config_bodge /mainsail/config.json permanent
```
