### ISSUE TITLE
feat: Light control

### ISSUE THREAD

**Issue by stijnb1234** [mainsail-crew/mainsail#1601]
### Requested feature:

Add an official way to control one or more lights of the printer, even when the printer itself is not powered on.

Currently, it's possible to add a button under 'Others', but it's not that easy to use and is also not available when the printer itself is offline.

I would like my light to stay on while the printer is turned off so that I can see the finished print and turn off the light myself afterward.

**Comment by meteyou** [comment]
how should the light work when the printer is off?

Mainsail itself is only the web interface and it only communicate via API. so when your printer is OFF, there is no possibility to "control" anything.

**Comment by stijnb1234** [comment]
> how should the light work when the printer is off?
> 
> Mainsail itself is only the web interface and it only communicate via API. so when your printer is OFF, there is no possibility to "control" anything.

As long as the host is online, it's possible to control, for example, lights (with GPIO) connected to the host?

**Comment by meteyou** [comment]
Then you have to use the Moonraker power devices
