### ISSUE TITLE
Spoolman Integration for prints with filament change

### ISSUE THREAD

**Issue by borisb74** [mainsail-crew/mainsail#1617]
### Requested feature:

When slicing a print with filament change, Orcaslicer adds "PLA;PLA" as the filament type which is also evaluated by Mainsail. Obviously, in Spoolman there is no spool with this filament type and Mainsail does not allow to print the model. 

Thus, for being able to print the model I manually have to fix the gcode file. Instead, it would be great if I could skip the check and print anyways.

**Comment by meteyou** [comment]
this is only a warning, but you can start the print. i will try to parse the filament from the slicer and only check the first filament.
