### ISSUE TITLE
Can not add temperature presets, mainsail says the preset name is already in use.

### ISSUE THREAD

**Issue by pmead7399** [mainsail-crew/mainsail#1622]
### Mainsail Version:

2.8.0

### Browser:

Firefox

### Device:

Laptop

### Operating System:

Linux

### What happened?

I click on settings, then presets, then add preset. In preset name, as soon as I enter any character the box turns red with a dialog underneath that says Name already exists. I click cancel and the preset list shows the name that I just entered in the preset list. (I was unable to store the preset due to the store preset button being grayed out) when I exit the presets window by clicking cancel then I exit settings. I click on the presets dropdown menu on the top right side of the Temperatures window, it shows the text I entered in the name box in the create preset window that I was unable to save. If I had entered a temperature and select it, it starts the heating process. If I did not enter a temperature it just shows the name I entered and nothing happens. So then I go to add another preset and the original preset is gone and the last text entered in the preset name box now now in the presets dropdown. Effectively I can only enter one preset by entering the name and the temperature, then hitting cancel, it works but won't let me add any other presets and replaces the one that was just there with any new preset I try. If I click add preset and immediately cancel the presets dropdown now just shows the fire symbol with nothing next to it and does nothing. (Man I hope that was clear enough) 

This behavior does not follow along in chromium, which works fine I just really prefer firefox especially because chromium does not support WebGL in the Heightmap. and of course presets in chromium do not transfer to firefox. Firefox version is 115.3.1esr(32-bit) I am using a virtual installation of Raspian in VMware Workstation 17 to run my printer. due to lack of a raspberry pi. The reason I am reporting this as a "bug" is because I didn't see an option to just ask about it.

### What did you expect to happen instead?

I expected to just be able to add multiple presets

### How to reproduce this bug?

I don't know how to be more precise than my description

**Comment by sander344** [comment]
I have the same problem on a fresh install with raspberry py 4 and mainsail.
any solutions for this?
