### ISSUE TITLE
Mainsail won't load if not able to connect to spoolman

### ISSUE THREAD

**Issue by smwoodward** [mainsail-crew/mainsail#1633]
### Mainsail Version:

2.8

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

If the hosted computer that has spoolman running on it is offline, mainsail won't load

### What did you expect to happen instead?

For mainsail to load even if spoolman is not reachable

### How to reproduce this bug?

Configure moonraker/mainsail to connect to spoolman, and turn off spoolman and try to reload mainsail.  This was also while the printer was running.

**Comment by hawkeyexp** [comment]
Confirmed - had the same behaviour some days ago while spoolman was not started after a nas reboot

**Comment by smwoodward** [comment]
Good that it's not just me.

**Comment by meteyou** [comment]
Thx for the report. This is a known bug and i have to add some "workflow" for init plugins, which can fail (like this one).

**Comment by mlee12382** [comment]
I am also experiencing this bug. Glad that's all that's causing the issue. I was able to load Fluidd but Mainsail will get stuck on initializing when the Spoolman host is offline. I hadn't figured out the cause until I saw this issue and commented out the Spoolman section in moonraker.conf and Mainsail loads properly so issue cause confirmed.
