### ISSUE TITLE
Webcam preview in PiP mode not inheriting flipped settings from camera settings

### ISSUE THREAD

**Issue by F0erster** [mainsail-crew/mainsail#1642]
### Mainsail Version:

v2.8.0

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When horizontal and/or vertical orientation gets changed in webcam settings, the pip mode on the mainpage of mainsail still shows the original stream without those changes.

### What did you expect to happen instead?

PiP mode shows the correctly flipped stream.

### How to reproduce this bug?

Regardless of chosen webcam settings, the pip preview mode always shows original webcam state.

**Comment by meteyou** [comment]
There is no PiP mode in Mainsail. Maybe you use a browser own function. So it looks like a browser issue.
