### ISSUE TITLE
G-Code files favorites

### ISSUE THREAD

**Issue by HitLuca** [mainsail-crew/mainsail#1672]
### Requested feature:

It would be nice to have a way to keep favorite gcode files to be always available on a dedicated section, or have a way to filter the files list to only show favorite gcodes.
This feature comes handy when printing a lot of different things, but having to go back to a handful of files to reprint (online shop objects, replacement parts etc.)

**Comment by meteyou** [comment]
This is a duplicate of https://github.com/mainsail-crew/mainsail/issues/1623.

and for your second usecase, you can also use the job queue.
