### ISSUE TITLE
Fixed Fan Speed And Acceleration

### ISSUE THREAD

**Issue by ruredi87** [mainsail-crew/mainsail#1695]
### Requested feature:

Hi, first of all, thank you for this awesome project. Recently, I noticed that sometimes I forget to change the fan speed depending on my project. You know, slicers change fan speeds during printing. This means that if I set a custom fan speed in Mainsail, it would be used until a new fan speed command comes from the slicer.

Here's my idea: there could be a lock button or something in the Mainsail UI that will fix the fan speed or acceleration value throughout the entire print. It should overwrite the fan speed or acceleration commands from the G-code file until I disable.

**Comment by meteyou** [comment]
Thanks for your request, but this request already comes every month...

Mainsail is just a webinterface and can only display the current klipper state and send klipper commands. as long as klipper doesn't have this feature, as long we cannot implement it.
