### ISSUE TITLE
Updated to v2.9.0 zh_tw cannot be displayed

### ISSUE THREAD

**Issue by BrownRhined** [mainsail-crew/mainsail#1700]
### Mainsail Version:

v2.9.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I'm trying to understand if it's a translation file error
But I believe it is caused by a JavaScript error
I'm checking the problem
If you know the changes and the problem
Then please help correct it

### What did you expect to happen instead?

zh_tw cannot be displayed

### How to reproduce this bug?

switch language 繁體中文

**Comment by panglikesheep18** [comment]
I also found this bug and the issue with JS was a part of the culprit
<img width="645" alt="Culprit of the issue" src="https://github.com/mainsail-crew/mainsail/assets/94123276/ce5694cb-1cf6-4105-97f0-b2d1c78a4057"> 
but I found a workaround.
First, connect to your printer via SSH
then enter "sudo nano ~/mainsail/config.json"
Replace "en" in defaultLocate with "zh_TW" (case-sensitive) (like "defaultLocale": "zh_TW" but don't change anything besides this), it should look like this if you done this properly
<img width="237" alt="config.json with a workaround, defaultLocale: en is replaced with defaultLocale: zh_TW, on Mainsail 2.9.0" src="https://github.com/mainsail-crew/mainsail/assets/94123276/529197ca-fb1b-4515-823a-ca2b9de13a14">

Save it and reload cache in your browser.
and enjoy
