### ISSUE TITLE
Console error and unexpected hover graph behavior in 2.9.0

### ISSUE THREAD

**Issue by blonestar** [mainsail-crew/mainsail#1709]
### Mainsail Version:

2.9.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

On graph hover it throws console error and it does not show box with temperatures.
![image](https://github.com/mainsail-crew/mainsail/assets/5240133/65f4adb7-6d7e-428e-bb15-1706d27ced3a)

### What did you expect to happen instead?

It should show box with information's on graph hover.

### How to reproduce this bug?

Just update Mainsail to 2.9.0
2.8.0 works fine, I was downgrade it to check.

**Comment by blonestar** [comment]
I guess it is a duplicate of
https://github.com/mainsail-crew/mainsail/issues/1655

**Comment by meteyou** [comment]
Thx for posting this issue. This bug has nothing todo with #1655. This bug comes with the light mode PR: #1580 .

i Fixed this PR already here: #1706 . I hope i can merge it as soon as possible and release a bugfix release.
