### ISSUE TITLE
[duplicate] JS exception on mouseover temperature graph

### ISSUE THREAD

**Issue by mrThe** [mainsail-crew/mainsail#1717]
### Mainsail Version:

v2.9.0

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

Graphing does not show temperature on mouseover and rises an error instead:
```
Uncaught ReferenceError: $vuetify is not defined
    tooltipFormatter index-2d058d3f.js:28946
    _showTooltipContent echarts-9bc570b0.js:22
    _showAxisTooltip echarts-9bc570b0.js:22
    _showOrMove echarts-9bc570b0.js:22
    _showAxisTooltip echarts-9bc570b0.js:22
    _tryShow echarts-9bc570b0.js:22
    manuallyShowTip echarts-9bc570b0.js:22
    b echarts-9bc570b0.js:22
    co echarts-9bc570b0.js:22
    eachComponent echarts-9bc570b0.js:22
    co echarts-9bc570b0.js:22
    du echarts-9bc570b0.js:22
    A echarts-9bc570b0.js:14
    du echarts-9bc570b0.js:22
    dispatchAction echarts-9bc570b0.js:22
    KP echarts-9bc570b0.js:22
    e echarts-9bc570b0.js:22
    trigger echarts-9bc570b0.js:14
    dispatchToElement echarts-9bc570b0.js:14
    mousemove echarts-9bc570b0.js:14
    trigger echarts-9bc570b0.js:14
```
<img width="805" alt="image" src="https://github.com/mainsail-crew/mainsail/assets/1254163/01187033-7197-4b07-b981-c200f3783791">

### What did you expect to happen instead?

Tooltip with temperature should showup

### How to reproduce this bug?

Drag mouse across the graph

### Additional information:

Mainsail is installed using kiauh and updated a few times since. I don't know when exactly it starts to error, but it reproducible on any browser i have: desktop/mobile safari/chrome/firefox.

I assume i need to rebuild the assets, but i have no idea how.

**Comment by rackrick** [comment]
Thanks for reporting.
That's an known issue and already fixed https://github.com/mainsail-crew/mainsail/pull/1706

**Comment by mrThe** [comment]
@rackrick thanks for the update. Closing.

**Comment by meteyou** [comment]
I hope we can publish the Bugfix release on the next days. Thx for the report.
