### ISSUE TITLE
Docker image build on automated "tag" push not executed

### ISSUE THREAD

**Issue by chrisbraucker** [mainsail-crew/mainsail#1721]
### Mainsail Version:

2.5.0 - current

### Browser:

Other (Please tell us below)

### Device:

Other (Please tell us below)

### Operating System:

Other (Please tell us below)

### What happened?

As of now, when a git tag is pushed through an action, it does not trigger the action in `.github/workflows/publish_docker.yml`, so no version-tagged images are released.
From GitHub's side, this is expected, like https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow documents.

### What did you expect to happen instead?

For every release version there should be a matching docker image available.

### How to reproduce this bug?

As stated above, using the GITHUB_TOKEN when pushing tags does not start actions that trigger on tag push.

### Additional information:

I've yet to fix this in my fork and am not entirely sure where the Personal Access Token should be used.

**Comment by meteyou** [comment]
thx for your request. I'm right now checking the issue, the workflow itself, will be triggered, but there is an issue with the tags... i have to look at it deeper
