### ISSUE TITLE
G-Code tab suggestions ignore primary color setting

### ISSUE THREAD

**Issue by wlhlm** [mainsail-crew/mainsail#1730]
### Mainsail Version:

2.9.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

G-Code tab suggestions appear blue in terminal instead of red which is my primary color in the Mainsail UI settings.

![mainsail-tab-color](https://github.com/mainsail-crew/mainsail/assets/1928113/5cafb4a7-399f-484a-a9e4-d59535e81878)

### What did you expect to happen instead?

G-Codes suggested when hitting tab to complete the current command line should appear in primary color in the terminal.

### How to reproduce this bug?

Go to the G-Code console, type `SET_`, hit the _tab_ key, Mainsail then suggests a number of G-Codes with the `SET_` prefix for completion.

**Comment by meteyou** [comment]
Yes. This is hardcoded to blue and have nothing Todo with primary color.

**Comment by wlhlm** [comment]
I see. Though I don't understand why it would need to be hardcoded and ignore the UI color setting. The tab suggestions seem to work the same way as for example G-Codes put into the console through other means (such as pressing movement buttons), namely clicking on them puts them console input field.

My workaround for now is the following snippet in my theme CSS:
```css
/* See https://github.com/mainsail-crew/mainsail/issues/1730 */
a.command.blue--text {
    color: var(--v-anchor-base) !important;
}
```
