### ISSUE TITLE
Add camera authorization.

### ISSUE THREAD

**Issue by khseal** [mainsail-crew/mainsail#1735]
### Requested feature:

Many cameras require authorization.
Example http://admin:admin@192.168.5.100/image.jpg does not work.

**Comment by meteyou** [comment]
URL authentification should work with the most webcams. I will not implement something webcam specific.

**Comment by khseal** [comment]
It's not specific.
The link http://admin:admin@192.168.5.100/image.jpg opens in any browser.
mainsail cannot open. mainsail is specific and not a camera!

**Comment by meteyou** [comment]
This is just a URL for a Snapshot. It needs a little more to display it correctly in Mainsail, not "only a link" but I would not see any issue as to why this should not work with MJPEG-ADAPTIVE or UV4L-MJPEG mode in Mainsail.

But in UV4L-MJPEG, you will only see the last image. Not a video.

We already implemented ten different webcam services for a web interface built to control your Klipper printer. This is no "webcam control center". So please use a webcam we support, or feel free to make a fork and implement your specific webcam mode.

**Comment by khseal** [comment]
I have cameras with openipc firmware. https://openipc.org/
The telegram bot just works without any problems.
Mainsail fell off when authorization was added to the camera.

**Comment by khseal** [comment]
Hm, my bot can send video.
![image](https://github.com/mainsail-crew/mainsail/assets/11374629/c41b83fc-a052-45da-85eb-a36f47b692bb)

**Comment by meteyou** [comment]
@khseal, you send a screenshot from a video... Sorry. But all of this sounds more like a joke/scam... I will lock this post now because this is only a waste of time for me.
