### ISSUE TITLE
Second instance unable to use crowsnest or any other camera 

### ISSUE THREAD

**Issue by kg6ebj** [mainsail-crew/mainsail#1741]
### Mainsail Version:

V2.9.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When installing 2 printers, 1 host, and using web cameras, the first printer (printer_1_data) controls Crowsnest.
The second printer (printer_2_data) can add the cameras in the webcams settings, but all other references for webcams are not present and the webcam is not accessible to plugins like mainsail-timelapse or even to view in the dashboard.

### What did you expect to happen instead?

The cameras should be available in both instances. 

### How to reproduce this bug?

Clean install current mainsail
Install crowsnest
Add 2 instances of klipper/moonraker
Add at least 2 cameras
map the cameras in the printer session that is controlling crowsnest (works as expected)
map the cameras in the printer session that does not control crowsnest (shows preview in the Webcams control panel but is not usable anywhere else in mainsail.)

### Additional information:

This used to work; I can't remember when it stopped working because I had system issues and stopped running 3d prints for a bit.

I expect this is a function that print farms would need/require to run multiple cameras into 1 instance of Mainsail.

**Comment by meteyou** [comment]
Double checked it right now and work like it should.
