### ISSUE TITLE
Lagging after last update

### ISSUE THREAD

**Issue by DVSVIDEO** [mainsail-crew/mainsail#1753]
### Mainsail Version:

v2.9.1

### Browser:

Other (Please tell us below)

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Today I updated one with the automatic update, which updates all components.
After the update the clipper would not start because the firmware of the EBB 2209 CAN card was old for it.
I put new firmware on it (both on the sub board and on the rpi) (you can see it in the attached pictures)
After that it started, but the startup was slower than usual and there is a drastic slowdown during operation.
The webcam refreshes with 00-01 frames instead of the usual 18-22 frames and the system often loses connection and reconnects with "initialize".
I suspect that the connection is faulty because the systems load is low below 6%.
![Mainsail1](https://github.com/mainsail-crew/mainsail/assets/96373457/e950a029-405d-47c9-b30c-11c28fb23b5c)
![Mainsail2](https://github.com/mainsail-crew/mainsail/assets/96373457/87f18840-5158-48ab-a56e-62e6d502bbd0)

### What did you expect to happen instead?

I expect the old familiar speed of operation

### How to reproduce this bug?

I simply upgraded the raspberry system, then the CAN adapter (BTT 2209) needed a firmware update.

### Additional information:

My browser: Brave (chrome based)

**Comment by meteyou** [comment]
klipper updates have nothing todo with mainsail in this area... mainsail just communicate with moonraker.

**Comment by DVSVIDEO** [comment]
The mistake was mine. Rebooting my router fixed it. I apologize

**Comment by meteyou** [comment]
@DVSVIDEO thx for the feedback! happy printing!

**Comment by DVSVIDEO** [comment]
Thank you for your excellent work!
I really like Mainsail.
