### ISSUE TITLE
UI Light/Dark Showing Up Swapped on Mobile Site

### ISSUE THREAD

**Issue by Xelvaris** [mainsail-crew/mainsail#1762]
### Mainsail Version:

v2.9.1

### Browser:

Other (Please tell us below)

### Device:

Mobile device (Phone, Tablet or similar)

### Operating System:

iOS

### What happened?

When opening the site on my iPhone in Brave, I noticed the UI was in Light mode despite showing up in dark mode when on PC. The UI settings menu shows the theme to be dark mode however still shows up as light mode. Switching the setting to light mode makes it appear in dark mode on mobile but light mode on PC

### What did you expect to happen instead?

I expected it to be in dark mode matching the settings I have configured

### How to reproduce this bug?

Open mainsail on Brave, or Safari on the most recent version of IOS. The UI will be in the opposite mode compared to the setting you have configured.

**Comment by meteyou** [comment]
we double-checked it with safari without any issue, but one crew member found out, that the "nightmode" in brava just "invert" the colors. so the dark mode looks like light mode and the light mode like dark mode. pls doublecheck your browser settings...
