### ISSUE TITLE
Incorrect current layer when printing by object

### ISSUE THREAD

**Issue by tstone** [mainsail-crew/mainsail#1771]
### Mainsail Version:

2.9.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

When using OrcaSlicer's "by object" print order, instead of the traditional "by layer" Mainsail seems to do the following:

- Adds up all layers showing the sum of all object's layers
- When each object starts, it rests back to that layer based on the Z height

In the screenshot below, the print was at 99% on the last object.
![image](https://github.com/mainsail-crew/mainsail/assets/90279/5583c875-c795-426e-8706-237c489f4f8c)

### What did you expect to happen instead?

Show the cumulative count of prior layers printed + the current object's layer count.

### How to reproduce this bug?

Do a print with multiple objects using "by object" print order.

### Additional information:

I know Mainsail is just the UI, and recognize this could be a lower level component (Moonraker, Klipper, etc.). I'm starting the bug here but let me know if it's the next layer down.

**Comment by meteyou** [comment]
As you already wrote... Mainsail is just a GUI... Mainsail show per default a calculated layer count. So it calculate the layer with the gcode height and layer height from the gcode metadata. if you want more precise layer count, you have to use the Klipper gcode for layer count: https://docs.mainsail.xyz/overview/slicer/prusaslicer#layer-count

But i have no knowledge about this work with multiple object prints in the slicer... so this would be more a slicer question, than i klipper/moonraker/mainsail question then.
