### ISSUE TITLE
Typo in EN

### ISSUE THREAD

**Issue by ffolkes** [mainsail-crew/mainsail#1775]
### Mainsail Version:

2.9.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

I know this is trivial, but there's a typo in EN.json:

"DescriptionPreviouslyThrottled": "rPI ARM core(s) where throttled down at least once since last power-on."

### What did you expect to happen instead?

It should be "were" not "where".

### How to reproduce this bug?

N/A

**Comment by meteyou** [comment]
thx for the report! it's funny that no one has reported it until now. this text is actually very old.
