### ISSUE TITLE
Z-Offset during printing is saved wrong

### ISSUE THREAD

**Issue by mysugarape** [mainsail-crew/mainsail#1784]
### Mainsail Version:

v2.10.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

After you adjust/tune the Z-Offset during printing, and hit the save button you dont get the choice between Probe or endstop. If u do the same in fluidd u get the choice dialog. Had days of bad headache to tune my z ... after i used fluidd for the adjusting all went fine. I dont know if its a bug ... but it is confusing for users :)

### What did you expect to happen instead?

a dialog wich give the user the choice after saving ... to save it to ... probe ... or ... endstop ... like in fluidd

### How to reproduce this bug?

just adjust ur Z offset during printing and hit save ... do the same in fluidd ... and see the diffrents

### Additional information:

thanks for this great piece of software ... !!! thanks to all the developers and the community !

**Comment by meteyou** [comment]
this was a conscious decision to remove the option. if this dialog is needed, 99% of the time it is a false klipper configuration. pls feel free to join our discord server, open a support ticket and upload your config.
