### ISSUE TITLE
Editor - Devices - Can0 - Open Guide gives PNF error

### ISSUE THREAD

**Issue by HaernCalistinson** [mainsail-crew/mainsail#1786]
### Mainsail Version:

2.10.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

After updating and checking out the new devices option in the editor, on the Can0 tab (haven't tried others) I hit the Open Guide button which redirects me to https://docs.mainsail.xyz/overview/features/query-devices#can-devices

That link displays a PNF error

### What did you expect to happen instead?

The page to properly load

### How to reproduce this bug?

Open an editor, click devices at the top, on the Can0 tab click Open Guide

**Comment by meteyou** [comment]
thx for the report! we forgot to merge/publish the docs page. I published it now. so i can close this issue.
