### ISSUE TITLE
"Hide backup files" option does not hide `.moonraker.conf.bkp`

### ISSUE THREAD

**Issue by thetic** [mainsail-crew/mainsail#1794]
### Mainsail Version:

2.10.0

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

![image](https://github.com/mainsail-crew/mainsail/assets/1388052/0e0a375a-ed3d-4d57-9842-cd59b3b4589a)

### What did you expect to happen instead?

`.moonraker.conf.bkp` is hidden because it is a backup file.

### How to reproduce this bug?

From "Machine > Config Files" enable both "Hidden files" and "Hide backup files." `.moonraker.conf.bkp` remains in the list of files.

**Comment by meteyou** [comment]
Hide backup files are only for Klipper Backup files.

Which tool create this backup file? Because it started with a ., it will be also hidden, when you disable the hidden holes. All files with a . as first chars, are hidden files in Linux.

**Comment by thetic** [comment]
moonraker creates these https://github.com/Arksine/moonraker/blob/9813011db2e65f13072b8e31ad9a9364e99e338d/moonraker/confighelper.py#L509

**Comment by meteyou** [comment]
thx for the link and the FR. I will add these files to "hide backup files".
