### ISSUE TITLE
AVM Fritzdect Power Outlet

### ISSUE THREAD

**Issue by TMTYD** [mainsail-crew/mainsail#1796]
### Requested feature:

Support for the Fritz Dect sockets from Avm, where you can switch the printer on and off via the web interface.

### Solves the following problem:

As a former Octoprint user, there was a PSU-Control plugin and a Fritzbox plugin for PSU Control, where you could switch the printer on and off via the web interface, which was very practical. Unfortunately I'm missing something like this in mainsail or the integration of its plugin. It's easy to turn the printer on and off via the web interface.

### Additional information:

It concerns the switchable sockets from AVM Fritzdect

**Comment by meteyou** [comment]
This is a part of Moonraker, but you can control them via Mainsail: https://moonraker.readthedocs.io/en/latest/configuration/#power

(I don't know if your specific devices are supported)
