### ISSUE TITLE
FR: In-built spool manager

### ISSUE THREAD

**Issue by Miksu80** [mainsail-crew/mainsail#1805]
### Requested feature:

Add a simple spool manager that would allow you to do:
-add, remove and modify spools
-automatically consume spool when printing and tinkering
-add parameters and "position/ID number" to spools so they can be easily swapped/replaced/identified
-in main screen, you could choose the spool you're using (for example right click and select spool from list)
-manager could be in separate "module" for easier overview and modification of spools -same as "G-CODE FILES" for more info
-ability to inform that the print won't be able to finish with this spool if the spool doesn't have the required volume
-ability to pause the print x grams before spool end for spool replacement (some of us don't have runout sensors)
-ability for quick bypass (for example selecting spool 000 - No spool management)
-estimated time to spool change
-there could be an internal calculator for spool usages on current print so it could suggest which spools to use on current material for being able to print the whole print

possible main page views:

![image](https://github.com/mainsail-crew/mainsail/assets/48354615/01714ba9-d4db-4752-807b-5bc661998250)

![image](https://github.com/mainsail-crew/mainsail/assets/48354615/197731e3-2cfe-430a-a732-8471e0d37675)

### Solves the following problem:

Spool management and replacement, would enable spool changes for individuals without runout sensors.

**Comment by rackrick** [comment]
We already support spoolman: https://github.com/Donkie/Spoolman
since update [2.8](https://github.com/mainsail-crew/mainsail/releases/tag/v2.8.0) why should we ad another spool manager?

**Comment by Miksu80** [comment]
Havent checked spoolman integration yet, seems to require some thinkering to get it going.. Does it enable the spool change without runout sensor or time for spool change?

**Comment by rackrick** [comment]
you can either install the docker container or use the standalone version. the installation of both is pretty straightforward.
When starting a print over mainsail. you get a warning when the wrong material is selected or the remaining filamant is not enough. 
this wont replace your runout sensor if the spool runs out during a print.

**Comment by Miksu80** [comment]
Ok I'll need to check out the Spoolman. Would it be possible to implement the filament change procedure to Spoolman plugin?

**Comment by rackrick** [comment]
you can change the selected spool any time during a print and there a macros which can do this automated for you.
if you need further help with the setup. feel free to open a discussions post or join our discord. there is a spoolman channel with the maintainer present.
