### ISSUE TITLE
{power printer] naming bug, loses GUI button

### ISSUE THREAD

**Issue by basementbuilder17** [mainsail-crew/mainsail#1812]
### Mainsail Version:

V2.10.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When defining [power printer] in moonraker.conf, using a capital "P" (Printer) breaks the GUI functionality that tells you the printer is shut down and offers the power button. Instead, it just shows Moonraker as disconnected. 
![image](https://github.com/mainsail-crew/mainsail/assets/104473685/a3b07c7b-edce-414e-b318-72618121f2f5)
![image](https://github.com/mainsail-crew/mainsail/assets/104473685/ef6be41b-5ca4-4692-be6a-cbc5593a0b36)

### What did you expect to happen instead?

I would expect it not to be case sensitive, or to capitalize the first letter, to match the rest of the power toggle buttons in the menu.

### How to reproduce this bug?

moonraker.conf

[power printer] = OK
[power Printer] = Not OK

### Additional information:

Please remove case sensitive requirement or format GUI to show capital "P".

**Comment by meteyou** [comment]
Thx for the report!

just as a short hint, you can also select each power device for your printer in the Interface Settings > UI Settings.
