### ISSUE TITLE
Vivaldi download issue

### ISSUE THREAD

**Issue by Zeanon** [mainsail-crew/mainsail#1818]
### Mainsail Version:

v2.10.0

### Browser:

Other (Please tell us below)

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When I try to download a log, gcode, moonraker db json or any other file from mainsail with Vivaldi, a new tab opens(as expected) but it stays with about:blank in the url bar.
Downloading from mainsail using chrome works and downloading from any other website using Vivaldi also works, so I guess it's some sort of issue between mainsail and Vivaldi.

### What did you expect to happen instead?

Being able to download stuff from mainsail

### How to reproduce this bug?

Install the latest version of Vivaldi and try to download a gcode file from your printer

**Comment by meteyou** [comment]
Do you use my.mainsail.xyz?

**Comment by Zeanon** [comment]
no, just normal local ip
what I just realized, could it be cause some js stuff gets blocked by one of my extensions?(though it has worked for quite some time, the issue only arose about 2 weeks ago)
Console unfortunately gives no information at all

**Comment by meteyou** [comment]
if you use any "js blockers", then we cannot help you...

**Comment by Zeanon** [comment]
I have just checked, there are no js blockers active.
Whats strange is that it worked till about 2 weeks ago.
I even used a completely fresh install of vivaldi to check and it still does not work, so not an extension

**Comment by meteyou** [comment]
to be honest. Vivaldi itself has many "blockers". You have to doublecheck it with different browsers.

Mainsail itself just open a new tab with the http download link. so there is no "function" in Mainsail itself for the download. Its "just a link".

**Comment by Zeanon** [comment]
ok, fair enough
do you have any idea what to look for?

**Comment by meteyou** [comment]
at first, pls double check it with a "normal" browser...

**Comment by Zeanon** [comment]
I double checked with chrome and it works
All the chromium based settings are the same between my chrome and vivaldi (to rule them out)

**Comment by Zeanon** [comment]
Coming back to this:
After I restarted Vivaldi on my Laptop (without changing any settings or plugins at all) I now can not download files on vivaldi either so I guess it has something to do with a recent vivaldi update

**Comment by Zeanon** [comment]
do you by any chance have any idea on how it could be fixed?

**Comment by meteyou** [comment]
no sry and we also don't support browser with any blocking features, because every update could be break something. this is just annoying for developing.
