### ISSUE TITLE
Bed mesh preview in Dashboard

### ISSUE THREAD

**Issue by PedroC1999** [mainsail-crew/mainsail#1822]
### Requested feature:

The only reason I leave the dashboard during the start of the print is to check the quality of my bed mesh, if we could have another section that summarises/display it (maybe just a heatmap with the variance/highest/lowest/size and not 3D) to quickly sanity check the quality of the mesh and alert me to any issues. 

### Solves the following problem:

Having to switch between tabs/operate the side menu to find the quality of the bed mesh generated, and then having to return to the dashboard

**Comment by meteyou** [comment]
to be honest, i don't want to "spam up" the dashboard any more. if you need to check your mesh on every print, i think that's a hardware problem. even displaying the mesh won't fix your mesh.
