### ISSUE TITLE
sensor_type: temperature_combined messes up the web UI

### ISSUE THREAD

**Issue by RNGIllSkillz** [mainsail-crew/mainsail#1847]
### Mainsail Version:

v2.10.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When configuring temperature_fan with sensor_type: temperature_combined
the web interface will not show fan name also it will not change target temp the dashborw with an error: The value '' is not valid for TEMPERATURE_FAN

### What did you expect to happen instead?

Web interface should show fan name and it should change target temp.

### How to reproduce this bug?

Configure temperature_fan with sensor_type: temperature_combined, go to the dashboard. Name for that fan will be blank and you will not be able to change target temp for that fan.

**Comment by meteyou** [comment]
pls upload your klippy.log. this help us to reproduce this issue.

**Comment by meteyou** [comment]
I cannot reproduce this issue. I added a "Max_MCU" temperature_fan, but it works like it should:

![image](https://github.com/mainsail-crew/mainsail/assets/8167632/18e2a276-f1a8-4dcb-af1f-9e6fcd953716)
