### ISSUE TITLE
Overlay on video

### ISSUE THREAD

**Issue by ariekraakjr** [mainsail-crew/mainsail#1868]
### Is your feature request related to a problem? Please describe

For the alignment of my IDEX toolheads I mounted usb cam under the bed.
for easy alignment of the nozzles is want to use a transparent overlay on my video output.
![Schermafdruk van 2024-05-02 15-10-08](https://github.com/mainsail-crew/crowsnest/assets/36099467/54b9c496-b6b8-4415-ba3a-92c16b5560bd)

### Describe the solution you'd like

create options like:

```
overlay_image: /path/to/overlay.png
overlay_h_align: left|center|right
overlay_v_align: top|center|bottom 
```

### Describe alternatives you've considered

I now use an esp32cam with some own code to do the overlay.
It works, but i like it more integrated on the machine.(no second wifi device)

**Comment by mryel00** [comment]
Worth mentioning here is #1557

**Comment by ariekraakjr** [comment]
Thanks for the info.

**Comment by mryel00** [comment]
I moved the FR to the Mainsail Repo. So I'm gonna reopen it, to keep track of this issue.

**Comment by filamonkey** [comment]
I think this would be really useful for IDEX, dual nozzle and tool changers. My proposal would be a simple overlay with styling on the cameras dashboard view and be able to use the toolhead controls to align both nozzles and obtain the offset form their relative positions.
![Mainsail_Crosshair](https://github.com/user-attachments/assets/22e584aa-7dc7-4ae1-85ec-0a5fef0bcfff)
