### ISSUE TITLE
Issue with output_pin

### ISSUE THREAD

**Issue by Guilouz** [mainsail-crew/mainsail#1869]
### Mainsail Version:

2.11.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

Sliders on Web UI only set 0 or 1 when output_pin is used with scale.

### What did you expect to happen instead?

Slider set the correct value in range 0-255 and not 0 or 1.

### How to reproduce this bug?

I use this config:

```
[output_pin soc_fan]
pin: PB2
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0
```

When using slider to 100% this is the sending command: 

```
SET_PIN PIN=soc_fan VALUE=1.00
```

While it should send this command:

```
SET_PIN PIN=soc_fan VALUE=255
```

### Additional information:

On Fluidd it's working as expected.

**Comment by rackrick** [comment]
Hey @Guilouz ,
you're right... the output pin is currently fixed to a value of  `1`. We look further into it. There were some changes of the module at the begining of the year. Looks like we did not address all those changes.

Anyways... I move this to the issues. To put it on our ToDo List.
If you don't want to wait for a fix you could use `fan_generic` (Klipper Config Ref)[https://www.klipper3d.org/Config_Reference.html#fan_generic] to controll a fan the same way.
