### ISSUE TITLE
Excessive amount of DNS requests

### ISSUE THREAD

**Issue by manisto** [mainsail-crew/mainsail#1892]
### Mainsail Version:

v2.11.2

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

Mainsail is making an insane amount of DNS requests, around ~585 requests every ten minutes. I noticed because my pi-hole complained about reaching the maximum amount of current connections. In the attached image, you can see exactly when I turned on the printer last night just before 20:00 (8 PM). The red bars are the requests made by mainsail.
![mainsail-dns](https://github.com/mainsail-crew/mainsail/assets/188267/807c3485-d209-4e2d-897e-43fb53dba2f4)

### What did you expect to happen instead?

I expect mainsail to only make a reasonable amount of DNS requests.

### How to reproduce this bug?

Setup local DNS proxy or pihole and monitor the amount of DNS requests over time.

### Additional information:

I'm running Mainsail OS on as Raspberry Pi 4B 8GB.

**Comment by meteyou** [comment]
Mainsail itself is only a Webinterface and make no single DNS request...
