### ISSUE TITLE
[Feature Request] Cooling down sensor

### ISSUE THREAD

**Issue by poudenes** [mainsail-crew/mainsail#1897]
### Requested feature:

Would be nice to have a "Cooling down" sensor. When a print is done and extruder and bed are cooling down show this in a sensor. 

### Solves the following problem:

Maybe some people (also me) are using Home Assistant and have the "Moonraker" integration installed. I have created an automation when temperature is 5degrees higher then target a switch will turn off and the printer is off power. 

When print is done the target temperature set to 0 then the actual temperature is more then 5 degrees higher.
With a cooling down sensor you can use this as a condition

**Comment by meteyou** [comment]
Thx @poudenes for the FR, but Mainsail is only the webinterface, so the "Moonraker integration" cannot read anything from it. so you have to make this FR to Klipper itself.

but i think this should also work, when you exclude 0 as target in your HASS action. But i would also change to the Moonraker power module, that it will shutdown, when your printer has a thermal runaway for example.
