### ISSUE TITLE
Unreliable macro prompt opening

### ISSUE THREAD

**Issue by HelgeKeck** [mainsail-crew/mainsail#1899]
### Mainsail Version:

v2.11.2

### Browser:

Edge

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Macro prompts does not open always

### What did you expect to happen instead?

that the prompt opens every time i call it

### How to reproduce this bug?

jsut try to open a prompt multiple times

### Additional information:

Youttube video demonstration
https://www.youtube.com/watch?v=C0w-u5VQP-g

Macro that has been used for this test
```
[gcode_macro TEST2]
gcode:
	RESPOND TYPE=command MSG="action:prompt_begin Load Filament T0"
	RESPOND TYPE=command MSG="action:prompt_button PLA...............215°C|_START_LOAD_FILAMENT TEMP=215"
	RESPOND TYPE=command MSG="action:prompt_button PETG..............230°C|_START_LOAD_FILAMENT TEMP=230"
	RESPOND TYPE=command MSG="action:prompt_button ASA...............260°C|_START_LOAD_FILAMENT TEMP=260"
	RESPOND TYPE=command MSG="action:prompt_button ABS...............255°C|_START_LOAD_FILAMENT TEMP=255"
	RESPOND TYPE=command MSG="action:prompt_button PC................275°C|_START_LOAD_FILAMENT TEMP=275"
	RESPOND TYPE=command MSG="action:prompt_button FLEX..............240°C|_START_LOAD_FILAMENT TEMP=240"
	RESPOND TYPE=command MSG="action:prompt_show"
```

**Comment by HelgeKeck** [comment]
any comments on this one?

**Comment by meteyou** [comment]
@HelgeKeck, I haven't had time to test it yet, but I think it's just an interference of the console lines due to the fast clicking. Macro prompts are very slow, and it's more of a "console hack" instead of a real klipper function. I think you have to live with that.

**Comment by HelgeKeck** [comment]
> @HelgeKeck, I haven't had time to test it yet, but I think it's just an interference of the console lines due to the fast clicking. Macro prompts are very slow, and it's more of a "console hack" instead of a real klipper function. I think you have to live with that.

the console commands i used was jsut for reference. even when calling from normal macros or macro buttons it is unfortunately unreliable. so its not guaranteed that a modela will show or not

**Comment by HelgeKeck** [comment]
thank you
