### ISSUE TITLE
Camera FPS css issue

### ISSUE THREAD

**Issue by Jaizu** [mainsail-crew/mainsail#1900]
### Mainsail Version:

v2.11.2

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

FPS text is not readable

### What did you expect to happen instead?

Having readable text

### How to reproduce this bug?

Check the camera fps counter

### Additional information:

![image](https://github.com/mainsail-crew/mainsail/assets/18596778/5b839bd2-3d1e-43ec-9ede-b59ee425ef61)

**Comment by Jaizu** [comment]
solved on my computer with custom css but cant apply that on mobile
`@-moz-document url-prefix("http://192.168.0.17:4409/") {
    .webcamFpsOutput[data-v-72cc9e9c] {
        color: white;
    }
}`

**Comment by meteyou** [comment]
Thx for your bugreport! I created a PR to fix this issue, but i used a white background in the light theme, instead of changing the text color.

**Comment by Jaizu** [comment]
Whatever you think that fits better ^^
