### ISSUE TITLE
front end multi extruder support for spoolman

### ISSUE THREAD

**Issue by Marshalldog** [mainsail-crew/mainsail#1927]
### Requested feature:

multi extruder support for spoolman like: 
https://docs.fluidd.xyz/features/spoolman
![image](https://github.com/mainsail-crew/mainsail/assets/99470771/ea07e40b-f32e-42e9-9b03-9e6739554f15)

### Solves the following problem:

fluid already has a solution which allows for a toolchanger to be used with spoolman
![image](https://github.com/mainsail-crew/mainsail/assets/99470771/4c4c5432-4def-4e5b-b098-b290a7a892a6)

**Comment by meteyou** [comment]
These are only macros and you can use it already. You only don't see it in the gui...
