### ISSUE TITLE
Driver OTPW cannot be cleared or ignored

### ISSUE THREAD

**Issue by miklschmidt** [mainsail-crew/mainsail#1955]
### Mainsail Version:

2.12.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

A lot of buttons that do nothing. This seems unintentional. 

https://github.com/user-attachments/assets/aa1bc50c-e689-40c8-acd8-275cacc8ab90

It would be nice if they worked. Currently you cannot avoid this warning if you want to get the maximum out of a set of 2209 sticks for example, and as such this is just an annoyance and not very helpful.

### What did you expect to happen instead?

The notification to be dismissed / ignored, or worst case scenario that the buttons were disabled.

### How to reproduce this bug?

Either generate the OTPW flag on a driver, or just unconditionally push it to the notification list in the client code since it's a mainsail-only implementation.

**Comment by sbtoonz** [comment]
![image](https://github.com/user-attachments/assets/c98225aa-973c-4504-a70e-3feb3c075639)
appears to still be present in 2.12 release

**Comment by meteyou** [comment]
@sbtoonz pls post a video...

**Comment by meteyou** [comment]
@sbtoonz pls try a reload without cache (ctrl + shift + f5 on windows)

**Comment by sbtoonz** [comment]
force cache reload not yielding any different outcome

**Comment by meteyou** [comment]
ohhh... @sbtoonz pls check the PR for this bug itself. this one is not even merged yet (waiting for a review) and therefore not yet released!

**Comment by sbtoonz** [comment]
Ah I'll pull this down then :)

**Comment by meteyou** [comment]
You can download a build from the ci chain.
