### ISSUE TITLE
Option to show history chart/table as time or filament used instead of number of prints

### ISSUE THREAD

**Issue by Gunner087** [mainsail-crew/mainsail#1966]
### Requested feature:

It would be nice to have the ability to display the history chart/table below with print time or filament used instead of number of prints. I think the print time or filament used display options would be a more accurate representation of the different categories. For example, if you cancel a print on the first layer or before the print even starts because you forgot something, that print would contribute very little to the "cancelled" prints from a time perspective compared to a 12hr print that contributes to "completed". Obviously this is not something very important, but thought I would mention it since it would potentially be more accurate.

<img width="321" alt="Screenshot 2024-08-09 at 12 40 47 PM" src="https://github.com/user-attachments/assets/f01c5971-321e-4fbd-b518-c6461b1743dd">

### Additional information:

Most of my coding skills are self taught, but if someone can point me to the right areas of the code, I am willing to learn and try to implement this feature.

**Comment by meteyou** [comment]
Thank you very much for your feature request!

When I read your FR for the first time, I thought it would be useless and that just changing the ratio between "error" and "successful" would be different but would have no added value.

Then, I discussed this FR internally with the other crew members and gave it more thought. Now, I see great potential in it, especially when you do the filament-based calculation. How much filament was used successfully, and how much was "wasted". I just have to find a good position for the switch between count, filament, and time-based calculation.

**Comment by Gunner087** [comment]
Awesome! The successfully used vs. "wasted" filament information was one of the benefits I had in mind, but failed to specifically mention above. I was also thinking of the time calculation being useful in a similar way. How much time is wasted on cancelled prints vs. just knowing how many prints were cancelled.
