### ISSUE TITLE
BME280 hide hpa

### ISSUE THREAD

**Issue by mochoandre** [mainsail-crew/mainsail#1972]
### Requested feature:

hide hpa (atmosferique pressure?) when  using BME280 sensor (and others?)

### Solves the following problem:

It's not a sensor thats has meaning to 3D printing

### Additional information:

I Am not shure if this should be a mainsail or klipper issue but itt's where we can see it

**Comment by meteyou** [comment]
Just click on the sensor name and unselect pressure.
