### ISSUE TITLE
Hide macro parameter that start with "_" from the UI 

### ISSUE THREAD

**Issue by HelgeKeck** [mainsail-crew/mainsail#1980]
### Requested feature:

Similar to hiding fans and other objects from the UI that start with a underscore we would like to have a feature to hide macro parameters from the macro dropdown menu

**Comment by dw-0** [comment]
This is already possible.

![image](https://github.com/user-attachments/assets/c8ad2787-5d82-4dee-a898-d01fe167797e)
![image](https://github.com/user-attachments/assets/318805f1-2415-42e8-b4c8-eaf3b645b1ee)

**Comment by HelgeKeck** [comment]
ha, i must have missed it somehow, thank you. thats nice
