### ISSUE TITLE
Heightmap doesn't work.

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [mainsail-crew/mainsail#1993]
### Mainsail Version:

2.11.2

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

Heightmap should level the bed. I have done the probe calibration and now I did the Heightmap, it should print normally but for some reason the second time I'm trying to print it says that the bed is 0.8mm above the baseline.
Yesterday there was no such issue.

### What did you expect to happen instead?

If it knows that the bed is 0.8mm off then why not adjust it by that amount and print like it should?
Why do I need to again to the probe calibration after I did the heightmap calibration?
I thought the Probe Calibration was the distance between the nozzle and the probe to trigger, but if I don't do a probe calibration it will ALWAYS result with printing in air because height map does indeed go all the way down to the bed like it should but then when the print starts, it prints 1mm above the bed in air.

### How to reproduce this bug?

I don't know, for me it is a heightmap calibration and starting a print.

**Comment by meteyou** [comment]
@4e576rt8uh9ij9okp pls explain me, what a web interface can fix here?
