### ISSUE TITLE
Adding a new webcam gives a javascript error

### ISSUE THREAD

**Issue by Rodin10** [mainsail-crew/mainsail#2001]
### Mainsail Version:

2.12.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I'm trying to add a webcam to Mainsail via the settings. Everything is setup correctly, I enter the name and when I hit save the webcam isn't added and I get the error index-17a5ec1d.js:38 Response Error: Invalid value for parameter 'rotate' (no action) in my Chrome console.

### What did you expect to happen instead?

The webcam to be added and available

### How to reproduce this bug?

1. Go to settings
2. Go to webcams
3. Click add webcam
4. Fill out all details and the name
5. Click save webcam

### Additional information:

I'm using a Qidi Q1 Pro, Mainsail is installed on my Raspberry Pi 4
The Moonraker version I use is v0.9.3-0-g71f9e677

**Comment by meteyou** [comment]
which moonraker version do you use?

**Comment by Rodin10** [comment]
I use Moonraker v0.9.3-0-g71f9e677

**Comment by meteyou** [comment]
pls post also a screenshot from your webcam settings which you try to store

**Comment by Rodin10** [comment]
![image](https://github.com/user-attachments/assets/deef2b25-28d8-40c6-beb1-3ca08219f70e)

**Comment by meteyou** [comment]
i tested exactly the same without any issue. i only know this error with an outdated moonraker version, but your moonraker version looks up-to-date.

**Comment by meteyou** [comment]
is it possible, that you use an extra Pi with Mainsail & Moonraker and then connect to the Qidi pro? so you use the default Klipper & Moonraker on the Qidi pro?

**Comment by Rodin10** [comment]
Not quite sure what you mean unfortunately

**Comment by Rodin10** [comment]
I just noticed that when connecting to my Q1 Pro the Moonraker version changes...
How do I update that?

![image](https://github.com/user-attachments/assets/185e46da-5a1c-401a-922b-789b7cf0eb13)

**Comment by meteyou** [comment]
yes, i exactly mean this. if you join to another printer, you connect to Moonraker from this printer. so you only have Mainsail from your first connection.

the Moonraker version from Qidi is too old (you should also see a warning in the notification center [the bell in the topbar]). So please update Moonraker on your printer to fix this issue.

**Comment by Rodin10** [comment]
Thanks!
