### ISSUE TITLE
Height Map resets after saving the offsets.

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [mainsail-crew/mainsail#2015]
### Mainsail Version:

2.11.2

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Linux

### What happened?

I changed the Z-Offset and pressed "save" after the machine restarted the Height Map was gone.

### What did you expect to happen instead?

The Height Map to be persistent even if I shut down the machine or restart it.

### How to reproduce this bug?

1) Go to Height Map
2) Make a height map calibration
3) Change the Z-Offset and press Save
4) The printer should reset
5) Now the Height Map is gone and you need to calibrate it again.

### Additional information:

I'm very upset because of it, I spent way to much time on this nonsense before realizing that my Height Map was the issue as it was always deleted/gone after every restart and some adjustments that require restarts.

I'm also trying to recover my PEI Mat that was damaged by the missing Height Map after restart.

How this happen is I printed 2 parts (in one go) and after they were ready I noticed a baby elephants foot and adjusted the offset... then the whole Height Map went missing without me noticing and because the previous 4 prints were good... I just press Start and went on with my day.

We can argue that it's my fault but I'm not blaming anyone just asking nicely to make the Height Map persistent and not delete if after the printer restarts

**Comment by meteyou** [comment]
this is the normal Klipper behavior.
