### ISSUE TITLE
BLTouch failed to deploy

### ISSUE THREAD

**Issue by giovannihuizer** [mainsail-crew/mainsail#2037]
### Mainsail Version:

v2.12.0

### Browser:

Chrome

### Device:

Laptop

### Operating System:

Windows

### What happened?

i was doing my bed mesh and on the last point it stopped and said this: BLTouch failed to deploy. and it said also this: Failed to verify BLTouch probe is raised; retrying. 
![Schermafbeelding 2024-10-29 151055](https://github.com/user-attachments/assets/78e07c63-3283-41d3-8839-28767002340a)
![Schermafbeelding 2024-10-29 151234](https://github.com/user-attachments/assets/b7db7a08-e76b-46d3-9dd0-16aa3ac4bfc0)

### What did you expect to happen instead?

what is should have done is do an bed mesh

### How to reproduce this bug?

-

### Additional information:

-

**Comment by meteyou** [comment]
Mainsail is just a webinterface, which display the config files and the current Klipper state, but it has nothing todo with any hardware.
