### ISSUE TITLE
Camera-Streamer WebRTC not working

### ISSUE THREAD

**Issue by Zeanon** [mainsail-crew/mainsail#2068]
### Mainsail Version:

v2.13.0

### Browser:

Other (Please tell us below)

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I updated mainsail to the current version (v2.13.0) and my webcam didnt work anymore, instead I got a spammed console:
![image](https://github.com/user-attachments/assets/d16da595-1365-4001-a357-f32d2e519e4f)
tested on Vivaldi and Chrome

### What did you expect to happen instead?

Webcam showing my printer

### How to reproduce this bug?

use camera streamer webrtc

**Comment by Zeanon** [comment]
Why was it closed immediately?
Using an older version of the webrtc class makes the cam work perfectly fine, so the cam itself works (in fluidd it also works)

**Comment by meteyou** [comment]
@Zeanon i tested it and cannot reproduce any issue, so it looks like a setup issue. pls follow the description above.

why should i care here if it works in fluidd or not? this is the mainsail repo...

**Comment by Zeanon** [comment]
> @Zeanon i tested it and cannot reproduce any issue, so it looks like a setup issue. pls follow the description above.
> 
> why should i care here if it works in fluidd or not? this is the mainsail repo...

I know it's the mainsail repo, I just mentioned fluidd to clarify it's not a camera issue(I did it to verify it's a mainsail issue since I don't want to report a bug that is not mainsail related on mainsail obviously)

**Comment by meteyou** [comment]
@Zeanon its an outdated camera-streamer version... you would know it, when you would follow the description above...

**Comment by Zeanon** [comment]
> @Zeanon its an outdated camera-streamer version... you would know it, when you would follow the description above...

My crowsnest is up to date 
How should I know the camera streamer is outdated?
I tend to not touch the backends so I don't break anything

**Comment by meteyou** [comment]
crowsnest != camera-streamer...

i will block this issue  right now, because its no mainsail issue and help for something is on our discord server. thx for the report, but its not any topic for here...
