### ISSUE TITLE
Inserting code from PrintTimeGenius into Mainsail

### ISSUE THREAD

**Issue by Peuqui** [mainsail-crew/mainsail#2084]
### Requested feature:

Since I switched from OctoPrint to Mainsail, I missed the plugin "PrintTimeGenius" from [https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/309](url) heavily.
Unfortunately, I am not in the position to try an integration myself.
But the programmer of this really genius code piece is more than willing to help in that regard. He said, he didn't have a 3D-printer since years and won't do it himself, but wants to help anyone, who is willing to code.
This code would lift the print time estimation to another level!
Best regards,
Peuqui

**Comment by meteyou** [comment]
Thanks for your request, but something like that is "close to impossible" to implement in Mainsail (or at least it wouldnt make sense). There is a massive different between Mainsail and Octoprint. Octoprint is a "full Printserver" and Mainsail is just a Webinterface. Mainsail is only running in your browser. So every time you start a print or just refresh/reopen your browser tab, Mainsail have to download the gcode again to analyse it. So if you would print a 500mb gcode file, every time you open Mainsail, it has to download the complete 500mb gcode file, analyse it in your browser to show the "correct" time. Something like that will not make any sense.

It would make more sense to just fix your settings in your slicer. This will create some really good/close to estimate times, which will display in Mainsail.

Another good solution for Klipper printers is the tool [klipper_estimator](https://github.com/Annex-Engineering/klipper_estimator). It will connect to your printer and use the correct printer settings to calculate the right print time and write it in your gcode file. This is a postprocessing script for your slicer.
