### ISSUE TITLE
[FR] Display currently select Bed Mesh / HeightMap Profile on Dashboard

### ISSUE THREAD

**Issue by craiglink** [mainsail-crew/mainsail#293]
**Is your feature request related to a problem? Please describe.**
It would be nice to know what the selected profile (if any) is in used when viewing the dashboard screen without having to open the heightmap tab

**Describe the solution you'd like**
Display the name of the selected heightmap profile on the dashboard.  Perhaps in Controls or Misc

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by meteyou** [comment]
you can also use a M117 for display it in the status panel. would this work for you?

**Comment by zellneralex** [comment]
Maybe add it to the z-offset panel. Maybe in the header line since then it would be always visible.
