### ISSUE TITLE
[FR] Is a port of this GCode Viewer a possibility in mainsail?

### ISSUE THREAD

**Issue by afbenevides** [mainsail-crew/mainsail#315]
Would it be possible to include something similar to that GCode Viewer in mainsail?

https://github.com/Sindarius/DWC_GCodeViewer_Plugin

Any thoughts?

Thanks,

**Comment by meteyou** [comment]
I have already referred to this gcode viewer several times. I think it is very similar to the backend and therefore very "easy" to integrate / migrate into mainsail.
