### ISSUE TITLE
[FR] Web push notification for some event

### ISSUE THREAD

**Issue by PolestarWx** [mainsail-crew/mainsail#336]
**Describe the solution you'd like**
A web push notification with sound for some event like :
- Empty filament sensors
- Print finished
- Error

**Additional context**
With this enhancement we can act fastly when human action needed

**Comment by meteyou** [comment]
mainsail is just a web app. if you dont have your browser running and mainsail open, it dont exist. so push notifications have to be added in moonraker for example.

**Comment by montyx00** [comment]
I know this ticket is closed, but it would be nice to have feature to trigger the system notification from the browser on gcode events:
[MDN Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)

Such as M118 gcode commands we should create private notification events, such as after a very long bed pre-heating event (half an hour in case of an 8mm thick bed plate).

**Comment by meteyou** [comment]
webworkers only exists if you has HTTPS "apps". so this would be not possible for 99% of the users.
