### ISSUE TITLE
[FR] Spool Weight Tracker

### ISSUE THREAD

**Issue by Tahx** [mainsail-crew/mainsail#382]
**Is your feature request related to a problem? Please describe.**
When a spool comes to its end, it's a lottery to predict whether there will be enough filament or not to complete the next print. I often end up having spare spools not fully empty that takes space.

**Describe the solution you'd like**
I think it would deserves his own tab named "Spool Manager" since it can get heavily loaded pretty quickly.

The mandatory input:
- Manufacturer (it can be different than the vendor)
- Filament material
- Filament material density (important to calculate the weight used based on the amount of meters used)
- Filament name
- Filament weight
- Pick the color on a color wheel since the name doesn't always reflect the color.

Other optional input:
- Vendor
- Cost

It would automatically detect which spool is being used by reading comments inside the GCode (example):

`;manufacturer: namehere`
`;filament_material: ABS`
...

These comments should be manually added inside the custom gcode section of the slicer inside the right filament profile. Not all slicer may be able to do that thought, I only use SuperSlicer so far.

Once a print complete or is ended, the weight used is calculated and substracted from the remaining weight of the spool. The print history should add a few new columns such as filament weight used which I would find more meaningful than the amount of meters used.

**Describe alternatives you've considered**
None. I just don't track my spool anymore since I started using Klipper and Mainsail instead of Octoprint.

**Additional context**
I've particularly liked the Octoprint plugin "FilamentManager". Simple and straight to the point, however it was lacking the possibility to read the GCode and automatically detect which spool is being in use, so I had to manually select the spool every time which was bothersome.
I haven't tried the "SpoolManager" plugin that seems to be a different but maintained by the same person and probably more modern plugin.

**Comment by Tahx** [comment]
> Just thinking out loud here: How about a load cell rather than a calculated solution? I think you'd only need to configure an offset weight for the spool itself
> 
> There is a voron mod using a load cell for example https://github.com/VoronDesign/VoronUsers/tree/master/legacy_printers/printer_mods/Danowar/Load_Cell_Spool_Holder

This is a funny mod, I like the concept which can easily be implement inside a dry box. But the goal of this issue is more to have an actual library you can keep track off as spools gets swaped in and out of storage. Also I suppose the readout can be sent to Klipper and read within Mainsail? There seems to be only Octoprint support so far.

I'm really not aware of how things works between Klipper, Moonraker and Mainsail so I won't talk about what makes the most sense.

**Comment by lixxbox** [comment]
I have set the status to "blocked" till the feature is integrated into moonraker.

**Comment by th33xitus** [comment]
That approach does not work across clients, as they don't share their databases resp. database namespaces.
So lets say we implement something like this in Mainsail and the user adds some spools, those spools won't be available in other clients. Also their remaining filament would only be available in Mainsail and not synced across other clients. That's why a solution based on Moonraker should be preferred, as the data is then synced. Like the print history that is available to all clients as those data is stored by Moonraker itself.

**Comment by LazaroFilm** [comment]
That makes sense. I guess it's time to head over to Moonraker's repo.

**Comment by meteyou** [comment]
I will close this FR, because there is now a tool for tracking the filament. There is a separate FR to implement this in Mainsail: https://github.com/mainsail-crew/mainsail/issues/1446. So pls follow the FR 1446 for updates to this topic.
