### ISSUE TITLE
Percentage symbol in URLs is not escaped properly

### ISSUE THREAD

**Issue by boop5** [mainsail-crew/mainsail#390]
**Describe the bug:**\
A percentage sign (%) in the filename will disturb the thumbnail in the "G-CODE FILES" section. Thumbnails won't be shown as soon as there is a % in the filename. 

![image](https://user-images.githubusercontent.com/4655466/138268990-ccd1d543-67e0-4df2-af14-6d64ab5d4415.png)

The symbol is not escaped properly so the picture url is malformed. `%` will be placed as `%` in the url while it actually should be escaped as `%25`

![image](https://user-images.githubusercontent.com/4655466/138269228-c78abc55-86b6-4576-8088-17212f9cade3.png)

So instead of   

```/server/files/gcodes/.thumbs/TEST_UPLOAD%%-64x64.png```

 the url should be  
```/server/files/gcodes/.thumbs/TEST_UPLOAD%25%25-64x64.png```

**Expected behavior:**\
The thumbnail should be shown in front of the filename instead of the default fallback.

**Comment by steadyjaw** [comment]
thanks for the report!
will be fixed in the next beta
