### ISSUE TITLE
[FR] Export the console messages (commands + results) into a text file

### ISSUE THREAD

**Issue by nesdnuma** [mainsail-crew/mainsail#409]
Hello,

It would be nice to be able to export the text of the console, for instance when performing some commands with the help of some person who is remote.

Also, it would be nice if this text gathered the commands launched from several devices. So having this saving feature from the RPI side rather than from the client side would be even better (I often launch some commands from my computer and some from my phone).

**Comment by lixxbox** [comment]
Hello,
thank you for your suggestion. The second part would have to be implemented in moonraker first. Maybe you should create a FR there and link it here. Then we can have a closer look at it. 

I have set the status to "blocked" for the time being.

**Comment by nesdnuma** [comment]
Hello,

I have just made a FR on Moonraker dev: [https://github.com/Arksine/moonraker/issues/335](https://github.com/Arksine/moonraker/issues/335)

**Comment by meteyou** [comment]
We can reopen this FR, when this function is implemented in Moonraker.
