### ISSUE TITLE
Editor Syntax Highlighting Error

### ISSUE THREAD

**Issue by smackoz** [mainsail-crew/mainsail#416]
If I click on say the printer.cfg file and open it for editing and press [enter] on a blank line (or anywhere) in the document then offscreen text will be displayed as white text rather than syntax highlighted. If a press enter again when the unhighlighted text is visible on screen the text is syntax highlighted correctly as expected.

All text should be syntax highlighted irrespective of how many times [enter] is pressed on a blank line in the file being edited.

![2021 11 20--08 19 49--1194](https://user-images.githubusercontent.com/16916616/142699775-5d45a85b-6b7f-4033-a1ac-97fb073143e0.jpg)

![2021 11 20--08 20 05--1195](https://user-images.githubusercontent.com/16916616/142699872-1d76039a-edd1-48ea-9fc8-6ecf3855617e.jpg)

Have repeated this behaviour with Brave, Firefox and Dissenter web browsers.

**Logfiles:**\
n/a

**Comment by th33xitus** [comment]
Hi,
we are aware of that issue. Currently we don't exactly know what is triggering this issue but we are in the process of investigating and therefore resolving the issue.

**Comment by smackoz** [comment]
> Hi, we are aware of that issue. Currently we don't exactly know what is triggering this issue but we are in the process of investigating and therefore resolving the issue.

I remember seeing a comment about this being unique to chrome based web browsers and something to do with a bug in the way it displays data line-by-line (I think). Apparently until you changed the setting it didn't behave as expected. I have done a search through the Brave browser settings and so far can find no reference to the setting mentioned> This might help you to track down the issue. If what they say is correct then the issue is entirely with the browser rather than mainsail in any case.

**Comment by meteyou** [comment]
should be fixed with this PR #462
