### ISSUE TITLE
[FR] Warn user before closing the browser tab, when there are unsaved changes in the editor

### ISSUE THREAD

**Issue by julianschill** [mainsail-crew/mainsail#421]
**Is your feature request related to a problem? Please describe.**
When editing a file and closing the browser tab accidentally, it can be frustrating to loose all unsaved changes.

**Describe the solution you'd like**
There is a browser function that can ask the user if he really wants to close the tab, when there are unsaved changes. A possible solution is described here: https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

Note that the new versions of the browsers don't support custom messages, but I think the default one is fine.

**Comment by meteyou** [comment]
thx for the FR. looks good to me!
