### ISSUE TITLE
Editor Save GCode

### ISSUE THREAD

**Issue by ckvsoft** [mainsail-crew/mainsail#431]
![Screenshot_20211126_001240](https://user-images.githubusercontent.com/16374447/143506843-d0230b63-0c60-4f66-82eb-37cfd8def86e.png)
Version 2.1 Beta 1
If you edit a gcode file you cannot save it. There is only the X to close. Changed code is not adopted.

**Comment by meteyou** [comment]
fixed with this commit: https://github.com/mainsail-crew/mainsail/commit/fbead2efb1481cfadf7ef2aeec846c1fdfb4297e
