### ISSUE TITLE
Incorrect available space on memory card

### ISSUE THREAD

**Issue by ckvsoft** [mainsail-crew/mainsail#432]
Version 2.1.0 Beta1
If you are in a subdirectory, the free space is displayed incorrectly.

![Screenshot_20211126_000840](https://user-images.githubusercontent.com/16374447/143506768-3a1c9241-73ff-49ce-8ed9-f8c1d87eda2b.png)
![Screenshot_20211126_001035](https://user-images.githubusercontent.com/16374447/143506770-79a7d9a6-702e-41cc-aaf1-bd19bc4098b0.png)

**Comment by meteyou** [comment]
thx for the report. fixed with this commit: https://github.com/mainsail-crew/mainsail/commit/b6c2901908d861fdb8a6bda65913e29e87a2279d
