### ISSUE TITLE
Some macros do not report their parameters

### ISSUE THREAD

**Issue by RomRider** [mainsail-crew/mainsail#436]
**Describe the bug:**\
Some macros do not report requiring parameters in the interface
Eg:
```ini
[gcode_macro SET_BED_SOAK_TIME]
gcode:
  SAVE_VARIABLE VARIABLE=bed_soak_time VALUE={params.SECONDS|default(120)}
```

While some of them do:
```ini
[gcode_macro SET_INFILL_SQV]
gcode:
    {% set svv = printer.save_variables.variables %}
    {% set val = params.SQV|default(svv.infill_sqv|default(printer.configfile.settings.printer.square_corner_velocity, true), true) | int %}
    SAVE_VARIABLE VARIABLE=infill_sqv VALUE={val}
```

**Expected behavior:**\
The macro with parameters should report their parameters in the interface.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/21064206/143870326-c45b8b19-a71d-4880-8bec-efb192613f27.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log

**Comment by freasy** [comment]
See my comment on: https://github.com/mainsail-crew/mainsail/pull/437
