### ISSUE TITLE
Error running 'git pull'

### ISSUE THREAD

**Issue by Talha909** [mainsail-crew/mainsail#463]
I try to update moonraker from 
v0.7.1-225-g1ad83ce to -> v0.7.1-228. I got this error. 

Updating Application moonraker...
Application moonraker: Updating Repo...
error: object file .git/objects/f5/f87bf08c9d8bf1ca4c2b944dd5ea428724f699 is empty
error: object file .git/objects/f5/f87bf08c9d8bf1ca4c2b944dd5ea428724f699 is empty
fatal: loose object f5f87bf08c9d8bf1ca4c2b944dd5ea428724f699 (stored in .git/objects/f5/f87bf08c9d8bf1ca4c2b944dd5ea428724f699) is corrupt
fatal: the remote end hung up unexpectedly
Error updating moonraker
[klippy.log](https://github.com/mainsail-crew/mainsail/files/7684748/klippy.log)
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/7684749/moonraker.log)

**Comment by meteyou** [comment]
Mainsail just display the update. Moonraker execute it. Pls report it on the moonraker repo.
