### ISSUE TITLE
Documentation: minor error in mainsailOS first boot instructions

### ISSUE THREAD

**Issue by gareth8118** [mainsail-crew/mainsail#466]
**Describe the bug:**\

There are a couple of issues in [first-boot.md](https://github.com/mainsail-crew/mainsail/blob/39fd77d0659eebc8ddfb332adf695d556992b9ed/docs/setup-guide/mainsailos/first-boot.md)

> This can be achieved either by placing the contents of mainsail.cfg into your printer.cfg.

says 'either' then only provides one option.

> To do this, open the default printer.cfg in the Mainsail web GUI:

There's no default printer.cfg after my fresh install of 0.5.0; I assume I have to upload a starter printer.cfg before I can add the `[include mainsail.cfg]` line?

**Comment by lixxbox** [comment]
Hello @gareth8118,
thank you for the information! These issues should be fixed with #506.
We would appreciate any further suggestions.

I close the issue.
