### ISSUE TITLE
serial/by-id not returned with mainsail 0.5.0.

### ISSUE THREAD

**Issue by MadsGadeberg** [mainsail-crew/mainsail#470]
**Describe the bug:**\
Installing the "mainsailos-rpi-lite-**0.5.0**" makes me not able to achieve USB id on SKR mini E3 2.0
![image](https://user-images.githubusercontent.com/7197181/146008805-00681c30-1d1c-4711-bfe2-2394925292d4.png)

If i install the "mainsailos-rpi-lite-**0.4.0**" it works fine untill i update via the klipper interface. 
![image](https://user-images.githubusercontent.com/7197181/146008843-bbc4751d-c429-45ac-b1c0-6817887d4e61.png)

Then i am not able to connect to the MCU, i of course recompile and load the new Firmware, but still not able to connect to MCU. I did of check FIRMWARE.CUR is returned after load.
![image](https://user-images.githubusercontent.com/7197181/146008876-9e09d28b-7790-4d72-b251-ef3d3b98a491.png)

Full putty
![image](https://user-images.githubusercontent.com/7197181/146009248-f3fba639-54f8-475f-86f6-b254534ecf3a.png)

**Screenshots:**\
This screenshot shows the versions just after i updated klipper, moonraker and mainsail.
![image](https://user-images.githubusercontent.com/7197181/146008661-e2734847-6e97-43a3-aa55-581f28c7e16d.png)

[klippy.log](https://github.com/mainsail-crew/mainsail/files/7711970/klippy.log)
[moonraker (1).log](https://github.com/mainsail-crew/mainsail/files/7711971/moonraker.1.log)

**Comment by meteyou** [comment]
mainsail is just the web gui and have nothing todo with the OS. mainsailOS is a raspberry pi image with raspberry pi os lite and preinstalled klipper/moonraker/mainsail/mjepgstreamer. if you have issues with klipper and the newest raspberry pi os updates, pls post it in the klipper repo.
