### ISSUE TITLE
No Macros on dashboard on latest version

### ISSUE THREAD

**Issue by Guariboa** [mainsail-crew/mainsail#472]
For some reason i am unable to see any of my macros on the dashboard.
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/7716734/moonraker.log)
[klippy (6).log](https://github.com/mainsail-crew/mainsail/files/7716735/klippy.6.log)

**Comment by meteyou** [comment]
You don't have any macro for your dashboard in your config file.
