### ISSUE TITLE
escape key does not close modals

### ISSUE THREAD

**Issue by blalor** [mainsail-crew/mainsail#479]
**Describe the bug:**\
Pressing the escape key does not dismiss modals, such as the interface settings configuration screen.  The dialog "pulses" but does not close.

**Expected behavior:**\
The dialog should close.

**Screenshots:**\
https://user-images.githubusercontent.com/109915/146761991-05819546-f62f-4288-bb67-975974b4c622.mov

**Logfiles:**\
n/a

**Comment by steadyjaw** [comment]
Good day @blalor 
thanks for the report.
This is already fixed and will be available in the next release of Mainsail: #413

Mainsail v2.1 will be released soon. Stay tuned!

**Comment by steadyjaw** [comment]
I've closed this issue for now.
Feel free to re-open it, if something is not right in the next release.
