### ISSUE TITLE
G-Code Thumbnails don't get displayed/processed with % in the name

### ISSUE THREAD

**Issue by TheLion** [mainsail-crew/mainsail#480]
**Describe the bug:**\
G-Code Thumbnails don't get displayed/processed with % in the name

**Expected behavior:**\
I expected that the thumbnails would display ;-)

**Screenshots:**\
![image](https://user-images.githubusercontent.com/3755011/147350966-54b735f1-1e71-425e-b31e-01d445b18081.png)
The G-Code is exactly the same. Only the filename is different.

**Logfiles:**\
There is nothing in the klippy.log or moonraker.log that has to do with this issue.

**Comment by meteyou** [comment]
Already fixed and is included in the current beta.

**Comment by 9R** [comment]
This bug is fixed in the G-CODE FILES tab but seems to persists in the DASHBOARD print status view.

Tested with v2.1.0-rc1

![Screenshot from 2022-01-19 19-38-51](https://user-images.githubusercontent.com/381298/150193583-94898681-fa14-4dfc-9db5-b045891816c2.png)

**Comment by meteyou** [comment]
@9R fixed after RC1
