### ISSUE TITLE
[FR] Theme colors adjustable from gcode macro

### ISSUE THREAD

**Issue by bcbuckles** [mainsail-crew/mainsail#485]
It would be a cool feature if the new customizable theme colors for the web UI were able to be adjusted from GCODE macros.  
You could then change the favicon color based on the state of the print (I always have multiple tabs open and look at the progress indicator in the favicon, adding a color customization would be great.

One solution I can think of would be to make the theme colors mappable to a virtual neopixel object

**Comment by meteyou** [comment]
This is something to special for me. I would only support the general Klipper state and maybe add a new favicon for pause and error state, but not custumize able per gcode.
