### ISSUE TITLE
[FR] Add nozzle diameter column to GCODE Files Tab

### ISSUE THREAD

**Issue by bcbuckles** [mainsail-crew/mainsail#487]
It would be good if the GCODE Files Tab could parse the nozzle diameter from the gcode and display that as one of the informational columns.

If you change nozzles often, its good to know you're using a gcode file that was slices for your current nozzle size, so you know if you need to reslice

**Comment by lixxbox** [comment]
We added the nozzle diameter recently to Moonraker. 
It should show up in after an update of Moonraker & Mainsail 2.1 (still beta as of today), if your slicer is supported.

https://github.com/Arksine/moonraker/pull/322
