### ISSUE TITLE
Can‘t add Presets #beta6

### ISSUE THREAD

**Issue by Devil-of-Chaos** [mainsail-crew/mainsail#488]
**Describe the bug:**\
In Beta 6 the add Preset Button is not showing, so you can‘t add presets. The same on Desktop MacBook and latest Chrome Browser and on iOS 15 Safari

**Expected behavior:**\
There should be an Button :-)

**Screenshots:**\

**Logfiles:**\
It‘s UI only 
![62D4EC0F-AFAA-43C7-BE2E-5FBFA7AEC7BD](https://user-images.githubusercontent.com/1410820/147547128-695adf1b-b750-4085-8e82-c7ad5e0506a6.png)

**Comment by meteyou** [comment]
Pls reset your presets settings

**Comment by Devil-of-Chaos** [comment]
Thanks

**Comment by ccollinscj** [comment]
> Pls reset your presets settings

Ok how to you reset preset?
