### ISSUE TITLE
Temperatures no Table anymore #beta6

### ISSUE THREAD

**Issue by Devil-of-Chaos** [mainsail-crew/mainsail#489]
**Describe the bug:**\
In the Temperature Widget the Table off sensors to set Temperature are missing in Current Beta. 
iOS 15 Safari and MacBook latest Chrome Browser

**Expected behavior:**\
There should be the Table width Temperature settings

**Screenshots:**\
![69A21BB3-20C7-4AB5-8F31-589E6C58CE77](https://user-images.githubusercontent.com/1410820/147547375-6c2f2b4e-9823-478e-a61a-6a25101fe8f7.png)

**Comment by kiwiiikiwiiikiwiii** [comment]
It works for me. iOS 15.2, safari

![image](https://user-images.githubusercontent.com/52346725/147560292-098244eb-b94d-47a8-a1e3-b4ea78d4f9a3.jpeg)

**Comment by RyanDam** [comment]
Not shown up for me also

![Screen Shot 2021-12-28 at 21 15 18](https://user-images.githubusercontent.com/8265230/147575167-e7c87190-12cb-41f4-a10b-09b9a439ce6b.png)

**Comment by meteyou** [comment]
Plus reset your presets via interface settings > general > factory reset and check the presets checkbox

**Comment by RyanDam** [comment]
> Pls reset your presets via interface settings > general > factory reset and check the presets checkbox

This works for me

**Comment by Devil-of-Chaos** [comment]
Worked thank you maybe there should something in the update script for release
