### ISSUE TITLE
Inconsistent button tooltips

### ISSUE THREAD

**Issue by Riksu9000** [mainsail-crew/mainsail#490]
In version 2.1.0-beta6 I noticed this issue when hovering on the sidebar.

https://user-images.githubusercontent.com/37774658/147555751-370dabe8-5179-4afc-bde6-05c7c7c755a6.mp4

I then tested the other tooltips and found inconsistencies.

Most settings buttons don't have tooltips.
Console help and filter buttons don't have tooltips.
Heightmap buttons use system tooltips.
G-Code Files uses system tooltips and is missing settings tooltip.
G-Code Viewer is missing tooltips.
Print history buttons use system tooltips.
Collapse buttons don't have tooltips.
Top bar doesn't have tooltips.

EDIT: One more thing I noticed is that with the Config Files buttons you must hover over the icon. Hovering on the edge of the button doesn't show the tooltip.

**Comment by meteyou** [comment]
this was fixed here: https://github.com/mainsail-crew/mainsail/commit/a6c927508f3451f8fe39e3ae7c4a1e46042c9f0a
