### ISSUE TITLE
[FR] Decorators to hide macros from UI

### ISSUE THREAD

**Issue by bcbuckles** [mainsail-crew/mainsail#495]
Might be nice to add a decorator that can be placed on [gcode_macro] to prevent it from showing up in the macros button layout, and the visibility configuration menu entirely.  Would be a nice QOL improvement for when you add large macro sheets for automation and know that 90% of them should not be accessed by user.  Would save confusion when sorting through the list and manually turning them off, and would likely prevent mistakes when using .cfg files provided by others.

**Comment by meteyou** [comment]
Yep. Just use a _ as first char of the macro name.
