### ISSUE TITLE
[FR] Ability to reorder, reformat macro buttons on UI

### ISSUE THREAD

**Issue by bcbuckles** [mainsail-crew/mainsail#496]
It would be nice to be able to reorder macro buttons.  It would also be helpful to have a few options for layout.  One suggestion would be to allow the user to specify a grid size that the buttons can be layed out in (similar to QT).  For example the user could force the buttons to be in a 2 column grid, length calculated as needed.  Aesthetically, it would be nice to be able to force the buttons to be the same width as well, so we can layout a control panel in an organized fashion.  I'm sure there are infinite possibilities that could be added to handle UI customization, the grid appealed to me as a good balance of functionality and ease of implementation.

This may be already planned/suggested, but I didn't see it in the feature requests.

**Comment by meteyou** [comment]
Just use v2.1 beta and use the macro management...
