### ISSUE TITLE
[FR] neopixel support

### ISSUE THREAD

**Issue by meteyou** [mainsail-crew/mainsail#504]
display neopixel colors and use a color picker to change the color of this neopixel. maybe add a function to group numbers from one line of neopixels.

**Comment by psiberfunk** [comment]
Rudimentary inspiration might be drawn from the UX here.. but it is highly constrained by the screen software used on this printer:  https://github.com/CR6Community/Marlin/releases/tag/v2.0.8.1-cr6-community-release-6.1

**Comment by lbibass** [comment]
Any update on getting this feature developed?

**Comment by meteyou** [comment]
We build up test boards with all kinds of LEDs to test it. Could be possible a feature for v2.3.0. maybe we will make some PRs also to Klipper for better usebillity.

**Comment by arshillimbani123** [comment]
> We build up test boards with all kinds of LEDs to test it. Could be possible a feature for v2.3.0. maybe we will make some PRs also to Klipper for better usebillity.

any update in this
?

**Comment by meteyou** [comment]
@arshillimbani123 in progress... i linked the PR for this feature.
