### ISSUE TITLE
[FR] missing translation keys

### ISSUE THREAD

**Issue by srbjessen** [mainsail-crew/mainsail#510]
While going through the translations for Klipperscreen, and cross-referencing to make them similar, I stumbled across these minor parts missing from the translator files. (Or i can't find them)

All text on the "History-wheel" is not available for translations
![image](https://user-images.githubusercontent.com/92088582/148142163-0000c9d4-66d3-4ba6-933e-4b78d79a2ab8.png)

Estimation method selectors not available for translation
Filament and Slicer are the same, but "File" is supposed to be "Fil"
![image](https://user-images.githubusercontent.com/92088582/148142225-72ea6d17-2522-40be-8286-83b4ef1259e7.png)

"Root" which I'm not sure i see the need for is also nowhere to be found
![image](https://user-images.githubusercontent.com/92088582/148142904-594dc7ca-d8ba-44f3-a22d-4e4204155444.png)

**Comment by meteyou** [comment]
thx for your feedback. i think i will add all these options in v2.2. the "history-wheel" is a dynamic content... i have to check how i can create a good fallback option for this...
