### ISSUE TITLE
Mainsail will not connect to Moonraker following update

### ISSUE THREAD

**Issue by water-rhatt** [mainsail-crew/mainsail#521]
**Describe the bug:**\
Mainsail/Moonraker/Klipper working as expected prior to update. Following update, Mainsail cannot connect to Moonraker. "Connection Failed" Popup cannot be cleared.

**Expected behavior:**\
I expected Mainsail to continue working as before and connect to Moonraker/Klipper

**Screenshots:**\
![Screenshot_20220107_122516](https://user-images.githubusercontent.com/59306499/148602848-5e6e5460-495b-4196-9630-8b94e9a43a31.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.

[moonraker.log](https://github.com/mainsail-crew/mainsail/files/7831171/moonraker.log)
[klippy.log](https://github.com/mainsail-crew/mainsail/files/7831175/klippy.log)

**Comment by meteyou** [comment]
this is no mainsail issue... your moonraker service is not running:
```
2022-01-07 20:03:00,510 [moonraker.py:main()] - Server Shutdown
```

for support pls use our discord server
