### ISSUE TITLE
Printer settings not updating with "Enter"

### ISSUE THREAD

**Issue by srbjessen** [mainsail-crew/mainsail#525]
**Describe the bug:**\
The Printer settings on the dashboard, doesn't update values when entered and then confirming with "Enter"-key. Only using the arrows next to each field.
Max-speed, Sq-C-V, accel, and accel-decel all show this behaviour
but
Pressure-advance and Smooth time works with "Enter"

**Expected behavior:**\
It would be nice if they would update with "Enter", as it takes a long time to go from 3500accel, to 3000, if you can only move 1 at a time. 
As a workaround it's currently possible to enter 3001, and then use arrow-down, to send 3000 as a value.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/92088582/148644187-b4f01508-3cff-41da-966f-d9a9b49d5d63.png)

**Comment by th33xitus** [comment]
Hi, this issue is fixed with https://github.com/mainsail-crew/mainsail/commit/52ad699f924692b1d1c85d9c223a2d14e3f98864

Thanks for reporting!
