### ISSUE TITLE
Issuetext isnt clear enough

### ISSUE THREAD

**Issue by DrFailbucket** [mainsail-crew/mainsail#526]
It took me around 4h to figure out that it matters if you taype [ **I** nclude] or [ **i** nclude]

The warning about that wasnt clear at all bc, the issuetext it was all lower case so i couldnt notice it directly.

Edit: not really sure if this is related to Mainsail or Klipper

**Comment by meteyou** [comment]
pls post a screenshot of the error message to check where the error comes from... if the header is called "klipper error" it depends every time to klipper...

**Comment by zellneralex** [comment]
Ok I did a test, and sorry that is complete out of our control.
Error Message seen in Mainsail:
![IMG_2400](https://user-images.githubusercontent.com/37265689/150519684-5a2c82c3-f87c-4c72-a3cf-c72e02ec7c56.PNG)

Config section to generate the error:
![IMG_2401](https://user-images.githubusercontent.com/37265689/150519769-9cfdf82d-3d4c-4129-b7c5-14faad9618ab.PNG)

And last but not least the klippy.log:
![IMG_2402](https://user-images.githubusercontent.com/37265689/150519838-3754d8f4-874d-4f0b-8ccb-def47b7f8b16.PNG)

The message is generated within klipper and Mainsail only shows what klipper sends as error
