### ISSUE TITLE
[FR] Customizable Z-Offset values 

### ISSUE THREAD

**Issue by ngynkvn** [mainsail-crew/mainsail#532]
**Is your feature request related to a problem? Please describe.**
Adjusting z-offsets is a common procedure for 3D printers. However, the UI currently does not permit customizing the adjustment values in the Z-offset panel like Fluidd permits.

**Describe the solution you'd like**
A configuration option for setting user-defined adjustment values for the Z-offset panel.

**Describe alternatives you've considered**
N/A

**Additional context**
A view of the rough working implementation is shown below:
![image](https://user-images.githubusercontent.com/20323081/149214906-ad71397f-5d24-43d1-b594-4adb67251d08.png)
![image](https://user-images.githubusercontent.com/20323081/149217549-4acc4c74-781e-474b-9bcd-32f3d607ecae.png)

And development branch is available at https://github.com/ngynkvn/mainsail/tree/feat/zoffset-configurable

From a glance, some things I think need work before proper PR:
- Proper alignment of the UI button in the Z-offset panel.
- Some window sizes cause the buttons to overflow the Z-offset panel and should be fixed/avoided.
- Change in the overall layout if one shown is not preferable for some reason.
- i18n translations should be added.

**Comment by meteyou** [comment]
thx for the FR and your work! this is a feature we have a long time on our todo list, but no time to implement it. a PR would be very welcome! just ping us if you have something we should test.

you can just open your PR with a prefix [WIP] to have it visible for other users (and for my planning).
