### ISSUE TITLE
Emergency Stop button doesn’t appear when Klipper is started

### ISSUE THREAD

**Issue by lukasfink1** [mainsail-crew/mainsail#533]
**Describe the bug:**\
When Mainsail is accessed while Klipper is stopped, the “Emergency Stop” and the “Upload & Print” buttons won’t appear. When Klipper is then started, the page needs to be reloaded for these buttons to appear, while the rest of the UI updates automatically. They also won’t disappear when Klipper is stopped without reload.

The hostname printed next to the Mainsail logo in the top left corner is affected by this too.

**Expected behavior:**\
Those buttons and the hostname should either

- be shown always and independently of the state of the Klipper service or they should
- dynamically appear and disappear depending on the state of the Klipper service without reload.

**Screenshots:**\
Accessing Mainsail while Klipper is stopped:
![top bar with buttons and hostname hidden](https://user-images.githubusercontent.com/3033969/149223466-ba79e52b-c80e-4310-af0b-c73486def097.png)
After starting Klipper:
![top bar with buttons and hostname hidden](https://user-images.githubusercontent.com/3033969/149223466-ba79e52b-c80e-4310-af0b-c73486def097.png)
After reloading the Mainsail page:
![top bar with buttons and hostname shown](https://user-images.githubusercontent.com/3033969/149223689-a6197180-d565-4447-b5ca-624343924117.png)
After stopping Klipper:
![top bar with buttons and hostname shown](https://user-images.githubusercontent.com/3033969/149223689-a6197180-d565-4447-b5ca-624343924117.png)
After reloading the Mainsail page again:
![top bar with buttons and hostname hidden](https://user-images.githubusercontent.com/3033969/149223466-ba79e52b-c80e-4310-af0b-c73486def097.png)

**Logfiles:**\
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/7858333/moonraker.log)
[klippy.log](https://github.com/mainsail-crew/mainsail/files/7858350/klippy.log)
of the sequence outlined in the Screenshots sections

**Comment by steadyjaw** [comment]
Good day,
thanks for the report. I'll have a look on that.

**Comment by steadyjaw** [comment]
Fixed in commit:
https://github.com/mainsail-crew/mainsail/commit/674ad36ddb738f4e27b1aac03116f17730319ceb
