### ISSUE TITLE
[FR] Sending a macro with enter/return key after typing parameter

### ISSUE THREAD

**Issue by Dingushippo** [mainsail-crew/mainsail#541]
When you use the drop down menu on a macro to type in parameters, the enter key does nothing. 

It would be nice if we could send them using the enter/return key after we've typed them 

![unknown](https://user-images.githubusercontent.com/43849676/149954091-ee1c6fb1-af53-41bb-8235-12ca082b5a0c.png)

**Comment by meteyou** [comment]
feature is integrated in v2.1.0 and should work.
