### ISSUE TITLE
Bedmesh: rename does not delete the already registered mesh

### ISSUE THREAD

**Issue by zellneralex** [mainsail-crew/mainsail#546]
**Describe the bug:**\
If you rename a mesh in Mainsail you end up with the old and the renamed mesh after SAVE_CONFIG

**Expected behavior:**\
Only the renamed version of the mesh should be there after SAVE_CONFIG

**Screenshots:**\
not needed 

**Logfiles:**\
not needed

**Comment by steadyjaw** [comment]
Fixed by #547
