### ISSUE TITLE
Bedmesh: deleted meshes are not visible indicated in the UI 

### ISSUE THREAD

**Issue by zellneralex** [mainsail-crew/mainsail#548]
**Describe the bug:**\
If you delete a mesh in the UI there is no visible indication that it will be removed after the next save config and also that it is not usable anymore in the current klipper season 

**Expected behavior:**\
Any kind of visualization e.g cross out the name or a small trash can symbol next to the name.

**Screenshots:**\
As you can see only the SAVE_CONFIG shows that somethings changed but you do not see which mesh I deleted
![image](https://user-images.githubusercontent.com/37265689/150117773-1f17ad3e-b7d2-4721-85b5-e66470359a9d.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
not needed

**Comment by Misterke** [comment]
This is a consequence of MainSail showing the meshes from the config as currently bed_mesh.py is not offering a way to report the actual available profiles.  Feel free to get more attention for https://github.com/Klipper3d/klipper/pull/5222 as that would allow solving this problem.

**Comment by meteyou** [comment]
@Misterke thx for the info and the PR in klipper! with this PR, it would be very easy to fix this issue!

**Comment by Misterke** [comment]
> @Misterke thx for the info and the PR in klipper! with this PR, it would be very easy to fix this issue!

The PR has been merged, so Mainsail could now use the actual profiles instead of the static config.

**Comment by meteyou** [comment]
fixed with https://github.com/mainsail-crew/mainsail/pull/660
