### ISSUE TITLE
[FR] Bedmesh: Add a field for mesh name to the calibrate context menu

### ISSUE THREAD

**Issue by zellneralex** [mainsail-crew/mainsail#549]
**Is your feature request related to a problem? Please describe.**
As klipper supports defining a profil name at the execution of  BED_MESH_CALIBRATE PROFILE={mesh_name} It would be an improvement to add this also the calibrate context in Mainsail

**Describe the solution you'd like**
Add a Name field to the context menu and default it to default
![IMG_2373](https://user-images.githubusercontent.com/37265689/150121895-c4c72938-d6c7-41b4-b3c3-6a38f5f3dbbe.jpg)

**Comment by meteyou** [comment]
fixed #664
