### ISSUE TITLE
[docs] "Macro link" in the manual setup docs is broken

### ISSUE THREAD

**Issue by pedrolamas** [mainsail-crew/mainsail#556]
**Describe the bug:**\

The "Macro link" in the [manual setup docs](https://docs.mainsail.xyz/setup/manual-setup/mainsail#important-macros) is broken

**Expected behavior:**\
Link to work!

**Comment by lixxbox** [comment]
Hey Pedro, 
thanks for the hint!
https://github.com/mainsail-crew/mainsail/commit/a3ad590d4b40dae279b64c553a06d2984cb8c2b1 should fix it.

https://docs.mainsail.xyz/setup/manual-setup/mainsail
