### ISSUE TITLE
[FR] GCODE files on the main screen

### ISSUE THREAD

**Issue by Karol01pl** [mainsail-crew/mainsail#562]
Is it possible to add a preview of GCODE files on the main screen as it is in Fluidd? This makes it very easy to use.
![image](https://user-images.githubusercontent.com/71727804/150526632-81036673-c921-4731-82cd-e27036644e06.png)

**Comment by meteyou** [comment]
this is already on our todo list: https://github.com/mainsail-crew/mainsail/issues/184
