### ISSUE TITLE
[FR] Add Job Queue List to Dashboard

### ISSUE THREAD

**Issue by Rneil-ca** [mainsail-crew/mainsail#573]
Hi,

First of all thank you to all the developers that have contributed to this great interface.  

I have started using queueing regularly and find that I miss that the Queue list is not available on the main dashboard.  I think this would be a great addition.

Thanks,
Ryan

**Comment by meteyou** [comment]
thx for your request! i think in v2.2 this will be included. i have already started to include the job_queue in the status panel. it should be a combo with from last 5 gcodes and job_queue.

**Comment by Rneil-ca** [comment]
That would be great.  Thank you!
