### ISSUE TITLE
No thumbnail preview 

### ISSUE THREAD

**Issue by Aussie84d** [mainsail-crew/mainsail#574]
**Describe the bug:**\
No thumbnail preview on MainSail, large (400x300) or small (32x32) 

**Expected behavior:**\
Thumbnails to be visible on the GCode file selection and on the dashboard

**Screenshots:**\
![image](https://user-images.githubusercontent.com/35589893/150707047-5072a7c3-ee21-4fdb-8b55-649e76c52bba.png)
![image](https://user-images.githubusercontent.com/35589893/150706692-9c33b140-cea5-4c5e-845e-e87645f90160.png)
![image](https://user-images.githubusercontent.com/35589893/150707159-c576a128-78a4-4532-bf40-fb7c99223006.png)

**Logfiles:**\
[3DBenchy - 0.2mm, 10 (PLA).txt](https://github.com/mainsail-crew/mainsail/files/7921941/3DBenchy.-.0.2mm.10.PLA.txt)
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/7921945/moonraker.log)

**Comment by th33xitus** [comment]
Hi, we have to investigate that issue and track it down. 

But anyways, i pinned down the issue and its the `,` in the filename. Please remove it.
A general advice and sidenote: For best practices, keep special characters out of any filenames. Always 😄

**Comment by ngynkvn** [comment]
The issue might be related to usage of [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) rather than [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) in GET requests to moonraker.

**Comment by meteyou** [comment]
i think you will get problems with sub directories and `encodeURIComponent`

**Comment by meteyou** [comment]
ok. we found a solution for this issue. there was a small bug in moonraker. Arksine fixed it here: https://github.com/arksine/moonraker/commit/04477705b07f2fefd7666c7d3159d5e9ee17ee47
