### ISSUE TITLE
[FR] Include heater power output in heater graph

### ISSUE THREAD

**Issue by hapklaar** [mainsail-crew/mainsail#597]
I'm checking out several heater/thermistor combinations and would like to be able to see the amount of power delivered to the heater in the graph. Fluidd has this, but I recently switched to Mainsail and really miss this insight.

Please add the feature to Mainsail to include current heater power in the heater graph, next to set temperature and current temperature.

Alternative would be to go back to Fluidd, but that's not ideal.

**Comment by th33xitus** [comment]
Click on the heater name and check the checkbox you can see below:

![image](https://user-images.githubusercontent.com/31533186/151661786-3ea01d00-36a8-4529-8941-72307167f515.png)

**Comment by hapklaar** [comment]
Oh great, didn't know that option existed there. Thanks!
