### ISSUE TITLE
Cross control Z axis is reversed

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#607]
**Describe the bug:**\
The Cross control Z axis is reversed for printers like Voron Trident.

**Expected behavior:**\
Up arrow should raise bed and down arrow should lower bed.

**Screenshots:**\
<img width="150" alt="image" src="https://user-images.githubusercontent.com/1135694/152600873-9875b7d1-808f-49bf-aeb8-277690e3d579.png">

**Logfiles:**\
n/a

**Comment by rlaferla** [comment]
or if there is a reason for this (I can't think of one readily), make it configurable.

**Comment by th33xitus** [comment]
Those are not "Bed-Controls"... those are "Toolhead-Controls".

Arrow down brings the toolhead/nozzle-tip down inside of the printers coordinate system.
Arrow up brings the toolhead/nozzle-tip up inside of that coordinate system. And it doesn't matter if the bed is stationary or can move in z-direction. 

This is no bug and currently the intended behaviour.

**Comment by rlaferla** [comment]
Understood but on printers like the Voron Trident where the tool head is stationary (in the Z axis) but the bed moves in the Z axis, it is counterintuitive.  I'd like to see an option to toggle it.

**Comment by meteyou** [comment]
You can change the arrow direction in your interface settings. But the default direction is like the description from @th33xitus .

**Comment by th33xitus** [comment]
@rlaferla For some reason i thought, that inverting the controls is not possible yet for the cross controls. But as @meteyou said, you can already invert pretty much all axis in the settings. Im sorry for this kind of "misinformation".

You have to look for those toggle switches in the Control Settings. You can then invert any axis you like.
![image](https://user-images.githubusercontent.com/31533186/152634489-9fc91cd1-c017-478b-a9c1-c0ed5dc56c9c.png)

**Comment by rlaferla** [comment]
I hadn't seen the Invert Z setting.  I also understand that the control is intended for the direction of the nozzle and not the bed.  I guess it's really a matter of perspective/preference and I'm happy to see that the user is given options.
