### ISSUE TITLE
Webcam feed cuts out when print is started

### ISSUE THREAD

**Issue by alexhocks** [mainsail-crew/mainsail#608]
**Describe the bug:**\
Usually, the webcam feed works fine. However, almost always when I start a print (i.e. right click a G-CODE file and start the print), the feed disappears. It's gone everywhere, in the dashboard and the dedicated tab as well. To get it back, I have to reboot the Raspberry Pi or restart webcamd.

**Expected behavior:**\
The webcam feed is always still available when I start a print.

**Screenshots:**\
![grafik](https://user-images.githubusercontent.com/70474753/152599970-9742f4e5-0dee-48d9-ba01-76c2ef67dfcf.png)

**Logfiles:**\
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/8006131/moonraker.log)

**Additional information:**
- Webcam: https://www.welectron.com/Waveshare-15301-OV5648-5MP-USB-Camera-A

**Software Versions:**
- klipper: v0.10.0-250-g01431991
- moonraker: v0.7.1-348-g6749d38
- mainsail: v2.1.1
Initially installed via as Mainsail OS. All system packages are up to date as well.

**Comment by alexhocks** [comment]
side question: Why does Mainsail warn me that the print might fail when I restart webcamd while a print is running? Is webcamd in anyway relevant to the printing operation?

**Comment by lixxbox** [comment]
regarding your side question:
Afaik depending on the hardware it *could* lead to a cpu spike when the webcam daemon is loading. which *could* stop the print.

**Comment by meteyou** [comment]
which webcam mode do you use?

**Comment by alexhocks** [comment]
I'm using the MJPEG-Streamer (non adaptive), but right now I cannot reproduce the error. webcamd seems stable. I will monitor if this issue arises again and see whether I can provide more details under what circumstances it happens. Otherwise I'll close the issue.

**Comment by alexhocks** [comment]
Okay, I just started a print and the following happened:
Webcam feed was okay. Printer homed and started QGL. At some point during the QGL right after the probe triggered, the print head stops moving. That's when the webcam feed dies. QGL then continues normally and I can get my webcam feed back during printing by restarting webcamd.

**Comment by meteyou** [comment]
pls upload your logs!

is it possible, that you have a damaged hardware or a short circuit when the probe triggers and it pulls the 5V line to 0?

but i think this have nothing todo with mainsail itself.. pls ask on the discord for help.
