### ISSUE TITLE
[FR] Make TESTZ clickable in output for Z_ENDSTOP_CALIBRATE

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#622]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In other console commands, you can click the command in the output to have it inserted as a new command.  Please do this for TESTZ, ABORT and ACCEPT.

**Describe alternatives you've considered**
The Z_ENDSTOP_CALIBRATE should have a GUI for calibration rather than or in addition to manual commands.

**Additional context**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/1135694/153221198-c11654a2-305c-496a-9b46-ff4060d10228.png">

**Comment by lixxbox** [comment]
at a certain point we disabled parsing of console entries to increase performance, as it was very hungry. i don't know if this has changed.

**Comment by rlaferla** [comment]
It would be better to have an interactive UI for this anyways.

**Comment by meteyou** [comment]
A UI will be added for this feature #1071
