### ISSUE TITLE
[FR] Aborting commands like Z_TILT_ADJUST

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#623]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start a Z_TILT_ADJUST and realize that I needed to run other commands first or need to do other maintenance but can't abort the operation.  

**Describe the solution you'd like**
A button to stop/abort the current operation.  Perhaps this needs to be on a per command basis.  Some potential issues:    If commands are queued, is the queue aborted?  Is there a cleanup routine when aborted?  Can this be done in Mailsail or does it need underlying Klipper support??

**Describe alternatives you've considered**

**Additional context**

**Comment by meteyou** [comment]
pls make a FR to klipper. klipper only sort each command in a gcode queue and each gcode will be execute after the gcode before. there is only one posibillity to stop current commands -> emergency stop
