### ISSUE TITLE
Stopping a print often hangs

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#624]
**Describe the bug:**\
Stopping a print often hangs the UI.  The orange spinning wheel keeps spinning for over a minute. Love Mainsail but this is by far the most frustrating issue.  Perhaps, there is more to it with regards to Klipper, Moonraker or the MCU itself.

**Expected behavior:**\
Stop should stop within a few seconds.

**Screenshots:**\

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log

**Comment by meteyou** [comment]
if your printer is in heatup state, klipper dont execute new gcodes. only possibility is to use the e-stop. for help -> pls use our discord server.
