### ISSUE TITLE
Localization missing for firmware restart

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#625]
**Describe the bug:**\
Missing localized button title
**Expected behavior:**\
Correct localized button title

**Screenshots:**\
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1135694/153645466-d36e150a-8eac-4932-8a4a-bb3727ebf332.png">

![A86C2A6A-163F-4327-9E73-A70EB3F10F9B](https://user-images.githubusercontent.com/1135694/153712180-e7d0ebe0-f8eb-47c9-acc0-7fca69a01bd2.jpeg)

**Logfiles:**\
n/a

**Comment by th33xitus** [comment]
Which Mainsail version are you using?
