### ISSUE TITLE
Console does not filter out timelapse take frame messages when timelapse is disabled

### ISSUE THREAD

**Issue by MuddyPuddles4325** [mainsail-crew/mainsail#626]
**Describe the bug:**\
When the timelapse plugin is installed and the console is configured to filter out timelapse messages it does not seem to filter out the "Take Frame" message when the plugin is disabled

**Expected behavior:**\
"Timelapse: disabled, take frame ignored" message would not be shown in the console when the timelapse plugin is disabled

**Screenshots:**\
![image](https://user-images.githubusercontent.com/13035594/153715095-13dd0218-0f5b-46e9-8c5e-9675cffb4b47.png)

**Version:**\
Mainsail v2.1.1

**Comment by zellneralex** [comment]
There is a verbose switch in the settings. Setting it to false will omit these messages.

There are 2 types of messages. Mainsail filters setup messages with the Console filter. For macro outputs there is the verbose setting in the setting. 

The reason for that is simple we are sure that there is nearly no need to get the setup messages shown, but you might be interested in the macro output while debug.

**Comment by th33xitus** [comment]
Closed due to inactivity.
