### ISSUE TITLE
gcode viewer bug

### ISSUE THREAD

**Issue by XEL-Maker** [mainsail-crew/mainsail#636]
**Describe the bug:**\
The results of the g-code preview and the results of the preview in the slicer display different screens.

**Expected behavior:**\
I applied sequential printing options to print two different objects and proceeded with slicing, and as a result of checking them through preview, the g-code viewer showed me like simultaneous printing.

**Screenshots:**\
![mainVsSuper](https://user-images.githubusercontent.com/52307315/153862440-1d2a883b-1941-4bfc-8ae4-08e7111b2b26.jpg)
![mainVsCura](https://user-images.githubusercontent.com/52307315/153862447-e5869796-3824-4076-bfc8-fd06f45a3606.jpg)

**Logfiles:**\
I added my g-code files
[sequential test.zip](https://github.com/mainsail-crew/mainsail/files/8060610/sequential.test.zip)

**Comment by Sindarius** [comment]
The bar on the right of the G-Code Viewer is simply a z height slider not a time slider.  When the file is simulated (coming soon to Mainsail) the file renders sequentially. You can validate the functionality at http://sindarius.com   this is what will be implemented in the near future. 

From your file you can see that the first part is complete and the second one is printing.

![image](https://user-images.githubusercontent.com/12520045/153872438-e28cc217-3f7b-448c-80e4-70847980e533.png)

**Comment by XEL-Maker** [comment]
I thought it was time, but I first knew it wasn't.
Thank you.
