### ISSUE TITLE
MJPEG-Streamer (non-adaptive) not working in Safari on macOS/iOS

### ISSUE THREAD

**Issue by JRHeaton** [mainsail-crew/mainsail#644]
**Describe the bug:**\
When selecting the "MJPEG-Streamer" service option for my webcam, it shows a blank webcam view showing "0 FPS" in Safari on macOS and iOS, while it works on Firefox. The experimental adaptive streamer _does_ work in Safari.

**Expected behavior:**\
I would expect that the non-adaptive, "stable" streamer service would be functional in all browsers. This seems to be a regression from past versions of Mainsail. It does work as such in Firefox.

**Screenshots:**\
<img width="1436" alt="Screen Shot 2022-02-15 at 6 38 18 PM" src="https://user-images.githubusercontent.com/159331/154168300-d52e5431-3520-4680-8e2d-61628bf3c8f4.png">
<img width="1436" alt="Screen Shot 2022-02-15 at 6 38 15 PM" src="https://user-images.githubusercontent.com/159331/154168304-938f48f7-2dce-4ff0-babc-8c6a3971feca.png">

**Logfiles:**\
[klippy-3.log](https://github.com/mainsail-crew/mainsail/files/8075450/klippy-3.log)
[moonraker-3.log](https://github.com/mainsail-crew/mainsail/files/8075452/moonraker-3.log)

**Comment by JRHeaton** [comment]
Any acknowledgment of this issue from the dev team? Seems like a pretty glaring issue for webcam users.

**Comment by JuicedEagle** [comment]
I can relate to that. 

mjpeg-stream is not working from iOS on iPhone, wether using Safari, Firefox, Chrome or Edge. 

on Fluidd mjpeg-stream is working without any problems, as well on Octoprint it worked with the normal mjpeg-stream.

**Comment by meteyou** [comment]
only because it has the same name, it doesn't mean, that the background is the same. I will not support this mode for ios/safari browsers, because it don't support all JS functions for this mode and other modes also work on ios.

**Comment by meteyou** [comment]
today I had time to read up on the problem again and tried various fixes, but unfortunately without success.

it looks like it's a bug in safari itself and it needs to be fixed first: https://bugs.webkit.org/show_bug.cgi?id=215771

**Comment by jalanjarosz** [comment]
I'm using "Adaptive MJPEG Streamer (experimental)" on iOS without issues:
![image](https://user-images.githubusercontent.com/40894871/168267949-fafe3d28-8e18-4005-8d58-06229f4c37a7.png)

You can also try "UV4L-MJPEG". This shows and image, but I have not tried it. 
![image](https://user-images.githubusercontent.com/40894871/168268145-4c2f3c8e-073f-4582-8cf3-68af1cdfa1dd.png)

Screen shots are from v2.2-beta1, but I have been using on v2.1.2 as well. 

Cheers
-James

**Comment by meteyou** [comment]
In v2.2.0-beta2, we fixed some issues in UV4L mode. This should work also fine now.

**Comment by meteyou** [comment]
I'm closing this issue, because safari doesn't seem to fix this problem. furthermore there are enough other streamers that also run with safari and we want to expand the WebRTC support and leave MJPEG behind us.
