### ISSUE TITLE
Keyboard does not show up on temp on iPad when Mainsail is accessed through the home screen

### ISSUE THREAD

**Issue by alexvonsiebenthal** [mainsail-crew/mainsail#649]
**Describe the bug:**\
I have added Mainsail to my iPad's Home Screen for easy access. This strips many controls i.e. refresh button. The unexpected behaviour lies in the missing keyboard when wanting to change the temperature during a print. When I click on the field with the extruder temp, the number gets selected and the dropdown is shown. However, I am not presented with a keyboard, hence unable to type in a different temperature. 

**Expected behavior:**\
When clicking on the temperature field, I want to be able to select and change the current temperature. The keyboard is expected to show up.

**Screenshots:**\
Can provide if necessary.

**Logfiles:**\
n/a

**Comment by th33xitus** [comment]
We reworked the temperature panel, especially the inputs with the release of Mainsail v2.2.0.
Please update to the new version. Does the issue still persist?
