### ISSUE TITLE
[FR] Create separate sections for Fans and Lights as well as segmented controls

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#656]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**

I'd like to see all Fans and all Lights in their own sections instead of under Miscellaneous.

Also optional segmented controls for the value:

[OFF][25%][50%][75%][100%]

It's unlikely that users are using odd ball values like 47%, etc...  These presets could be in Settings for customization.  Perhaps a +/- button to adjust it from the preset.

**Describe alternatives you've considered**
n/a

**Additional context**
<img width="434" alt="image" src="https://user-images.githubusercontent.com/1135694/154726449-fadd1b5f-ed95-4990-a615-dcddaaa02a3c.png">

**Comment by meteyou** [comment]
since no other users have responded to this topic so far, I see little interest in this feature. perhaps it will become interesting in the future. for now, I am closing this ticket.
