### ISSUE TITLE
[FR] Section macros

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#657]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'd like to see macros associated with a section.  For example, I may have a PREHEAT BED macro.  I'd like to see that in the Temperature section instead of mixed in with a bunch of non-related macros.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by th33xitus** [comment]
This won't be possible with the current way the panels of the dashboard are structured and work.
For one, you can use the advanced macro management in case you have more temperature related macros and want to group them in logical groups.

But if your usecase would mainly be in regards to the temperature panel in terms of preheat commands, i suggest you just use preheat presets which are exactly made for that. As you can see, you can even execute G-Code (that also means macros) with that.
![image](https://user-images.githubusercontent.com/31533186/154822368-764bc0e0-13e6-425a-9d9d-42682d62d423.png)
![image](https://user-images.githubusercontent.com/31533186/154822428-5e9bc91a-760b-4df2-9a8f-fd1e01b58856.png)
