### ISSUE TITLE
[FR] Z offset UI

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#659]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
It would be useful to see a visualization of the Z offset.  Especially for novices but it also has a wow factor.

**Describe alternatives you've considered**
n/a

**Additional context**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/1135694/154744063-f94dea35-e8cd-4ff7-a554-1548dc70d271.png">
<img width="177" alt="image" src="https://user-images.githubusercontent.com/1135694/154744156-7a0e0663-0716-4986-afd0-7c1c6fd02051.png">

**Comment by th33xitus** [comment]
We have a "rework" of the Z-Offset-Panel on our todo list. But i don't think we will add any kind of visualization though. Something like on the second screenshot just takes up too much space. **_Maybe_** we can include some hints or some kind of mnemonics. But generally the arrows which are already in place should be enough...
