### ISSUE TITLE
Host Load graph appears to be off by 10x

### ISSUE THREAD

**Issue by jalanjarosz** [mainsail-crew/mainsail#673]
**Describe the bug:**\
Machine Settings Tab, under System Loads, the HOST controller pi graph seems to be off by a 10x factor.   

Assuming that "Load" value is 1=100% and any fraction is an equal percentage (like MCU Load), then the pi graph is off.

In the attached image, my SBC Load is about 15%, when I SSH to the SBC, I'm presented with 11% (it's grabs values at login only), the pi graph should be 15, not 2, as in the image.

**Expected behavior:**\
Pi graph should be 15 to match load value of 0.15, not 2

**Screenshots:**\
![image](https://user-images.githubusercontent.com/40894871/155325311-9e2d91b7-edf8-4871-a4ea-658e693d4cc6.png)

**Logfiles:**\
- klippy.log
[klippy(1).log](https://github.com/mainsail-crew/mainsail/files/8124495/klippy.1.log)

- moonraker.log
[moonraker.log](https://github.com/mainsail-crew/mainsail/files/8124497/moonraker.log)

**Comment by pataar** [comment]
It's correct. Just try to run `htop`, `top` or `uptime`. They will all show the load in a 0..1 way.

Example:
![image](https://user-images.githubusercontent.com/3403851/155326544-2fb40a56-ee13-44ee-a281-77c4c7bd432e.png)
 
Mainsail basically rounds it and multiplies it to get a percentage.

**Comment by meteyou** [comment]
and it depends on your cpu. if you have a 4 core cpu, load 4.0 => 100%

**Comment by jalanjarosz** [comment]
Yes, the load values match between the text in Mainsail and htop, both are 17%, that is if 1.00 = 100%.  However the pi chart in Mainsail only shows 2%

![image](https://user-images.githubusercontent.com/40894871/155327968-770c6f93-3c27-4584-b719-6e247d826ca9.png)

**Comment by pataar** [comment]
Given you have 8 cores:
`0.17 / 8 = 0.02` which translates to 2% :)

**Comment by jalanjarosz** [comment]
Well, That makes sense.   It just was not what I expected.  :-)

**Comment by jalanjarosz** [comment]
Closing issue since an answer has been provided.
