### ISSUE TITLE
Check for updates/upgrades shouldn't be disabled

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#678]
**Describe the bug:**\
Check for updates/upgrades shouldn't be disabled during printing BUT actual upgrade buttons should be.

**Expected behavior:**\
You should be able to check for and see upgrades but not upgrade until printing is complete.

**Screenshots:**\
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1135694/156003775-b1b01160-eb0a-47f7-8545-bb12a8483df7.png">

**Logfiles:**\
n/a

**Comment by meteyou** [comment]
ok. it is the docs from moonraker: https://moonraker.readthedocs.io/en/latest/web_api/#get-update-status

```
Note that the refresh argument is ignored if an update is in progress or if a print is in progress. In these cases the current status will be returned immediately and no refresh will take place.
```
