### ISSUE TITLE
Select multiple files to delete in G-code and Machine files

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/mainsail#686]
### Requested feature:

We need to be able to select multiple files to delete in G-code files.  It is very time consuming to clean up.  Same for Machine files.

### Solves the following problem:

Very time consuming to delete multiple files.

### Additional information:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1135694/156481954-c45a52fe-187e-43b2-ba17-7a6a46f3c8f7.png">

**Comment by meteyou** [comment]
Pls check all FR... This FR all ready exists and I'm working already on it.

https://github.com/mainsail-crew/mainsail/issues/500
