### ISSUE TITLE
Webcam not working

### ISSUE THREAD

**Issue by asdfire1** [mainsail-crew/mainsail#699]
### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I get no image from camera in mainsail, if I go to the camera address (http://192.168.87.169:8080/?action=stream) I get an image.
Here are my camera settings, I tried putting http://192.168.87.169:8080/?action=stream as url stream and also changing the regular mjpeg to adaptive mjpeg and I get no image from the camera. I'm adding a screenshot of the camera config as well as webcam.txt
![image](https://user-images.githubusercontent.com/45483619/156860175-cf11f076-29ad-43fd-b858-f818027e7509.png)
[webcam.txt](https://github.com/mainsail-crew/mainsail/files/8189459/webcam.txt)

### What did you expect to happen instead?

I expected there to be image in mainsail

### How to reproduce this bug?

I installed mainsail os with raspberry pi imager, its a fresh install. I have not used mainsail before.

**Comment by asdfire1** [comment]
Same config for both adaptive and regular mjpeg works in Firefox.
![image](https://user-images.githubusercontent.com/45483619/156860488-2d8fa66f-cdbf-4e8d-a0b3-f95da34190b9.png)

**Comment by meteyou** [comment]
do you use also my.mainsail.xyz with chrome? you have to change some flags in chrome if you want to use my.mainsail.xyz.
