### ISSUE TITLE
Upload gcode files / edit config via WebDAV mounts

### ISSUE THREAD

**Issue by alexvonsiebenthal** [mainsail-crew/mainsail#710]
### Requested feature:

it would be handy if the directory for the GCode files – and potentially the config files too – could be mounted as WebDAV drives in Explorer/Finder/Linux Window Manager of choice.

### Solves the following problem:

Easier file management than through web interface. Renaming, removing, sorting etc. Also, not all slicers support direct upload via Octoprint API.

### Additional information:

There are a few open source WebDAV libraries available for web projects in PHP, Python and others. No need to completely reinvent the wheel.

**Comment by meteyou** [comment]
mainsail is a JS/TS frontend and runs exclusively on the client in the browser. so you couldn't even integrate something like that.

if you need webDAV, you can simply install it on the raspberry.
