### ISSUE TITLE
[FR] Temporal ordering button on main UI console controls

### ISSUE THREAD

**Issue by TodWulff** [mainsail-crew/mainsail#719]
### Requested feature:

Addition of temporal ordering button along side filter/?/...

### Solves the following problem:

If there was a traffic 'ordering' button alongside the other buttons, to have the console's temporal order toggled (instead of having to go into the settings UI to toggle it), that would be pretty darn useful.  In production use (i.e. when printing), having new traffic appear on top is 'traditional', however, during a config dev/testing effort, it helps to have the console populated top down (oldest on top).   Being able to toggle the console in that manner via a console UI button would be nice - it's not a 'gotta have', of course.

**Comment by meteyou** [comment]
I am closing this FR, because no other user liked or commented this FR until now.
