### ISSUE TITLE
[FR] save collapse elements per device/group in dashboard

### ISSUE THREAD

**Issue by tispokes** [mainsail-crew/mainsail#728]
### Requested feature:

Sometime I minimize some panels (e.g. console) on my mobile device but I don't them to deselect/hide generally.
On my tablet and espacially on my desktop I want it to be expanded all the time.

Would like to set it per group (desktop/phone) or even per device (phone #1, phone #2 ...)

### Solves the following problem:

Expanding/minimzing panels if a user switches devices

**Comment by meteyou** [comment]
thx for your request! i implemented this feature already in the develop branch and it will be part of the next release.

https://github.com/mainsail-crew/mainsail/pull/696
