### ISSUE TITLE
The possiblility to "Drag and drop", straight to the dashboard

### ISSUE THREAD

**Issue by DragonFlyer007** [mainsail-crew/mainsail#737]
### Requested feature:

The possibility to drag and drop gcode files straight to anywhere on the dashboard. (...or spesific area)
Like without having to go to the gcode tab.

(This is possible on Fluidd if i remember correct?)
Really neat function.

**Comment by meteyou** [comment]
Fixed it with this PR #777

**Comment by DragonFlyer007** [comment]
Latest Klipper update has now eabled this. Very nice!

**Comment by th33xitus** [comment]
> Latest ~~Klipper~~ Mainsail update has now eabled this. Very nice!

You're welcome 😉

**Comment by DragonFlyer007** [comment]
> > Latest ~Klipper~ Mainsail update has now eabled this. Very nice!
> 
> You're welcome 😉

😂
Omg, yeah.... Mainsail! 🙈🤦‍♂️

**Comment by th33xitus** [comment]
The drag & drop feature of Mainsail has nothing to do with the Klipper installation.

**Comment by DragonFlyer007** [comment]
> The drag & drop feature of Mainsail has nothing to do with the Klipper installation.

Yeah, that's what so wierd :? Pure Mainsail, right? Why isn't here anymore then. Hmm
