### ISSUE TITLE
G-Code Viewer with bed mesh leveling displays incorrect Z position.

### ISSUE THREAD

**Issue by KocsisV** [mainsail-crew/mainsail#770]
### What happened?

In the G-Code Viewer the displayed nozzle position does not take into account the bed mesh leveling. This results in a Z offset between the loaded and tracked model and the displayed nozzle position. This only affects the first x number of layers where klipper compensates for the unevenness of the bed.

### What did you expect to happen instead?

The G-Code viewer displaying the compensated Z position if a print is in progress. Or maybe have a switch to switch between the absolute and compensated one.

### How to reproduce this bug?

Load a bed mesh which has huge huge a Z offset, eg 10mm, try start printing and check the live tracking in the G-Code viewer.

### Additional information:

Mainsail version V2.1.2

**Comment by meteyou** [comment]
the gcode viewer works perfectly because it should display the gcode in the first line.

but there is no information from klipper to display the nozzle in the simulated position in real-time, only the machine coordinates in real time. so it's not possible to display it in another way.
