### ISSUE TITLE
Job Queue Continues To Process Jobs With A Completed Job Still On The Build Plate.

### ISSUE THREAD

**Issue by Maker3DPrininting** [mainsail-crew/mainsail#771]
### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

I had a job queue of about 10 prints processing my first job completed and was on the build plate. The next job in the queue started on its own and hit the parts on the tray.

I added the following to Moonraker.conf to try to prevent this from happening again but it still occurs.

[job_queue]
load_on_startup: False
automatic_transition: False

### What did you expect to happen instead?

I expected the first job to finish and that I would clear the build surface and push the start button manually to start the next job in the queue.

### How to reproduce this bug?

Run jobs in the queue and it will happen again.

### Additional information:

This has been going on since February and I have tried everything I know to do to resolve the issue. This feature is super important as I have 12 Voron machines using the queue system everyday and they all have had this happen. Some more regular than others. I am using the queue more as a reference right now stating a file from the main file directory then removing it from the queue list so I know what to print next.

**Comment by meteyou** [comment]
jobqueue is a moonraker feature. so mainsail has no effect on the behaviour. if you still have the bug, feel free to open an issue in moonraker github repo.
