### ISSUE TITLE
Unable to print after update

### ISSUE THREAD

**Issue by soleshoe** [mainsail-crew/mainsail#800]
### Browser:

Chrome

### Device:

Laptop

### Operating System:

macOS

### What happened?

Mainsail OS was working fine until I made an update this morning. The cura2moonraker plugin gets the following error when sending an object to the printer : 

**Moonraker error:**
There was a network error: 401 error transferring http://mainsailos.local/server/files/upload - server replied : internal server error

When I check in mainsailOS UI, the object is present in the "GCode files" section, but if I click on the object and then on the "START PRINT" button, nothing happens.

I tried rebooting printer + raspberry pi and problem still present.

### What did you expect to happen instead?

Printing GCode stored !

### How to reproduce this bug?

100% reproductible with 13/05/22 update around 8am CEST

### Additional information:

klipper v0.10.0-408-g2c441b45
moonraker v0.7.1-569-gbabfba1
print_area_bed_mesh v1.2.1-13-gcb49478
mainsail v2.1.2

mcu(stm32f103xe)
Version: v0.10.0-184-gdd714fc7
Load: 0.01, Awake: 0.00 , Freq: 72 MHz

mcu rpi(linux)
Version: v0.10.0-184-gdd714fc7
Load: 0.02, Awake: 0.00 , Freq: 50 MHz

Host(armv7l)
Version: v0.10.0-408-g2c441b45
OS: Raspbian GNU/Linux 10 (buster)
Load: 0.08, Mem: 131.4 MB / 871.7 MB, Temp: 41°C

**Comment by th33xitus** [comment]
We are aware of that issue, but this is not a Mainsail issue.
It is due to a recent Moonraker update.

You need to roll back Moonraker by at least two commits. SSH into the host and do the following:
```
cd ~/moonraker
git reset --hard HEAD~2
sudo systemctl restart moonraker
```
Do not update Moonraker afterwards for now.

**Comment by soleshoe** [comment]
Perfect, working again, thanks 👍

**Comment by th33xitus** [comment]
PSA: Arksine pushed a fix for the recent issue. Update Moonraker again and everything should work again.
https://github.com/Arksine/moonraker/commit/0164bb239ea1032e105428435ff2643378bf4bfa
