### ISSUE TITLE
System Loads Text color black on dark grey . 

### ISSUE THREAD

**Issue by gurusonwheels** [mainsail-crew/mainsail#807]
### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Text in System Loads is  now almost unreadable as color of text is black on a dark grey background . 
![Screenshot 2022-05-15 at 15-03-06 Voron 2 2896](https://user-images.githubusercontent.com/3314914/168489815-77b29cac-e4c5-4319-982e-f4d66a70a903.png)

### What did you expect to happen instead?

status to be readable .

### How to reproduce this bug?

load system loads .

**Comment by th33xitus** [comment]
Are you using a custom theme?

**Comment by gurusonwheels** [comment]
> Are you using a custom theme?

not that im aware of ... how would i know ?

**Comment by th33xitus** [comment]
Check your klipper_config folder for a folder named `.theme`. And if it exists, there is probably a css file in there.

**Comment by gurusonwheels** [comment]
> Check your klipper_config folder for a folder named `.theme`. And if it exists, there is probably a css file in there.

went in KIAUH and done remove theme ...  works as should . do not remember ever installing a theme . did not even know that existed .   thanks
