### ISSUE TITLE
Need power off at shutdown

### ISSUE THREAD

**Issue by whoim2** [mainsail-crew/mainsail#811]
### Requested feature:

At "shutdown" menu element need call poweroff via pin from "power" section of moonraker

**Comment by th33xitus** [comment]
Please elaborate.

**Comment by whoim2** [comment]
> Please elaborate.

At select "shutdown" menu in mainsail/fluidd, moonraker activate power off procedure from "power xxx" section for power off device

**Comment by th33xitus** [comment]
So what you are asking for is, when you click on this button here:
![image](https://user-images.githubusercontent.com/31533186/168583588-fcc25bba-0531-457e-9c8f-b570f5b9ed08.png)
moonraker should shut down the printer?

**Comment by whoim2** [comment]
> So what you are asking for is, when you click on this button here: ![image](https://user-images.githubusercontent.com/31533186/168583588-fcc25bba-0531-457e-9c8f-b570f5b9ed08.png) moonraker should shut down the printer?

Shutdown RPi, not printer. Power pin not changed.

**Comment by th33xitus** [comment]
> Shutdown RPi, not printer.

That's what this button does:
![image](https://user-images.githubusercontent.com/31533186/168584231-7f27b68a-2034-4fcb-8442-e55c5339451d.png)

**Comment by whoim2** [comment]
> > Shutdown RPi, not printer.
> 
> That's what this button does: ![image](https://user-images.githubusercontent.com/31533186/168584231-7f27b68a-2034-4fcb-8442-e55c5339451d.png)

Yes, this button shutdown RPi, but not change power pin as described in "power xxx" section of moonraker.conf

**Comment by meteyou** [comment]
this button only sends this command: https://moonraker.readthedocs.io/en/latest/web_api/#shutdown-the-operating-system

I think you misunderstand the setting in the moonraker power device:

```
off_when_shutdown: False
#   If set to True the device will be powered off when Klipper enters
#   the "shutdown" state.  This option applies to all device types.
#   The default is False.
```

the important part of this description is this: `when Klipper enters the "shutdown" state"`
this setting only switches off the pin when the Klipper state == "shutdown" and hot the RPI itself. If you shutdown your RPI, it cannot execute anything because it is shutdown!

**Comment by whoim2** [comment]
> this button only sends this command: https://moonraker.readthedocs.io/en/latest/web_api/#shutdown-the-operating-system
> 
> I think you misunderstand the setting in the moonraker power device:
> 
> ```
> off_when_shutdown: False
> #   If set to True the device will be powered off when Klipper enters
> #   the "shutdown" state.  This option applies to all device types.
> #   The default is False.
> ```
> 
> the important part of this description is this: `when Klipper enters the "shutdown" state"` this setting only switches off the pin when the Klipper state == "shutdown" and hot the RPI itself. If you shutdown your RPI, it cannot execute anything because it is shutdown!

im change inverse mode to normally (1 on, ,0 off), and adding pin up to config.txt for fast start. Now worked good.

**Comment by Nastras** [comment]
> this button only sends this command: https://moonraker.readthedocs.io/en/latest/web_api/#shutdown-the-operating-system
> 
> I think you misunderstand the setting in the moonraker power device:
> 
> ```
> off_when_shutdown: False
> #   If set to True the device will be powered off when Klipper enters
> #   the "shutdown" state.  This option applies to all device types.
> #   The default is False.
> ```
> 
> the important part of this description is this: `when Klipper enters the "shutdown" state"` this setting only switches off the pin when the Klipper state == "shutdown" and hot the RPI itself. If you shutdown your RPI, it cannot execute anything because it is shutdown!

Is it possible to change this command that is sent to Moonraker?

**Comment by meteyou** [comment]
@Nastras Sorry... I think, I cannot follow you...

The Shutdown button sends the shutdown API command, and the reboot button, sends the reboot API command...

**Comment by Nastras** [comment]
I use Klipper with root on a creality k1 printer. I am aware that I cannot shut down the printer with a shutdown command in mainsail.

But the reboot command should work right?
When I press the reboot button in the mainsail menu nothing happens. If I send a command via the terminal only "reboot" to the printer it restarts completely. I had hoped that this also works via clipper?

**Comment by meteyou** [comment]
Sry... It's impossible to support any Creality Klipper/Moonraker/OS version. Creality doesn't use any "klipper-standard".

As a next point, Creality doesn't use a standard Mainsail and has an adapted version. So I ask you to simply write to Creality support directly. They have to fix their product themself...
