### ISSUE TITLE
Temp chart shows "null RPM" for fans w/o tachometer pins defined

### ISSUE THREAD

**Issue by TodWulff** [mainsail-crew/mainsail#818]
### Requested feature:

https://i.imgur.com/xOmwF1T.png

If possible, when a fan doesn't have a tach input defined, can the 'null RPM' be suppressed on the Temp table.

Just a low priority nice to have.  TIA for any consideration.

### Solves the following problem:

Simply provides a more elegant less cluttered implementation.

**Comment by th33xitus** [comment]
Thanks for the request. That makes definitely sense to me!

**Comment by th33xitus** [comment]
I already wondered why that should even happen and display null. Now looking at the code, it was definitely not intended to be shown! So you found a bug im going to fix! I will re-label this issue from a feature request to a bug report.

Thanks again!
