### ISSUE TITLE
why remove the scroll bar from text editor?

### ISSUE THREAD

**Issue by Fuckingnameless** [mainsail-crew/mainsail#819]
### Requested feature:

page up & down doesn't work either so we´re handicapped  inside the code editor

**Comment by th33xitus** [comment]
The scrollbar did not get removed.
Currently, in v2.1.2 the scrollbar appears only if you start scrolling with the mousewheel or moving to the edge of the browser window. We changed that for v2.2.0. The scrollbar will then be permanently visible.
You can try out the changes with installing the current v.2.2.0-beta3

We know about the page up/down issue and already have a PR for that open. It needs a bit more tweaking but we are on it!
