### ISSUE TITLE
Gcode Preview no Object / Nothing shown

### ISSUE THREAD

**Issue by Robnex** [mainsail-crew/mainsail#829]
### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Hello,

1. Upload Gcode file
2. GCode Files - Right Click - 3D View
3. Open 3D View Tab
4. No object visible but file active

### What did you expect to happen instead?

On Step 4.

Show Gcode / STL 3D File Preview

### How to reproduce this bug?

The bug is reproducable every time i try to View the 3D object.

Also on Firefox / Chrome / Edge

**Comment by meteyou** [comment]
should be fixed with this PR: https://github.com/mainsail-crew/mainsail/pull/847
