### ISSUE TITLE
locale(ru):  Not the correct name of the button in Russian localization

### ISSUE THREAD

**Issue by Switch2002** [mainsail-crew/mainsail#835]
### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

An error in Russian localization. When starting the print on the button, it is written "Druck Starten".
![Снимок](https://user-images.githubusercontent.com/57393418/169660449-e152d12a-727e-4c73-98bf-39031bb13f0d.PNG)

### What did you expect to happen instead?

In Russian localization, instead of "Druck Starten" should be "Распечатать"

### How to reproduce this bug?

Turn on Russian localization and start printing

**Comment by th33xitus** [comment]
Thanks for reporting. Will be fixed once https://github.com/mainsail-crew/mainsail/pull/836 gets merged!
