### ISSUE TITLE
Setting to disable Autoscroll

### ISSUE THREAD

**Issue by MrKumaPants** [mainsail-crew/mainsail#838]
### Requested feature:

It would be helpful if there was a setting for the console (maybe an addition to the button that contains hide temperatures?) that disables auto scroll. It's difficult debugging klipper scripts, and measurement or calibration output when the console is continuously scrolling to bottom.

**Comment by chrispitzer** [comment]
+1 to this feature request.
Autoscroll continuously snapping my console to the bottom makes looking back at stuff on the console useless while the printer is running. Please add a feature to disable this "snap to bottom" feature! <3
