### ISSUE TITLE
Edit temperature on Mobile Device

### ISSUE THREAD

**Issue by SchwabJ** [mainsail-crew/mainsail#857]
### Browser:

Chrome

### Device:

Mobile device (Phone, Tablet or similar)

### Operating System:

Android

### What happened?

Hello, 
with v2.2.0-beta3 i cant edit the temperature (extruder, heatbed,...)on my phone (Pixel 6 Pro, Android 12, Chrome) . After type in a new temp nothing happens.

### What did you expect to happen instead?

Set the new temp like on desk. 

### How to reproduce this bug?

Pixel 6 Pro, Android 12, Chrome

### Additional information:

![Temp_Bug](https://user-images.githubusercontent.com/93655993/170844271-cb008bb4-731e-4906-86bf-389a627b1829.jpeg)

**Comment by th33xitus** [comment]
Please update to beta4.
That was a bug, and it got fixed with beta4.

**Comment by meteyou** [comment]
issue was fixed with this PR: https://github.com/mainsail-crew/mainsail/pull/828
