### ISSUE TITLE
Is something off with the extruder section calculation?

### ISSUE THREAD

**Issue by PhilBaz** [mainsail-crew/mainsail#869]
### Browser:

Chrome

### Device:

Laptop

### Operating System:

Windows

### What happened?

 My normal extrusion setting of  5-7mm/s is now producing clicking....I have been using these settings a while. 

Also, the new calculation says I should expect 109mm of filament for 25mm requested. Maybe I'm misunderstanding something.

![Screenshot 2022-06-05 212050](https://user-images.githubusercontent.com/21558241/172089483-040cff48-f41b-4a95-a28a-79eff87c310b.jpg)

### What did you expect to happen instead?

 No clicking extruder, as usual....

The calculation should show the requested amount of filament. 25mm requested should show estimated extrusion 25mm @ Xmm^3

### How to reproduce this bug?

extrude?

**Comment by meteyou** [comment]
If you use the correct nozzle size on your config, it should be 109mm extruded filament.

**Comment by PhilBaz** [comment]
@th33xitus 

Do you happen to know the calculation?   I'm curious to understand.

**Comment by PhilBaz** [comment]
Ahh okay.....its volumetric.      Its listed as mm currently. Perhaps labelling it mm^3 would eliminate some confusion for others.


                     v-if="filamentDiameter && nozzleDiameter"
                        style="font-size: 0.8em"
                        class="text--disabled text-caption font-weight-light d-flex justify-center">
                        {{ $t('Panels.ExtruderControlPanel.EstimatedExtrusion') }} ~ {{ extrudedLength }} mm @
                        {{ volumetricFlow }} mm³/s
                    </div>


get extrudedLength(): number {
        return Math.round(this.feedamount * this.extrudeFactor * (this.filamentDiameter / this.nozzleDiameter))

**Comment by PhilBaz** [comment]
No, I'm still missing the point....

Its extruding 25mm of filament. The max volumetric that could be is 60mm^3.

Sorry, I'm just trying to understand....what measurement is the 109mm ?

**Comment by PhilBaz** [comment]
@th33xitus

Yes, I thought volume, not volumetric flow rate, but absolute volume.

 Ahhh, its the length coming out the tip of the nozzle. Sorry, have never even thought about it from that angle before.  

Got it...thanks...sorry.

**Comment by th33xitus** [comment]
I thought i made it clear with:
> The calculation of the estimated extrusion is to be seen after the nozzle orifice.
25mm of requested filament do not translate to 25mm of extruded (molten) filament.

in this comment https://github.com/mainsail-crew/mainsail/issues/869#issuecomment-1147527344 😄
anways, glad you understand now.

**Comment by PhilBaz** [comment]
@th33xitus 

You did, but the switch in my brain hadn't flipped yet....you made it clear, for sure.
