### ISSUE TITLE
Temperature graph State

### ISSUE THREAD

**Issue by numindast** [mainsail-crew/mainsail#883]
### Requested feature:

The temperature graph currently displays nozzle and bed temperature, and works well.

Can we also have, or access a toggle for, plotting the heater State %'s too?

My reasoning: one can tell at a glance when the PWM power state to the heaters has levelled off. This would be a good way to tell if my bed, and its glass plate, have stabilized and no more "heat soak" patience is required. Useful for preheating.

Thanks!!

### Solves the following problem:

Knowing when a bed (or hot end) has reached full heat-soaked stable operation.

**Comment by meteyou** [comment]
just click on the heater and enable PWM in chart.

**Comment by numindast** [comment]
I feel dumb. Thank you and sorry for the useless FR.
