### ISSUE TITLE
Power On button when printer is disconnected.

### ISSUE THREAD

**Issue by LazaroFilm** [mainsail-crew/mainsail#897]
### Requested feature:

When the printer is off, I need to go into the top right power menu to turn it on, I would love a Power on button in the main view when the printer the Printer switch is detected in the OFF position.
![Screen Shot 2022-06-12 at 1 47 22 PM](https://user-images.githubusercontent.com/18351100/173246711-38a126c3-3d6f-4281-927d-964e7571dc6e.png)

### Solves the following problem:

Adding a Power On Printer button in the main dashboard area when the Printer switch is Off.

**Comment by meteyou** [comment]
Something like this is on our to-do list, but I think I will only display one panel with "print is off -> switch on" or something similar.

**Comment by LazaroFilm** [comment]
Amazing news!  .... waits... (jk. You guys are doing an amazing job already, no rush, take your time, I'll just be here, waiting patiently)

**Comment by LazaroFilm** [comment]
> > ### Requested feature:
> 
> > When the printer is off, I need to go into the top right power menu to turn it on, I would love a Power on button in the main view when the printer the Printer switch is detected in the OFF position. ![Screen Shot 2022-06-12 at 1 47 22 PM](https://user-images.githubusercontent.com/18351100/173246711-38a126c3-3d6f-4281-927d-964e7571dc6e.png)
> 
> > 
> 
> > ### Solves the following problem:
> 
> > Adding a Power On Printer button in the main dashboard area when the Printer switch is Off.
> 
> > 
> 
> > ### Additional information:
> 
> > _No response_
> 
> 
> 
> Hi, how to make Power on button ?

The image is a "photoshop" of what it could look like. To my understanding, as of now, it is not possible to have a power on button.

**Comment by jordandrako** [comment]
Why wouldn't it be possible? Wouldn't it just be a matter of having an option to expose specific power devices on the dashboard (or even the top bar would be nice)
