### ISSUE TITLE
'Malformed command' if using macro with custom parameter

### ISSUE THREAD

**Issue by nofuturekid** [mainsail-crew/mainsail#901]
### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Starting a macro with a custom value for it's parameters, the macro call is malformed.
Klipper console: "Malformed command 'SAFE_RAISE_Z Z5'"
![image](https://user-images.githubusercontent.com/7026230/173334913-3505e3e7-82a6-419b-a31c-8f85d634269c.png)

![image](https://user-images.githubusercontent.com/7026230/173335342-33a5f2e0-a02b-438c-aa6d-c5eda269fb2c.png)

If I put into the value field "=5" it works, but is inconvenient and not expected.

### What did you expect to happen instead?

That the macro call would look like: "SAFE_RAISE_Z Z=5"

### How to reproduce this bug?

Never tested it before but my current setup:

* Windows 11
* Chrome 102.0.5005.63
* Mainsail 2.2.0

### Additional information:

Macro parameters and their values should be separated with an "=" sign, ie. "SAFE_RAISE_Z Z=5"

**Comment by meteyou** [comment]
we have analyzed this issue again and merged a bugfix. Klipper checks the macro name itself and if this is gcode-style (M123 or G123) macro, then no `=` is needed. if this is an extendet gcode, as in your case, a = is always needed for the attributes.
