### ISSUE TITLE
Graph the average PWM heater values

### ISSUE THREAD

**Issue by onde2rock** [mainsail-crew/mainsail#905]
### Requested feature:

I just discovered that we can graph the PWM values for the heater.
However, for me the PWM is all over the place and not very user-friendly :

![image](https://user-images.githubusercontent.com/3342132/173878009-583e6ff9-1e2d-4d61-8930-3ffc0bd45fe8.png)

Is is possible to instead plot the average PWM, like when hovering over the value:
![Screenshot_20220615_182807](https://user-images.githubusercontent.com/3342132/173879396-6e0e8fda-45c7-48e9-bf64-66d3b85ff800.png)

I'm guessing this value is a rolling average over a minute ?

Since this value is already here, It should not be very difficult to add.
I'm trying to look in  ``src/components/charts/TempChart.vue`` and ``src/store/printer/tempHistory/actions.ts``, but I never used vue.js, so I'm a little lost.

Do you have any pointer where to start ?

**Comment by meteyou** [comment]
to show PWM is to see issues with the PWM settings. for example, your chart looks like really really bad PWM values. if you have the right values, you should have close to a stable line.

so... it would be bad to make an average PWM value to display in the chart.

**Comment by onde2rock** [comment]
Ok, makes sense.
That would explain why the auto pid tuning was not working as good as expected.
There must some problem in my setup, I will investigate.
Thanks

**Comment by meteyou** [comment]
feel free to join our discord for helping!
