### ISSUE TITLE
[FR] add print jobs to job queue in batches

### ISSUE THREAD

**Issue by sheldo26** [mainsail-crew/mainsail#920]
### Requested feature:

continuous printing, expanding the functionality of job queue,

add jobs to the continuous printing queue, multiply the number of times the job is printed consecutively
run cleaning script/macro after each print

**Comment by th33xitus** [comment]
What is your exact feature request? Mainsail already has a job queue and continuous printing is a Moonraker feature: <https://moonraker.readthedocs.io/en/latest/configuration/#job_queue>
Running a macro after each print is also configures via the moonraker.conf.

Can you elaborate on the exact functionality you want to see improved?

**Comment by sheldo26** [comment]
thank you, big help,

functionality to improve, when job is added to the queue, we are able to set number of times it reprints, before it moves to the next job in the list

example Job Queue:
Job A print: "10" times
Job B print: "3" times

this would reduce the over number of jobs in the queue, allowing users to better refine total prints when needing to continuous printing of the same model.

**Comment by th33xitus** [comment]
I see, now i understand your idea. I will re-open this ticket. If we close it, we can't track that feature request anymore.
