### ISSUE TITLE
Power toggle initially grayed out on secondary printer instance

### ISSUE THREAD

**Issue by numanair** [mainsail-crew/mainsail#929]
### Mainsail Version:

~~v2.1.2~~ v2.2.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

When trying to switch to and then power on my secondary printer, the power toggle is grayed out. If the power state is switched externally with the 2nd printer active in Mainsail, the toggle is no longer grayed out. I am 80% sure this used to work.

### What did you expect to happen instead?

Can toggle printer power.

### How to reproduce this bug?

1. Load Mainsail on 1st printer
2. Select 2nd printer from dropdown in Mainsail 
3. Attempt to toggle power from the Mainsail power menu

### Additional information:

1st printer serves Mainsail while the 2nd printer is just Moonraker and Klipper. They are running on two SBCs. If this is not the ideal setup I am open to suggestions.

**Comment by meteyou** [comment]
pls upload mainsail and test it again

**Comment by numanair** [comment]
I am actually still having the same issue after all.

**Comment by numanair** [comment]
I have narrowed down the issue slightly. The button is only grayed out after starting a print on the first printer. I do have `locked_while_printing` in my Moonraker config.

**Comment by meteyou** [comment]
pls post your moonraker configs of both printers. do you also updated to v2.2.x?

**Comment by numanair** [comment]
Yeah, I am on v2.2.1.
[moonraker(1).txt](https://github.com/mainsail-crew/mainsail/files/9124496/moonraker.1.txt)
[moonraker(2).txt](https://github.com/mainsail-crew/mainsail/files/9124495/moonraker.2.txt)

**Comment by meteyou** [comment]
both are the same moonraker config file. port 7125

**Comment by numanair** [comment]
Should I change the port? They are from two different moonraker instances each running on their own pi. Two printers, two pi's. I switched away from multi instance/single pi as I was having issues with crashes.

**Comment by meteyou** [comment]
ah ok. sry. mixed it up. thought you have both on the same pi. then its all ok

**Comment by meteyou** [comment]
pls upload also both moonraker.log files. i tested it with your config, but it works for me.

**Comment by numanair** [comment]
moonraker.logs:
[moonraker(1).log](https://github.com/mainsail-crew/mainsail/files/9128847/moonraker.1.log)
[moonraker(2).log](https://github.com/mainsail-crew/mainsail/files/9128846/moonraker.2.log)

Try these repro steps:
(ender3=printer1 running mainsail, MPSM=printer2)

1. Connect to mainsail (pi1)
2. Switch to printer2 from the top dropdown 
![image](https://user-images.githubusercontent.com/8195699/179431376-64f42743-925d-422f-9867-c8cb67708a6e.png)

3. Power on printer2 from the power menu 
![image](https://user-images.githubusercontent.com/8195699/179431391-454558e3-8434-4f0a-a309-651d1f2116b8.png)

4. Start a print
5. At this point printer 1 in the top dropdown shows as disconnected & grayed out. Not sure if this is related. 
![image](https://user-images.githubusercontent.com/8195699/179431414-99eb4246-a593-4155-8460-20ed28a53140.png)

6. Switch to printer 1 from the printers menu by first clicking "reconnect" and then "switch to printer" 
![image](https://user-images.githubusercontent.com/8195699/179431425-bd0e8d59-d601-4171-8c6a-04773ca3e748.png) 

![image](https://user-images.githubusercontent.com/8195699/179431439-78a47d26-649e-44b3-a258-489835219a7a.png)


7. Power device cannot be toggled from the menu. 
![image](https://user-images.githubusercontent.com/8195699/179431451-624df7b9-6edb-43de-b22b-29e209ca8ff2.png)

8. Reload the page. Power can now be toggled. 
![image](https://user-images.githubusercontent.com/8195699/179431482-3dfea69b-0d5e-42b2-9ac2-448c45bba3f6.png)

9. Switching between printers with the "switch to printer" button again grays out the toggle.

**Comment by meteyou** [comment]
I think it is more an issue, that Moonraker cannot connect to the plug ant that's why it is disabled.

**Comment by numanair** [comment]
I am not so sure about that. If that was the case, why does the printing state affect the other printer's toggle?

**Comment by numanair** [comment]
Fixed with v2.3

**Comment by meteyou** [comment]
thx for your feedback!
