### ISSUE TITLE
12hr Clock formatting for Print ETA

### ISSUE THREAD

**Issue by d-nx** [mainsail-crew/mainsail#934]
### Requested feature:

It would be great to have the option for 12hr Clock formatting Print ETA. For example= 1D:1H:1M:1S
![screenshot](https://user-images.githubusercontent.com/80003983/175777037-18159ca7-20f0-48b0-9f7c-69763a4f37f2.png)

**Comment by JamesIV4** [comment]
This would be great!

**Comment by mcmasterp** [comment]
+1 for this

**Comment by meteyou** [comment]
@d-nx your example does not fit for 12hr clock formation or better for ETA. "1D:1H:1M:1S" is a duration and not a time.

**Comment by ubqtous** [comment]
+1
