### ISSUE TITLE
Libcamera stack support for webcam

### ISSUE THREAD

**Issue by krollnux** [mainsail-crew/mainsail#935]
### Requested feature:

I have couple rpi cameras that I would love to use. It uses libcamera instead raspicam. Plus the new debian bullseye switched to libcamera aswell. I got it to work for octopi but not for mainsail and fluidd. Can you please add libcamera support on mainsail. My cameras is imx915 16mp autofocus arducam and 64mb Hawkeye autofocus arducam.

### Additional information:

I used arducam mjpg-streamer for octopi they have instructions on how to do it on their site.

**Comment by meteyou** [comment]
Mainsail is just a web GUI and it runs only in your browser. so it have nothing todo with hardware or webcams.

Pls check our other project we are will use to support webcams on your hosts/rpi: https://github.com/mainsail-crew/crowsnest
