### ISSUE TITLE
Adding folder with spaces vs renaming folder with spaces in filemanager

### ISSUE THREAD

**Issue by daniel-volz** [mainsail-crew/mainsail#941]
### Mainsail Version:

2.2.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Creating a folder in the gcode filemanager using spaces, the UI tells me that this creation is not possible with using space chars.

Renaming a folder and using spaces seems no problem

### What did you expect to happen instead?

No Errormessage when creating a folder using spaces

### How to reproduce this bug?

Try to create a folder in the gcode filemanager with spaces in the Folder Name.
That wont work. Create a folder and then rename the folder with spaces in the Name wont be no problem

**Comment by th33xitus** [comment]
Thanks for reporting. I was able to reproduce that issue.
