### ISSUE TITLE
Special characters in folder names cause printing to crash

### ISSUE THREAD

**Issue by daniel-volz** [mainsail-crew/mainsail#947]
### Mainsail Version:

v2.2.1

### Browser:

Firefox

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

Folders with special characters such as äüö can be created in the file manager.
If a file is saved in it, the attempt to print a file fails with the message "Internal error on command: "SDCARD_PRINT_FILE".

### What did you expect to happen instead?

It should not be possible to create folders with special characters

### How to reproduce this bug?

Go to file manager und add a folder, in Example: "Raspberry Pi Gehäuse"
Due to bug #941 you have to create the folder first and then rename it.
Place a Printfile in there and try to start a print
Error Message "Internal error on command: "SDCARD_PRINT_FILE" will appear in log

**Comment by th33xitus** [comment]
Hi, i just tried to reproduce the bug. For that i didn't use the folder name you recommended, instead i just used `öäüß`, i used the same name for the gcode. 
![22-08-01_20-02-39_brave](https://user-images.githubusercontent.com/31533186/182213335-23af8591-3be5-476e-b3fa-7e81beddfcf2.png)
As you can see, the print is running, and i can assure you, my printer right now is still printing that part. Hence im not able to reproduce the issue you report.
