### ISSUE TITLE
Pressure Advance settings missing from dashboard machine settings

### ISSUE THREAD

**Issue by noahliketheark** [mainsail-crew/mainsail#980]
### Mainsail Version:

v2.2.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

After updating Mainsail, the dashboard machine settings only list MOTION and FIRMWARE RETRACTION. PRESSURE ADVANCE has been moved to Extruder Dashboard, but when defining an alternate stepper with T0 and T1 macros, pressure advance is not visible. Removal of second stepper config options restores the setting boxes.

### What did you expect to happen instead?

Pressure advance options available in dashboard for a 2-in 1-out configuration

### How to reproduce this bug?

Defining an alternate extruder stepper removes pressure advance

[extruder_stepper right_stepper]
extruder: extruder
step_pin: PC1
dir_pin: !PC3
enable_pin: !PC7
full_steps_per_rotation: 200
rotation_distance: 5.7
microsteps: 16

**Comment by th33xitus** [comment]
Please see: https://github.com/mainsail-crew/mainsail/issues/845
