### ISSUE TITLE
Printer name header when using code editor.

### ISSUE THREAD

**Issue by d-nx** [mainsail-crew/mainsail#985]
### Requested feature:

For Multi-Printer users.

When editing your printer.cfg, it would be helpful to see your printer name up top.

![Screen Shot 2022-07-22 at 3 34 37 PM](https://user-images.githubusercontent.com/80003983/180514708-14528d02-0cf9-421f-add7-224864cf0b12.png)

As seen below, once you enter the code editor, the printer's name goes away:
![Screen Shot 2022-07-22 at 3 29 06 PM](https://user-images.githubusercontent.com/80003983/180514259-87db9178-1c9c-457e-be2f-ae00121df4eb.png)

**Comment by meteyou** [comment]
You should see the printer name in your browser tab. I don't think it makes sense to add this to the editor top bar, because especially with small screens there is very little space.
